### ISSUE TITLE
Template engine for render views

### ISSUE THREAD

**Issue by hallison** [perwendel/spark#1]
Hi Wendel,

First, congrats for this great project.

How to render a template source like [Sinatra](http://github.com/sinatra/sinatra)? In a [Sinatra](http://github.com/sinatra/sinatra) code I use the following instructions:

``` ruby
get "/" do
  erb :index
end
```

The template for index page can be find (read) in views (default) directory.

In the Spark Java, maybe use the follow syntax:

``` java
get(new Route("/") {
  @Override
  public Object handle(Request request, Response response) {
    return jsp("index");
  }
});
```

Ryan Tomayko (@rtomayko) develop the [Tilt](http://github.com/rtomayko/tilt), a template handler for Sinatra.

**Comment by Veske** [comment]
Is there a solution like this for Spring using Thymeleaf also?

**Comment by tipsy** [comment]
@Veske Spark supports Thymeleaf, if that's what you were wondering.
