### ISSUE TITLE
Request Async Support Release

### ISSUE THREAD

**Issue by keuller** [perwendel/spark#1000]
Hey guys,

I'd like to know when will be released next version ? I've seen that there are 2 PR (issues #983 and #953) to provide async request. We're building a big ingestion system based on SparkJava, this feature will be very good for us. If dont have any release plan to support it coming soon, maybe we need change SparkJava for other HTTP solution.

I will be glad for any thoughts.

Regards.

**Comment by tipsy** [comment]
Async will not be included in the next release, but probably in Spark 3.0 some time later this year.
