### ISSUE TITLE
SparkJava 2.5 holding static files open?

### ISSUE THREAD

**Issue by davidfordaus** [perwendel/spark#1001]
It appears that even after a stop() SparkJava holds static files open?  

Background: 
* Windows, SparkJava core 2.5
* Our UI developer would like to be able to make static file changes, save them and refresh the browser to see the changes.  This is a normal fast UI development cycle. To restart the app every time isn't acceptable in terms of development speed
* However - Our UI Dev is receiving a "user mapped file section open" error when trying to save, indicating to me that SparkJava is holding the file open (!).
* So - we've tried implementing a "stop" so that SparkJava would shut down and restart when you pressed a key, expecting that this would release files.
* However - even after a stop, the files are still open and the UI designer isn't able to save them.  In short: with the exception of completely restarting the app we don't seem to have any easy way to achieve a typical UI development work cycle of "save, refresh browser" as files are being held open.

Preferences:

* A switch within SparkJava that files are closed immediately after being read - slow, but provides for fast UI development cycles.  We have less than a few tens of megabytes of static content, so this could simply be cached internally with periodic file system date-modified checks.
* OR SparkJava properly releases all file handles on a stop().  I'm frankly not sure whether it's an accident (bug) or by-design that it holds the file handle open after the read completes.

Any thoughts would be appreciated and potentially we're happy to update SparkJava ourselves to achieve this, however we see both file handle leakage and the impact on the typical Dev cycle as reasons to fix the issue from within the core team.

**Comment by toyg** [comment]
Spark 2.5 has a [a known vulnerability](https://vuldb.com/?id.93236) when using static files. You should upgrade to the latest build.
