### ISSUE TITLE
Illegal character on proxy https connection

### ISSUE THREAD

**Issue by RyanSusana** [perwendel/spark#1008]
Hello spark friends,

I am deploying my spark app with docker.

I am using nginx and letsencrypt to point to the containers  running sparkjava.

So nginx handles https for me. 

Everything works fine except I get a WARN log.
`Illegal character 0x18 in state=START for buffer HeapByteBuffer` Spamming my SLF4J logs

I need to see the info logs so I cant set the logger level higher.

Is there any way to solve it other than using secure()?

**Comment by toyg** [comment]
It's probably due to something NGINX says when talking to spark/jetty. Some details here: https://stackoverflow.com/questions/32300109/header-parse-error-after-upgrade-to-jetty-9-3

I would check what nginx is passing with something like wireshark.
