### ISSUE TITLE
Unexpected 404 with exceptionHandler with empty response body

### ISSUE THREAD

**Issue by jlorenzen** [perwendel/spark#1011]
It seems spark will return a 404 when an `exception` handler does not set the response body. The following should reproduce the issue:
```java
before("/foo", (request, response) -> throw new CustomException());
get("/foo" (request, response) -> "Hello");
exception(CustomException.class (ex, request, response) -> {
    response.status(401);
    response.header("WWW-Authenticate", "Bearer");
    // response.body("");
});
```

When the line `response.body` is commented out, hitting that endpoint will result in a 404. When the line is uncommented out, a 401 is returned. It doesn't seem like we should have to set the response body.

**Comment by tipsy** [comment]
Routes need to return a value (or have a body set), or they will result in a 404. It's known behavior, but it hasn't been changed due to backward compatibility.

**Comment by jlorenzen** [comment]
ok thanks @tipsy
