### ISSUE TITLE
Feature Request: Support a micro http server like NanoHttpd

### ISSUE THREAD

**Issue by ajma** [perwendel/spark#103]
Support a micro http server like NanoHttpd
https://github.com/elonen/nanohttpd

It would be awesome if I could embed this into Android.

**Comment by daluu** [comment]
@perwendel, I see this marked closed. What is the resolution? Won't support, or support has been added in?

**Comment by tipsy** [comment]
It was closed as a `Won't fix`.

**Comment by daluu** [comment]
Thanks for the update. I wonder with respect to this item, whether the feature of swapping in another web server would suffice? http://sparkjava.com/documentation#other-web-server. If the default embedded jetty server doesn't work for Android.

**Comment by tipsy** [comment]
I think it would be possible, if the other web-server supports Servlets.
