### ISSUE TITLE
Reloading of static assets: Where is "localhost" defined? Documentation clarification ....

### ISSUE THREAD

**Issue by mhulse** [perwendel/spark#1034]
Hello,

The docs have this example:

```java
if (localhost) {
    String projectDir = System.getProperty("user.dir");
    String staticDir = "/src/main/resources/public";
    staticFiles.externalLocation(projectDir + staticDir);
} else {
    staticFiles.location("/public");
}
```

But I get:

```bash
  symbol:   variable localhost
  location: class Main
/.../Main.java:21: error: illegal start of type
        if (localhost) {
           ^
```

How do I define localhost? Is that a command line arg that I need to set?

In terms of the docs, and making this issue not a pure question, it might be nice to show or describe how to do this with a more complete example?

**Comment by mhulse** [comment]
Ok, simple a property fixes the issue:

```java
public static boolean localhost = true;
```

Any tips on how to flip that for a prod build vs. dev build?

I think where I got thrown off is that the variable name "localhost" implies that there should be something looking for "localhost" in URL ... Which, I'm sure I could engineer ... At first I thought it might be built in to Spark.

**Comment by medicm** [comment]
I don't think this is an issue with spark, you can do something like:
```java
if (request.host().equals("localhost") || request.host().equals("127.0.0.1")) {
    // local
} else {
    // not
}

**Comment by mhulse** [comment]
I think someone here suggested:

```java
if (request.host().equals("localhost") || request.host().equals("127.0.0.1")) {
    // local
} else {
    // not
}
```

Which looks pretty neat in terms of checking if `localhost` ... Though, where I set `staticFiles.location` is in the constructor of my Spark app’s main class. I don't see that `request` is passed in to this class other than when calling routes/`before`/`after`.

**Comment by tipsy** [comment]
Hi @mhulse,

You can launch your app with a dev/localhost config file (using something like [args4j](https://github.com/kohsuke/args4j)), then that would be picked up by an if-statement like the one in your first comment.

Static files have to be configured before starting the server, so there is no way to change the configuration per request.

**Comment by mhulse** [comment]
@tipsy Thanks!!!!

I'll check out args4j and post back my findings tomorrow (and close out issue). Hopefully this issue will help future noobs. 👍 

Appreciate the help!
