### ISSUE TITLE
[FeatureRequest] Url for static resources

### ISSUE THREAD

**Issue by vlio20** [perwendel/spark#1039]
Hi,
Fom the documentation I see that the static files are read from the resources folder:

> // root is 'src/main/resources', so put files in 'src/main/resources/public'
> staticFiles.location("/public"); // Static files

And would be served when the following url would be provided:
> http://{host}:{port}/css/style.css

My question is: is it possible to place the files in the `resources/public` but access it with a different url. For example: `http://{host}:{port}/MyApp/site/static`

Note: putting nested directories will result putting the index.html file in to url in order to get it server (which should be the default response)

**Comment by vlio20** [comment]
Is there any way to workaround it? redirects?

**Comment by tipsy** [comment]
If your main problem with using nested directories is that `index.html` has to be in one URL, I would write a custom handler that serves that particular file. Or maybe I misunderstood?

**Comment by vlio20** [comment]
there are 2 issues here:
1. Say I want to serve my site from: https://mysite.com/site -> this will result the index.html
2. I want my website assets to be served from https://mysite.com/site/static (example: https://mysite.com/site/static/main.css)

**Comment by vlio20** [comment]
Can you please also show the Kotlin version of your suggestion?

**Comment by vlio20** [comment]
found it:
`Spark::class.java.getResourceAsStream()
`
Trying to make it work

**Comment by vlio20** [comment]
@tipsy it did work.
Though I think this feature should be baked into the framework.

Thanks!
