### ISSUE TITLE
Add matchedRoute field to Request object

### ISSUE THREAD

**Issue by robax** [perwendel/spark#1048]
Currently on a Spark request you are able to retrieve the requested URI or path. However, there's no way to work backwards from the URI to find out which route it was mapped to. I should mention that this is specifically only an issue when parameters are involved. I can see that the request's pathInfo is "/users/bob" but I can't pull the matched route of "/users/:username".

For context, we want to inspect requests in the after() block and instrument them by route.

This is a pretty tiny change so if I get approval I'd be happy to submit a PR. Thanks ya'll. :)

**Comment by jon-ruckwood** [comment]
This would also resolve #959

**Comment by robax** [comment]
@tipsy do you have an idea of when @perwendel will be back? it seems he's been gone almost 3 months

**Comment by tipsy** [comment]
Sorry @robax, I don't really know.

**Comment by tipsy** [comment]
This has been merged now!

**Comment by robax** [comment]
Thanks you @tipsy !

**Comment by adriancole** [comment]
Thank you!
