### ISSUE TITLE
Type Safe Route Definitions

### ISSUE THREAD

**Issue by SixBitProxyWax** [perwendel/spark#1061]
Hello,

I was wanting to write some code to make endpoint definitions safer, but didn't know if I should just create my own project or if it might be something of interest for the core project.

The basic idea is to allow things like:

```java
// Route would be like a function that can return tuples of parameters
Route route = Root.literal("users").int().literal("posts").int().literal("title");
// this route would provide a tuple from Integer x Integer
Endpoint.get(route).apply(params ->{
  // here we don't need to find and parse parameters from the route
  // we have already been given a nice tuple of Integers.
  // We may need to pass in a request here or something
  // not sure the details
});
```

I suspect we could also do something to encode the expected query parameters to make them type safe as well. The idea being that the route and query definitions would allow us to have type safe handlers and hide boiler plate for lookups and parsing in a safe way.

It may even be possible to incorporate some request header handling, but that's not something I am really thinking about at the moment.

Clearly, this needs to be fleshed out, but I wanted to know if there is any desire at all to investigate this or not. If not, I'll go do it for myself.

**Comment by tipsy** [comment]
I think the odds of merging something like this into Spark are very low. Personally I'm very interested in what you'll come up with though. Could you keep this issue updated, or link to your project when you create it?

**Comment by tipsy** [comment]
I think it's very unlikely that something like this will be merged into Spark. Personally I'm very interested in what you'll come up with though. Could you keep this issue updated, or link to your project when you create it?

**Comment by SixBitProxyWax** [comment]
Sure thing.

**Comment by perwendel** [comment]
Added in #1170
