### ISSUE TITLE
First request is always WAY slower than second for the same resource

### ISSUE THREAD

**Issue by richarddd** [perwendel/spark#1068]
### Issue
The first request to ANY resource is always much slower than the second one to that resource. This seems to happen after some idle as well

### How to reproduce
_With kotlin:_
```kotlin
fun main(args: Array<String>) {
    get("/hello") { req, res -> "Hello World" }
}
```

_...or java:_

```java
public class HelloWorld {
    public static void main(String[] args) {
        get("/hello", (req, res) -> "Hello World");
    }
}
```

Get request
http://localhost:4567/hello

**First** request is on my machine around ***144 ms***
**Second** request is around ***10ms***

Is this something related to jetty? Could this be configured?

**Comment by perwendel** [comment]
This is related to Jetty! I've seen issue reports for Jetty on this.
