### ISSUE TITLE
Spark cannot load static resources from jar files.

### ISSUE THREAD

**Issue by y-kaku** [perwendel/spark#1074]
Spark cannot load static resources from jar files.

spark framework version 

```
compile group:'com.sparkjava', name:'spark-core', version:'2.7.2'
```

code

```
staticFileLocation("/public");
```

gradle run on the console screen

```
2018-10-24 09:58:46,034 [INFO -spark.staticfiles.StaticFilesConfiguration] StaticResourceHandler configured with folder = /public
```

java -jar static-file-bug-1.0-SNAPSHOT-jar-with-dependencies.jar

```
nothing log
````

**Comment by toyg** [comment]
Works fine for me in 2.8.0 (although I use Maven). Have you checked the files are actually packed in the jar? Note also that they will be mounted in the URL at /, not /public -- that path is simply the folder in `resources` where Spark will look.

**Comment by hoto** [comment]
Also did you run `init()` to ignite the spark?

```
Static files location must be configured before route mapping. If your application has no routes, init() must be called manually after location is set.
```

source: http://sparkjava.com/documentation#static-files

**Comment by perwendel** [comment]
This has worked for a very long time and changes to this functionality has not been done in quite a while. Closing for now.
