### ISSUE TITLE
Use of deprecated setSoLingerTime Jetty method causes a warning.

### ISSUE THREAD

**Issue by skyghis** [perwendel/spark#1080]
A call to a Jetty **deprecated**  method [`setSoLingerTime`](https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/server/ServerConnector.html#setSoLingerTime-int-) should be removed to avoid pollution on server initialization log : 

```
[info] org.eclipse.jetty.util.log:193         - Logging initialized @3471ms to org.eclipse.jetty.util.log.Slf4jLog
[WARN] org.eclipse.jetty.server.AbstractConnector:450  - Ignoring deprecated socket close linger time
[info] spark.embeddedserver.jetty.EmbeddedJettyServer:142  - == Spark has ignited ...
```

Call done at [SocketConnectorFactory.java(L105)](https://github.com/perwendel/spark/blob/c697d981268c538dfeeb38786bd9eb0a03ab86f0/src/main/java/spark/embeddedserver/jetty/SocketConnectorFactory.java#L105)

```java
private static void initializeConnector(ServerConnector connector, String host, int port) {
    // Set some timeout options to make debugging easier.
    connector.setIdleTimeout(TimeUnit.HOURS.toMillis(1));
    connector.setSoLingerTime(-1);
    connector.setHost(host);
    connector.setPort(port);
}
```

**Comment by toyg** [comment]
Pinging @tipsy @perwendel easy one to merge

**Comment by tipsy** [comment]
Thanks, merged.

**Comment by perwendel** [comment]
Fixed
