### ISSUE TITLE
Update spark-core version in Getting Started docs

### ISSUE THREAD

**Issue by jon-ruckwood** [perwendel/spark#1083]
The Maven coordinates in the [Getting Started][0] section for `spark-core` needs be updated from `2.7.2` to `2.8.0`. I would have submitted a PR but it wasn't clear to me where it should be directed.

[0]: http://sparkjava.com/documentation#getting-started

**Comment by toyg** [comment]
I believe it's https://github.com/perwendel/spark-web-page

**Comment by jon-ruckwood** [comment]
The readme says it's no longer in use. 😕

**Comment by toyg** [comment]
Lol, yeah, sorry, it's actually https://github.com/perwendel/perwendel.github.io - I checked

**Comment by perwendel** [comment]
Fixed.
