### ISSUE TITLE
Travis CI failing with invalid certificate

### ISSUE THREAD

**Issue by huangminchn** [perwendel/spark#1154]
Good afternoon.

I created a PR to allow configuring the Jetty SSL: https://github.com/perwendel/spark/pull/1153
At the beginning, the travis CI failed because the project is using oraclejdk8; after upgrading to oraclejdk9, it started complaining about the certificate:
https://travis-ci.org/perwendel/spark/builds/619856630?utm_source=github_status&utm_medium=notification

I have found some posts that reported the same issue: http://blog2.vorburger.ch/2016/04/how-to-resolve-validatorexception-pkix.html Could you please try the fix mentioned in it? Thanks.

**Comment by perwendel** [comment]
Fixed!
