### ISSUE TITLE
Add ability to set cookie "samesite" setting, by updating embedded Jetty to version 9.4.23 or newer, 

### ISSUE THREAD

**Issue by stevemcleod** [perwendel/spark#1161]
Jetty 9.4.23 introduces a way to set a "samesite" value for cookies. This is needed to deal with a change introduced by Google Chrome 80 (released Feb 2020).

Relevant Jetty issue here: https://github.com/eclipse/jetty.project/issues/4247

Heroku has a good description of the problem here: https://blog.heroku.com/chrome-changes-samesite-cookie

Could we please have an update release of Spark with the latest Jetty release?

**Comment by perwendel** [comment]
Fixed by #1162
