### ISSUE TITLE
When is 2.9.2 with new Jetty version going to be released?

### ISSUE THREAD

**Issue by nickel-bert** [perwendel/spark#1182]
I saw that the jetty version has already been bumped up to the latest version and that the next release of spark has been prepared.
But when will the new version actually be released? 
Ops are already bugging me because of a severe security issue in jetty 9.4.27-9.4.29.

If it's not coming any time soon i will probably need to fork and create my own version.
Something I would like to prevent however ...

Thanks!

**Comment by c-rack** [comment]
As far as I can see, it is already in Maven Central:
https://mvnrepository.com/artifact/com.sparkjava/spark-core/2.9.2

and includes latest Jetty 9.4.30: https://github.com/perwendel/spark/pull/1179

**Comment by nickel-bert** [comment]
Oh, sorry. I expected to see it listed under releases and in the README.md. 

Thanks or the information!
