### ISSUE TITLE
Notify about release 2.9.2

### ISSUE THREAD

**Issue by michelvosje** [perwendel/spark#1187]
I discovered by coincidence that version 2.9.2 has been released:
https://twitter.com/sparkjava/status/1293108939727556608

There is no message about this on the official news page:
http://sparkjava.com/news

And it can also not be found on the Github release page:
https://github.com/perwendel/spark/releases

The Download and Docs page refer to 2.9.2. But the Github page still refers to 2.9.1.

**Comment by perwendel** [comment]
done!
