### ISSUE TITLE
Code sample：Cannot resolve method 'afterAfter' in 'FilterExample'

### ISSUE THREAD

**Issue by landou1107** [perwendel/spark#1198]
Code sample：
**Error**
afterAfter("/hello", (request, response) -> response.header("finally", "executed even if exception is throw"));
afterAfter((request, response) -> response.header("finally", "executed after any route even if exception is throw"));

**Right**
after("/hello", (request, response) -> response.header("finally", "executed even if exception is throw"));
after((request, response) -> response.header("finally", "executed after any route even if exception is throw"));

**Comment by perwendel** [comment]
I tried, it works. You just need to import the method.
