### ISSUE TITLE
ability to stop server

### ISSUE THREAD

**Issue by tclavier** [perwendel/spark#120]
Hello,

in my integration test class in @Before i start a Spark server ... but in After i can't stop it. 

is it possible to have a Spark.stop() to do that ?

**Comment by bliti** [comment]
I wrote this on issue #39 . Not looking to spam. Just looking out for people who might be doing web searches for this. :)
---
Just dropping this here:

I'm enjoying Spark with Netbeans and was facing a similar issue. I was able to find and modify a bash script that worked (under Linux and OSX, not Windows support).

I've put it up in github:

https://github.com/bliti/killnetty
