### ISSUE TITLE
Feature Request: Testing Documentation and Examples

### ISSUE THREAD

**Issue by patnaikshekhar** [perwendel/spark#133]
Could we add some documentation on how to test routes in the framework with some examples? The Flask docs (python) seem to have a detailed description on how to test application written in the framework. It would be very helpful to have something similar for Spark.

**Comment by Lewiscowles1986** [comment]
Also is there code coverage to ensure the tests cover as much as is possible? Btw Amazing framework, Java programming can be so long winded

**Comment by tipsy** [comment]
Have a couple of testing tutorials here: https://sparktutorials.github.io/
