### ISSUE TITLE
Return null after calling response.redirect might cause "response already committed" exception?

### ISSUE THREAD

**Issue by thickvisor** [perwendel/spark#141]
_v1.1.1_

Hello, maybe I'm doing something wrong, but I get "response already committed" exceptions with the following

```
get(new Route("/test") {
    @Override
    public Object handle(Request req, Response res) {
            // do work...   
            res.redirect(somePath);
            return null;
    }
});
```

It happens only when my app is deployed into web container (Tomcat) using the SparkFilter approach. Embedded jetty works fine.

Changing it to 

```
res.redirect(somePath);
return ""; // blank string
```

solves the issue.
PS: have yet to test against v2.0.0, downloading soon..

**Comment by Matyeu** [comment]
#910
