### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by S11001001** [perwendel/spark#162]
Could you tag the releases?  I've prepared some tags; running this in `sh` should tag all releases and push.

```sh
git tag 2.0.0 fa3cae9b2bff944c7c88c0e567d4544bb8d9e89c
git tag 1.1.2 ab8de107373acbd7f0eb8f78405024813b9ffe68
git tag 1.1.1 a19594a0e9d824c61996897cf8d1efcd9da43313
git tag 1.1 3d0cfc1f630259f14c9266a9cd564be10daa9363
git tag 1.0 458806a680d2a43dcf2a7c8facdccb11424a76fa
git tag 0.9.9.4 f51b243dae2f8fe73defb950cd203c0606dc7773
git push --tags origin
```

**Comment by tipsy** [comment]
@S11001001 Could you complete the list?

**Comment by S11001001** [comment]
@tipsy The ones I've listed are the reliable ones; others aren't as clear-cut, e.g. c4b5a13b74202d06c76edf70aacf1e4602cc7cdf, which mixes a jump from 0.9.9.1-SNAPSHOT to 0.9.9.2-SNAPSHOT with code changes.  Did these code changes end up in the 0.9.9.1 release or not?  Or maybe some of them did, some didn't?  I can't tell without source packages.

Nevertheless, here are my best guesses at the rest of them.

```sh
# the less-reliable guesses; maybe add a ? to the tags
git tag 0.9.4 1441261c1368cd5d64b2b4b1e6b990f124d91155
git tag 0.9.6 0c1815c06eaeb4ecb5ce703a0b136dbf6bfcecbe
git tag 0.9.7 83bb6edb0d88cc24450762b93d64c4681945d606
git tag 0.9.8 3eff8947e6416eb9fc2985450a17b492b4b6bf49
git tag 0.9.9 f95965fb50fb12af5be56ae54a56ac1b97bcb919
git tag 0.9.9.1 c4b5a13b74202d06c76edf70aacf1e4602cc7cdf
git tag 0.9.9.2 76b86d14d12858ff49d8df7adbffc4461c67246d
git tag 0.9.9.3 0cdfab2aa59b716e5e5aea80f37e008aa407d028
git tag 0.9.9.5 587400d0754f6c9e54cb3c82516884b59596955c
git tag 0.9.9.6 c4bc83901877e32bf9cbbca3db665f21aa168083
```

**Comment by tipsy** [comment]
@S11001001 I've added the tags you suggested originally. Adding the rest might be a little much, especially if they're not reliable? I really have no idea what went on in Spark four years ago :)
