### ISSUE TITLE
Refactor (Routes and Filters)

### ISSUE THREAD

**Issue by amarseillan** [perwendel/spark#177]
I've been stumbling though the code and found out that before and after are part of the the HttpMethod enum. I believe this was made to treat filters as routes, but I don't think this brings in easy coding or any other advantage. The code ends up doing things like 

```
if (filterTarget instanceof FilterImpl) {
```

Is there any other reason why  Routes and Filters should be treated as one?

**Comment by tipsy** [comment]
Is this fixed?

**Comment by amarseillan** [comment]
I never proposed a change, no one seemed to care =P

**Comment by tipsy** [comment]
I'm trying to care now (cleaning up our issues). 
Looking at HttpMethods, before/after definitely seem out of place (not being, well, HttpMethods), but could you give me a bit more context to your example? When do you need to do instanceof?
Also, Routes and Filters are already two different interfaces, where are they treated as one?

**Comment by amarseillan** [comment]
[here](https://github.com/perwendel/spark/blob/master/src/main/java/spark/webserver/MatcherFilter.java#L123) is where you need the instanceof

and [here](https://github.com/perwendel/spark/blob/master/src/main/java/spark/SparkInstance.java#L320-L330) is where they are treated as one (see add route and add filter do the same thing, they just put a different HTTP method/name)
