### ISSUE TITLE
Add SSL information to spark README

### ISSUE THREAD

**Issue by tchoulihan** [perwendel/spark#189]
Hey everyone, so I looked for documentation on how to get spark working with SSL, and finally found a thread in the google group.

After many hours of searching, I finally got my SSL working in spark, using this guide:
https://stackoverflow.com/questions/906402/importing-an-existing-x509-certificate-and-private-key-in-java-keystore-to-use-i/8224863#8224863

And including this line to the webservice.
` SparkBase.setSecure(keystore or .jks file location string, keypass,null,null);`

This is something that should be in the spark README.

**Comment by stowns** [comment]
what was the behavior when it was not working? My server appears to start in secure mode but I can't hit it.

[Thread-8] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@704df5f5{SSL-HTTP/1.1}{0.0.0.0:3000}

**Comment by tchoulihan** [comment]
I'm pretty sure it throws some SSL exceptions if it was initialized wrong. If it didn't throw any exceptions, then try hitting your webservice using https://, and it should work.

**Comment by tchoulihan** [comment]
I'm pretty sure it throws some SSL exceptions if it was initialized wrong. If it didn't throw any exceptions, then try hitting your webservice using https://, and it should work.

**Comment by tchoulihan** [comment]
I'm pretty sure it throws some SSL exceptions if it was initialized wrong. If it didn't throw any exceptions, then try hitting your webservice using https://, and it should work.

**Comment by tchoulihan** [comment]
I'm pretty sure it throws some SSL exceptions if it was initialized wrong. If it didn't throw any exceptions, then try hitting your webservice using https://, and it should work.

**Comment by tchoulihan** [comment]
I'm pretty sure it throws some SSL exceptions if it was initialized wrong. If it didn't throw any exceptions, then try hitting your webservice using https://, and it should work.

**Comment by tchoulihan** [comment]
I'm pretty sure it throws some SSL exceptions if it was initialized wrong. If it didn't throw any exceptions, then try hitting your webservice using https://, and it should work.

**Comment by tipsy** [comment]
Made this more clear in the docs now, and created an example repo on GitHub: 
http://sparkjava.com/documentation.html#secure (this was always here)
http://sparkjava.com/documentation.html#enable-ssl (this is new)
https://github.com/tipsy/spark-ssl (this is new)
