### ISSUE TITLE
Request#body() empty in Route if previously accessed in a Filter

### ISSUE THREAD

**Issue by mikolak-net** [perwendel/spark#201]
If `Request#body()` is called in a `Filter` mapped for a HTTP request, subsequent calls in the `Route` for this request will return an empty string.

I suspect this is simply to due to a new `Request` being created for each processing stage, and the previous read exhausting the corresponding `InputStream` in the `HttpServletRequest`.

**Comment by ecamaj** [comment]
This is not working in "before" filters too. After filter is working OK, but in before, req.body() is lost after first "consummation".

**Comment by Frietziek** [comment]
Same problem here with before and body coming with an empty string.
