### ISSUE TITLE
staticFileLocation messes up binary files (e.g. images)

### ISSUE THREAD

**Issue by zeroflag** [perwendel/spark#215]
In SparkFilter>>doFilter() there is an IOUtils.copy that copies from an InputStream to a Writer with no encoding. If the resource is a binary file (e.g. png) then its content will be corrupt.

I propose changing that line to: IOUtils.copy(resource.getInputStream(), response.getOutputStream());

What do you think?

Regards
Attila Magyar

**Comment by c-rack** [comment]
I have the same problem and proposed a pull request that fixes this issue: https://github.com/perwendel/spark/pull/235
