### ISSUE TITLE
Can not access response from routes in the after filters

### ISSUE THREAD

**Issue by kliakos** [perwendel/spark#221]
It would be nice (not to say necessary) if response returned from route could be accessed with response.body() in the after filters.

This would enable easy response logging for example.

Otherwise, what is the purpose of the response.body() getter method?

I have already made this PR #211 that takes care of this issue.

**Comment by aldendaniels** [comment]
Thanks @kliakos! I would love to see the PR merged.

Per the docs:
> After filters are evaluated after each request and can read the request and read/modify the response

Without this fix, we currently can't "read" the response body.

**Comment by kliakos** [comment]
@aldendaniels  I had missed that notice in the docs.

This means that reading the response is the desired behaviour, not a change I propose. The current behaviour is definitely a bug as it is right now.

To deal with this I use my own custom build over the official one, since I see no progress overall in the project.

**Comment by angexis** [comment]
No flame war intended with my PR #412 ... I just thought that the PR #211 had been around for over a year now and tried to figure out if there was a reason for it stagnation... Any of the two PRs reaching the next release would be really very nice! For me, this a kind of blocker...

**Comment by kliakos** [comment]
No problem @angexis, as long as it does the trick. I really hadn't thought the case of the response body being binary or stream. Your solution seems much more robust, however there are much more changes also for the admins to review.

**Comment by kliakos** [comment]
Issue has been fixed in the latest commits.

**Comment by angexis** [comment]
To be honest, I have closed #412 w/o testing because my project no longer uses Spark... Cheers

**Comment by tipsy** [comment]
Fixed in 2.5
