### ISSUE TITLE
Best User Authentication Method?

### ISSUE THREAD

**Issue by AlexAbraham1** [perwendel/spark#225]
Hey! I am new to SparkJava and so far I am loving it!

I was wondering what the best way to add users to my site would be. I would want to authenticate them at every protected page (using a filter probably), and I would also want to store the user passwords in a SQL database using some form of encryption. I have a rudimentary version of user account control in my project so far but I am not sure where to go from here.

https://github.com/AlexAbraham1/SparkJavaTest

Any help would be greatly appreciated!

Thanks :-)

**Comment by tchoulihan** [comment]
For user authentication, read some articles about cookie-based authentication. I used this for my spark site, and its what the majority of websites use.

Basically it goes like this, once a user has sent a POST to your login page, you generate a random string, called a session ID, as their cookie. use spark response.setcookie to do this. Make sure you set the expiration on the cookie to what is reasonable(maybe 1 hour to 1 day). 

Then, keep a database or in memory map of this sessionID string, to a username. Then when a request is made to spark, you can take this sessionID, and associate it internally with the correct user.

IMO, generating a completely random string for each login is good enough security.

Here's a more detailed description of this:
http://stackoverflow.com/questions/6631834/authenticate-system-without-sessions-only-cookies-is-this-reasonably-secure?rq=1

**Comment by Serranya** [comment]
Jetty generates an manages a sessionId cookie by itself. You solution should be used for a "keep me logged in" system.

**Comment by AlexAbraham1** [comment]
Should there be a separate table in the MySQL database called "tokens" which contains a random string (the sessionID string) and the userID associated with it? Or should the sessionID be another field in the "users" table?

**Comment by tchoulihan** [comment]
The first. Think about it, if you tried to put this in the user table, how would you put potentially hundreds of session IDs in one user row? Make sure you study up on your SQL one-to-many relationships.

Also, here's how you encrypt and check a password with jasypt. Again, NEVER STORE USERS PASSWORDS. You'd run the .checkPassword when a user does a login POST.
```
StrongPasswordEncryptor passwordEncryptor = new StrongPasswordEncryptor();
String encryptedPassword = passwordEncryptor.encryptPassword(userPassword);
...
if (passwordEncryptor.checkPassword(inputPassword, encryptedPassword)) {
  // correct!
} else {
  // bad login!
}
```
