### ISSUE TITLE
Gzip compression of content

### ISSUE THREAD

**Issue by fab1an** [perwendel/spark#229]
I found no way of doing this in Spark. In Jetty you can do it this way:

```
GzipHandler gzip = new GzipHandler();
gzip.setMimeTypes("text/html");
gzip.setHandler(new HelloHandler());
```

**Comment by pazhapn** [comment]
+1

**Comment by gencube** [comment]
How about this???
http://sparkjava.com/documentation.html#response-transformer
```java
get("/hello", "text/html", (request, response) -> {
    return new MyMessage("Hello World");
}, new GzipTransformer()); // 
```

**Comment by tipsy** [comment]
This should work automatically now: 

    after((request, response) -> {
        response.header("Content-Encoding", "gzip");
    });
