### ISSUE TITLE
Setting the content-type inside a ResponseTransformer

### ISSUE THREAD

**Issue by zeroflag** [perwendel/spark#230]
I have a response transformer that generates JSON objects. Unfortunately there is no way to set the content-type of the response (application/json) inside the transformer. I think this functionality belongs to the same object that generates the JSON object.

```
public class JsonTransformer implements ResponseTransformer {
    private Gson gson = new Gson();
    @Override
    public String render(Object model) {
        return gson.toJson(model);
    }
}
```

**Comment by codexorange** [comment]
From ResponseTransformer I guess that you can't set the response type, but you can from the method that you return a json object.

```java
get("/resource", (request, response) ->  {
    response.type("application/json");
    MyResource myResource = Service.getResource();
    return myResource;
}, new JsonTransformer());
```

For me it works :)

**Comment by zeroflag** [comment]
Yes, this is how I do it now (also I can set it in a before or after filter as far as I remember). But the problem is, when I change the response transformer I also need to change the content type because those two things are usually coupled together. It would make sense to do both in one place.

**Comment by ribomation** [comment]
I agree. It would be convenient to tie type and formatting together in a response-transformer.

**Comment by beihaifeiwu** [comment]
+1, I also want this feature, It will be great

**Comment by tipsy** [comment]
ResponseTransformer will receive a makeover soon.
