### ISSUE TITLE
Synchronous initialization

### ISSUE THREAD

**Issue by pizerg** [perwendel/spark#236]
On slow working devices (ex. Raspberry Pi Model B / B+) Spark server might appear as "initialized" (no way to check if it's operational or not) when ignite thread has not finished, it would be useful to have a way of checking if the server is actually initialized or maybe to do it synchronously.

**Comment by tchoulihan** [comment]
I'm dealing with this issue too. Here's the thread:

https://github.com/perwendel/spark/issues/226

How I solved it for my project, was to use polling... poll every second until it comes back with a result.

**Comment by amarseillan** [comment]
I fixed this on PR #238, you have SparkBase.awaitInitialization() which blocks until jetty is initialized. Wait for that PR to be merged or fork and merge it yourself =)

**Comment by drabiter** [comment]
+1

A blocking initialization will make integration test cleaner and stable.

**Comment by tipsy** [comment]
Fixed.
