### ISSUE TITLE
Add ability to create URL string from route and parameters

### ISSUE THREAD

**Issue by BabakMN** [perwendel/spark#241]
Is there a facility to allow creation of URL for a route? I think this would be very useful.

For example in Flask you can use `url_for` ([+](http://flask.pocoo.org/docs/0.10/quickstart/#url-building)):

``` python
>>> print url_for('profile', username='John')
/profile/John/
```

You can then use `url_for` in your views to prevent from having to hard-code URLs everywhere.

What are your thoughts on this?

**Comment by vbauer** [comment]
:+1:
