### ISSUE TITLE
Set port

### ISSUE THREAD

**Issue by benjyz** [perwendel/spark#243]
great project.

set port is marked as deprecated, but the [docs](http://sparkjava.com/documentation.html#port) are not up to date. What to use instead?

**Comment by davidvollmar** [comment]
From the javadoc:

`public static void port(int port)`

Set the port that Spark should listen on. If not called the default port is 4567. This has to be called before any route mapping is done. If provided port = 0 then the an arbitrary available port will be used.

**Comment by pkafel** [comment]
As fas as I can see documentation is up-to-date right now so I guess we can close this issue right @benjyz ?

**Comment by benjyz** [comment]
AFAICS setting port is deprecated (?)

**Comment by pkafel** [comment]
Hey @benjyz !

Yes, method `setPort(int port)` is deprecated and just as @davidvollmar pointed out you should used `port(int port)` instead. Javadoc to `setPort(int port)` is pointing to `port(int port)` as well.

In the page under the link you have provided every thing looks fine in my opinion however if you see something out-dated please report that.

If by documentation you mean README and so on then here you go - https://github.com/perwendel/spark/pull/268 Those are only occurrences of `setPort(int port)` I was able to find. If I missed something please do not hesitate to put it here !
