### ISSUE TITLE
Type safe routes and ResponseTransformers

### ISSUE THREAD

**Issue by zeroflag** [perwendel/spark#246]
I wonder why Routes and ResponseTransformers use Object as a parameter or a return. I'm not against dynamic typing in general, but this is something that could have been done in a type safe way in my opinion.

E.g.

```
interface Route<T> {
    T handle(Request request, Response response);
}

interface ResponseTransformer<T> {
    String render(T model);
}

<T> void get(String path, Route<T> route, ResponseTransformer<T> transformer) {
    // somewhere else
    String rendered = transformer.render(route.handle(req, resp));
    // whatever logic  
}
```

Now, I can create a type safe route as follows:

```
get("/path",  (req, resp) -> "someString" , model -> model.toUpperCase() );
```

The type of the model is known by the compiler (it is a string), and it is enforced that the output of the route must have the same type than the input of the response transformer.

Now, I can also create domain specific response transformers beside the general ones (e.g. json), and this is my main motivation.

```
class UserDTOTransformer implements ResponseTransformer<User> {
    @Override
    public String render(User user) {
        return json(new UserDTO(user));
    }
}

get("/path",  this::findUser , new UserDTOTransformer());
```

The return type of the findUser must be User. With the current solution, I have to make sure that the output type of the findUser and the input type of the transformer are in sync.

**Comment by amarseillan** [comment]
:+1:

**Comment by tipsy** [comment]
We'll have a look at this for v3.
