### ISSUE TITLE
Logging of Jetty verbose

### ISSUE THREAD

**Issue by benjyz** [perwendel/spark#247]
AFAICS there is no option to set Jetty to a less verbose logging mode. Running Spark I get a lot of output. I currently pipe system.out. into a file, but a specific logging function would be nice.

See also: http://stackoverflow.com/questions/9235809/how-to-enable-debug-level-logging-with-jetty-embedded

**Comment by mddubey** [comment]
Hello team
what is the status of this feature? Is there a way now I can turn off console logs ?

Thank you
Mritunjay Dubey

**Comment by tipsy** [comment]
Not sure if fixed. Closing this because we need to clean up. Please create a new issue if this is still a problem.
