### ISSUE TITLE
Support resume of large file downloads (from static files / public directory)

### ISSUE THREAD

**Issue by dns** [perwendel/spark#257]
It seems Spark doesn't support HTTP byte-range to resume download.
This feature is very useful if the client (browser/download manager) requested very large files.

**Comment by gencube** [comment]
+3
Hear hear. 
Developer should consider open up using Pattern like this:

```java
public class MyStaticFileHandler implements StaticFileHandlerTransformer {
}

staticFileLocation("/public", new MyStaticFileHandler()); // Static files
externalStaticFileLocation("/var/www/public", new MyStaticFileHandler()); 
```

**Comment by dns** [comment]
Doesn't work that way.

**Comment by S66D** [comment]
I think this [stack**overflow** question](http://stackoverflow.com/questions/38916978) is connected with this issue is't not?

**Comment by dns** [comment]
Yes, it's seem related.

**Comment by tipsy** [comment]
Not sure if fixed. Closing this because we need to clean up. @dns, please create a new issue if this is still a problem.
