### ISSUE TITLE
Support of normalized IPv6 Addresses on requests

### ISSUE THREAD

**Issue by Vogel612** [perwendel/spark#261]
Currently when requesting a route from my webbrowser and logging `request.ip()` I get following String:

     "0:0:0:0:0:0:0:1"

This is not conform to [RFC-5952 (especially Section 4)](http://tools.ietf.org/html/rfc5952#section-4)

> 4.2.  "::" Usage

>4.2.1.  Shorten as Much as Possible

 >  The use of the symbol "::" MUST be used to its maximum capability.
   For example, 2001:db8:0:0:0:0:2:1 must be shortened to 2001:db8::2:1.
   Likewise, 2001:db8::0:1 is not acceptable, because the symbol "::"
   could have been used to produce a shorter representation 2001:db8::1.

Instead of the extended form, the IPv6 Address should be provided in it's shortened ("human readable") form:

    "::1"

Please represent IP addresses in the standardized format.

**Comment by tipsy** [comment]
I think this should be taken care of on the user end.
