### ISSUE TITLE
Exception in halt() when spark is deployed in tomcat

### ISSUE THREAD

**Issue by debarshri** [perwendel/spark#264]
I have following error when I use halt. I am not sure if it is relevant or may be something is wrong with my configuration.

07-Apr-2015 16:41:51.399 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter SparkFilter
 spark.HaltException
	at spark.Spark.halt(Spark.java:841)

**Comment by Serranya** [comment]
If you take a look at

https://github.com/perwendel/spark/blob/1ecd428c8e2e5b0d1b8f221e9bf9e82429bd73bb/src/main/java/spark/Spark.java#L806-L808

Its how `halt()` is implemented

**Comment by perwendel** [comment]
@Serranya +1
Not an issue.
