### ISSUE TITLE
Creating two instances of SparkServer at the same time. 

### ISSUE THREAD

**Issue by StefanLiebenberg** [perwendel/spark#281]
I want to create two separate instance of a SparkServer, each running on different ports, with different routes and exception handling. 

If I igore the Spark and SparkBase classes, I can get very close to this by replicating what they do internally, but there are still two issues making this difficult. One is that JettyHander is a private class and I cannot instantiate it directly and the other is that MatcherFilter uses a hardcoded singleton instance of ExceptionMapper instead of taking an exception mapper as constructor argument.  

```java
...
} catch (Exception e) {
 ExceptionHandlerImpl handler = ExceptionMapper.getInstance().getHandler(e);
 if (handler != null) {
...
```

I've managed to get past the JettyHandler issue by copy-pasting the private class into my code (but this is messy) but I see no quick and easy way of getting past the exception handling problem.

**Comment by eamonnfaherty-productmadness** [comment]
+1

**Comment by tipsy** [comment]
Being worked on.

**Comment by tipsy** [comment]
#499 <-
