### ISSUE TITLE
Recent version of Jetty 

### ISSUE THREAD

**Issue by jhernandezgt** [perwendel/spark#287]
Any plans of support recent version of jetty like 9.2.7 and the javax.servlet api v3 ?

**Comment by gencube** [comment]
Or even Better:
 opening up jetty replacement with other custom server: 
https://github.com/perwendel/spark/issues/288
Like:
public class MyNetworkServer implements NetworkServer {
}

...
// just like in port and before port(8080)
server(new MyNetworkServer());

**Comment by r1j0** [comment]
+1

**Comment by at15** [comment]
https://github.com/perwendel/spark/pull/301 this pr updates jetty version to 9.2.11.v20150529

**Comment by arinconstrio** [comment]
I have <jetty.version>9.3.2.v20150730</jetty.version> on production and it seems  work fine

**Comment by tipsy** [comment]
Should be fixed now.
