### ISSUE TITLE
Please consider opening up jetty replacement with other custom server:

### ISSUE THREAD

**Issue by gencube** [perwendel/spark#288]
HI,

``` java
public class MyNetworkServer implements NetworkServer {
}

...
// just like in port and before port(8080)
server(new MyNetworkServer());
```

That way, we can write a hook to replace jetty with an even better server or Custom server like Netty or Undertow.

**Comment by gencube** [comment]
This is Related to this issue:
https://github.com/perwendel/spark/issues/289

**Comment by kliakos** [comment]
+1 for undertow

**Comment by gencube** [comment]
That is what I am thinking about.

**Comment by jacek99** [comment]
Personally, I would really prefer that Spark gets split into 2 totally separate project: a REST router with no server dependencies at all AND then a separate all-in-one combo with an embedded server.

If we have the first part (i.e. standalone REST router) then we could embed it in our existing Dropwizard services and get rid of Jersey

**Comment by gencube** [comment]
Personally, I would really prefer that Spark gets split into 2 totally separate project: a REST router with no server dependencies at all AND then a separate all-in-one combo with an embedded server. << Hear Hear!

**Comment by jhernandezgt** [comment]
+1 for split

**Comment by rygel** [comment]
+1 for split

**Comment by r1j0** [comment]
+1

**Comment by beihaifeiwu** [comment]
+1

**Comment by tipsy** [comment]
Considering it. We already have some other issues and PRs for this, so closing this one.
