### ISSUE TITLE
Rename the project to avoid confusion with Apache Spark

### ISSUE THREAD

**Issue by orionll** [perwendel/spark#299]
The project has the same name as a popular data analysis framework Apache Spark. This is confusing.

**Comment by jbgi** [comment]
Or sue Apache Spark for trademark infringement! ;)

**Comment by hleb-kastseika** [comment]
jbgi, great idea.

PS. Actually a lot of questions on Stackoverflow related to Apache Spark are additionally marked with "spark-java" tag, and vice versa.

**Comment by ribomation** [comment]
Good idea. It's kinda annoying googling for spark topics, but get flooded with Apache ditto.

**Comment by Tradunsky** [comment]
+1

**Comment by arinconstrio** [comment]
+1

**Comment by pmanvi** [comment]
+1
suggestions with alternative names?
webspark
saral (means simple in sanskrit language) or saralweb

**Comment by Ariel-Isaacm** [comment]
Since the icon of the page is a comet what about Comet or jComet or webComet

**Comment by hoangtranwork** [comment]
How about Jinatra?

**Comment by tipsy** [comment]
We're working on it, but it's very hard :)
