### ISSUE TITLE
How can I pass urls contaning slashes(/) in my route?

### ISSUE THREAD

**Issue by ahmedmohiduet** [perwendel/spark#304]
I am trying to pass urls to my route. But it is always treating my url parameter as a whole.

		get("/:url", (request, response) -> {
			String url = request.params(":url");
			url=encodeUrl(url);
			String html = "You requested : " + url;
			return html;
		});

When I try: http://localhost:4567/http://www.facebook.com/somepath/somepage.php

Spark is saying : [qtp12207265-19] INFO spark.webserver.MatcherFilter - The requested route [/http://www.facebook.com/somepath/somepage.php] has not been mapped in Spark

My encoding function:
public static synchronized String encodeUrl(String urlStr) throws URISyntaxException, MalformedURLException {
		URL url = new URL(urlStr);
		URI uri = new URI(url.getProtocol(), url.getUserInfo(), url.getHost(), url.getPort(), url.getPath(), url.getQuery(), url.getRef());
		return uri.toASCIIString();
	}

Please help.

**Comment by chillenious** [comment]
Use splats (search for 'splat' in http://sparkjava.com/documentation.html)

**Comment by ahmedmohiduet** [comment]
That was easy :)

**Comment by ahmedmohiduet** [comment]
Hi chillenious,

I tried to pass this url : https://finance.yahoo.com/q/ks?s=VNJTX+Key+Statistics
using splats. Here is my code
get("/*", (request, response) -> {
			String url = request.splat()[0];
			LOG.log(Level.INFO, "Requested url : " + url);
			//...
			return html;
		});

But my log is saying that:
INFO: Requested url : https:/finance.yahoo.com/q/ks
It's removing my query string params.But I need evything in the url intact.
Do you have any ideas how can I solve this?

**Comment by chillenious** [comment]
From the top of my head... the underlying servlet API already breaks that
up. If you need the full url, you'll probably have to recreate it from the
components (url, parameters, ...).

**Comment by ahmedmohiduet** [comment]
Can you elaborate a bit more?

**Comment by amarseillan** [comment]
Hi, the case is pretty strange, usually you pass that as a parameter encoded in the query string, but you can accomplish it this way:

```java
Spark.get("/*", (req, res) -> {
    return req.raw().getRequestURL().toString() + "?" + req.raw().getQueryString();
});
```

**Comment by ahmedmohiduet** [comment]
Thank you :)
