### ISSUE TITLE
Jetty server can silently fail to serve requests when maxThreads is below 8

### ISSUE THREAD

**Issue by blandflakes** [perwendel/spark#306]
# Description
We recently upgraded to Spark2.2 in preparation for multithreading our service.

However, we couldn't get any response from our routes whenever we had threadPool set to a value below 8 (actually, on my machine, it worked at 7).

I suspect this is due to the Jetty server throwing an exception, as it does some checks to make sure the threadpool is large enough:
https://github.com/eclipse/jetty.project/blob/master/jetty-server/src/main/java/org/eclipse/jetty/server/Server.java#L356

However, logfiles show no errors.

# Test Case

## Code
Using the sample HelloWorld:

    import static spark.Spark.*;

    public class HelloWorld {
      public static void main(String[] args) {
        threadPool(2);
        get("/hello", (req, res) -> "Hello World");
      }
    }

# Observed Behavior:

Any requests to the route hello hang, and eventually timeout.

Logs:

>lasting-damage:test-spark blandflakes$ java -cp "./lib/*:." HelloWorld
>[Thread-0] INFO spark.webserver.SparkServer - == Spark has ignited ...
>[Thread-0] INFO spark.webserver.SparkServer - >> Listening on 0.0.0.0:4567
>[Thread-0] INFO org.eclipse.jetty.server.Server - jetty-9.0.2.v20130417
>[Thread-0] INFO org.eclipse.jetty.server.ServerConnector - Started >ServerConnector@65700916{HTTP/1.1}{0.0.0.0:4567}

# Expected Behavior

Requests to be served immediately. Since this may be a misconfiguration on our part, we'd hopefully see:

* A log message about why Jetty is or isn't starting up (if that is indeed the cause)
* An exception or warning about us setting the thread pool size too small (which does at least seem to be the high-level case)

**Comment by ShibaBandit** [comment]
I also ran into this, was a bit confusing.

**Comment by joakime** [comment]
Having maximum threads that low is generally a bad idea.  This is a web server, its designed to handle many requests.  

A single typical webpage can result in 20+ requests for resources on the server, from a single browser or client.  A thread limit at 8 would leave you nearly nothing left to process requests (after the thread count is used up by the acceptors and selectors)

Acceptors and Selector counts are based on a number of physical characteristics of the machine you are running on.   (eg: number of cpu cores, number of network interfaces, etc)

Setting artificially low thread count limits without also tweaking all of the hardware specific counts as well is a recipe for problems.

The Jetty typical low-resource (small machines, think in terms of 1 shared cpu core, sub 200MB memory limit, such as raspberry pi, android, and other embedded systems) thread pool is at a maximum of 200 threads. 

A high load API server can be in the thousands of threads.

A high load HTML server can be in tens of thousands of threads arena.

**Comment by blandflakes** [comment]
We're totally ok with setting a higher number of threads (I think the Jetty server defaults to 254 if you don't use threadPool() within Spark).

However, Jetty makes some effort to detect a thread pool that's too small and throws an exception on start, but that exception isn't being thrown here. Silent and non-working deadlock/starvation prevention can be frustrating.

**Comment by tipsy** [comment]
In 2.3 the supplied sample code crashes with 

    java.lang.IllegalStateException: Insufficient threads: max=2 < needed(acceptors=1 + selectors=2 + request=1)

**Comment by kodonnell** [comment]
Has this issue reappeared with Spark 2.5? When I set `threadPool(1)`, it runs through, and after a few seconds, the app simply finishes (cleanly, as far as I can tell).

For context, I explicitly want a single thread as I've got a 4G object which currently seems to be being duplicated (so two threads?). With `threadPool(1)`, memory usage stays around 4G (as expected) - until it dies as above - but without it memory usage is 8G. I'm happy with a single thread as this app is not a production one, and has very few consumers.

**Comment by kodonnell** [comment]
Update - OK, it randomly did throw the above error once. I'm not sure if it's not being logged due to sparkjava/jetty, or the fact I'm running in Eclipse on windows.

**Comment by joakime** [comment]
Starting in Jetty 9.3.14+ there is a test of threads in the Server startup.

See: https://github.com/eclipse/jetty.project/blob/jetty-9.3.14.v20161028/jetty-server/src/main/java/org/eclipse/jetty/server/Server.java#L383-L384

**Comment by kodonnell** [comment]
So why isn't the error reproducible - for me it only appears one in ten times (or something like that)? Is it because I'm running in Eclipse, or on Windows?
