### ISSUE TITLE
Static files getting locked on windows

### ISSUE THREAD

**Issue by 0419** [perwendel/spark#307]
There is a known issue in Jetty which locks static files on windows due NIO. Can you please follow the guidelines from following link to put the workaround in Spark.

http://www.eclipse.org/jetty/documentation/current/troubleshooting-locked-files-on-windows.html

**Comment by 0419** [comment]
actually found what needs to be changed.

In class SparkServer, where you are creating instance of ResourceHandler,  calling resourceHandler.setMinMemoryMappedContentLength(0); fixes the issue. Would be nice if you can integrate this with build


```
                if (System.getProperty("os.name").startsWith("Windows"))
                    externalResourceHandler.setMinMemoryMappedContentLength(0);
```

**Comment by tipsy** [comment]
I built 2.4 and tested, this is fixed now.

**Comment by cybrown** [comment]
I have the same issue with spark version 2.5.2, I've tested on Windows 7, using IntelliJ to remove static files and many git comands.
Spark is run directly as a jar file, without any servlet container.
