### ISSUE TITLE
ResponseTransformers should be able to set the Content-Type header

### ISSUE THREAD

**Issue by micsumner** [perwendel/spark#310]
It'd be nice if my json ResponseTransformer could also set the Content-Type header anywhere it gets used. 

Right now I can either:
* Create a filter matching the same URLs as my routes that sets the header
* Set the header in every one of my handlers

The first one is the better option, but if new routes are created the pattern for the filter has to be updated.

**Comment by zeroflag** [comment]
Agree. I've already opened an issue about this moths ago: https://github.com/perwendel/spark/issues/230

**Comment by tipsy** [comment]
Duplicates #230
