### ISSUE TITLE
Remove references to org.mortbay (jetty)

### ISSUE THREAD

**Issue by joakime** [perwendel/spark#315]
References to org.mortbay are no longer relevant in Jetty 9+

When the Jetty project moved from codehaus.org to eclipse.org the namespace changed from `org.mortbay` to `org.eclipse.jetty`

See: https://github.com/perwendel/spark/blob/2.2/src/main/java/spark/webserver/SparkServer.java#L56

**Comment by tipsy** [comment]
Can't find any references, so this was done at some point.
