### ISSUE TITLE
request.body() returns an empty String when having more that one filter

### ISSUE THREAD

**Issue by orby** [perwendel/spark#317]
If you define two before filters in a Spark application that reads the `request.body()`, an empty String is returned in the second filter and in the route itself.

Application
```java
public class Application implements SparkApplication {

    @Override
    public void init() {
        before(new ReadBodyFilter1());
        before(new ReadBodyFilter2());
        post("/", (req, res) -> req.body());
    }
}
```

ReadBodyFilter1 and ReadBodyFilter2 do the same thing:
```java
public class ReadBodyFilter1 implements Filter {

    @Override
    public void handle(Request request, Response response) throws Exception {
        System.out.println("Body filter 1: " + request.body());
    }
}
```

ReadBodyFilter1 prints whatever you posted, ReadBodyFilter2 prints an empty String and the same for the route.

You can call this application using this command:
`curl -i -X POST -d "spark-bug" http://localhost:8080/spark/` (when deployed inside Tomcat)

If you comment out one of the filters, leaving you with one filter and one route, it will work as intended.

Fails in both version 2.1 and 2.2

**Comment by ghayes** [comment]
I have found a similar issue.  If you reference "request.body()" and then attempt request.queryParams("named-parameter"), it will return a null value.  It seems that any reference to request.body() wipes out the content.

**Comment by AzureusNation** [comment]
I have tested this in version 2.5 and is no longer giving the output of null, therefore I can safely say that this is fixed and giving the correct output.

**Comment by tipsy** [comment]
Thanks!
