### ISSUE TITLE
Redirect without Connection: close

### ISSUE THREAD

**Issue by angryziber** [perwendel/spark#321]
Spark's response.redirect() sends a Connection: close header. Why?

The problem with that (besides breaking http keep alive) is that at least Chrome does a redirect too early when it encouters Connection: close, meaning that the redirected request comes in before previous request's after() handlers have completed. This poses problems for post-and-redirect pattern, because the redirect may come before the DB commit of the post request, resulting in a 404 response.

I suggest removing Connection: close from redirect method.

**Comment by tipsy** [comment]
Not sure if fixed. Closing this because we need to clean up. @angryziber please create a new issue if this is still a problem.

**Comment by AN3Orik** [comment]
Spark still closing connect when redirect.
