### ISSUE TITLE
response.redirect() should have a return value

### ISSUE THREAD

**Issue by angryziber** [perwendel/spark#322]
Currently, response.redirect() is not very convenient especially for REST APIs, as it is a void method and you cannot use it with a return statement.

E.g. you cannot write like this:

``` java
get("/something", (req, res) -> res.redirect("/somewhere-else"));
```

Instead, you need this:

``` java
get("/something", (req, res) -> { res.redirect("/somewhere-else"); return null;});
```

Which seems a bit awkward.

Also, you cannot do this:

``` java
get("/something", (req, res) -> {
  if (something is wrong) return res.redirect("/somewhere-else"));
  // do the stuff
});
```

I propose response.redirect() to return null by default so that you can use it with return statement or shorter lambdas.

**Comment by angryziber** [comment]
Are you interested in a pull-request?

**Comment by ilja903** [comment]
+1

**Comment by tipsy** [comment]
@angryziber Sorry for the late reply. Unfortunately we've been neglecting the issue list a bit, but I think we are very interested in a PR for this :)

**Comment by tipsy** [comment]
We added a redirect API, will add return values for redirects in v3.
