### ISSUE TITLE
Need a finally() or around() filter to do proper transactions

### ISSUE THREAD

**Issue by angryziber** [perwendel/spark#324]
Currently it is not possible to do a reliable transaction filter with Spark.

The problem:
after() runs only on successful requests
exception() runs only the filter with matching exception, i.e. it is not possible to register another 'global' exception handler that would run on any error

Some filters need to always run after the original route handler, no matter was it successful or not. This is needed for cleanup-type tasks, e.g. close a transaction, or logging of execution times, etc.

It would be nice to have a Spark.finally() or similar that would ensure that this filter will be run anyway, after both successful and failing requests.

Another option would be to add a Spark.around() filter that will work similarly to java.servlet.Filter in wrapping and delegating the original call, e.g.

``` java
Spark.around((req, res, route) -> {
  try {
    startSomething();
    return route.handle(req, res);
  } finally {
    stopSomething();
  }
});
```

**Comment by angryziber** [comment]
Would you be interested in a pull-request?

**Comment by angryziber** [comment]
There is actually a similar pull-request: https://github.com/perwendel/spark/pull/217
I can help bring it up-to-date if needed

**Comment by AthenaStudies** [comment]
I agree with this issue.

**Comment by anderssv** [comment]
+1 

I need the around filter to time all requests.

**Comment by MouettE-SC** [comment]
PR has been merged, this issues can be closed now.
