### ISSUE TITLE
Can spark hot deploy?

### ISSUE THREAD

**Issue by qwIvan** [perwendel/spark#326]
Can it auto recompile and hot reload class?

**Comment by magicgoose** [comment]
I think this is beyond its responsibilities,
but I sometimes reloaded code while debugging and it ran as expected

**Comment by andreldm** [comment]
Yeah, it seems to be Jetty's job to auto reload the app.
I wonder if tweaking SparkServer.java with something like what is explained [here](http://stackoverflow.com/q/20964126) or [here](http://stackoverflow.com/a/14368310/129822) would work.
Maybe using jetty-maven-plugin?

**Comment by tipsy** [comment]
Not currently.

**Comment by bioform** [comment]
+1

**Comment by jiacai2050** [comment]
+1

This feature is really usefully in development.

**Comment by serjN** [comment]
+1

**Comment by ruurd** [comment]
Would that be a good thing if the spark based product is used in a production environment? Anyway - as long as it is possible to reconfigure the spark server the creation of the listener and the reaction to the event can be user code, amirite?
It IS a nice addition though....

**Comment by jschwartz73** [comment]
+1

**Comment by fractalzombie** [comment]
+1

**Comment by cepix** [comment]
+1 for this feature. Why the issue was closed anyway????

**Comment by tipsy** [comment]
I closed it because it was a question, and I answered it. Even if it was a feature request, it's not trivial to implement, so we're not planning on introducing it.
