### ISSUE TITLE
Ambiguous route matching - some route entries are not reachable.

### ISSUE THREAD

**Issue by haridas** [perwendel/spark#330]
The sparkjava's default route matcher is failing to pick the correct routes,  if it is defined as follows and in that order,

```java
get("/v2/pet/:petId", (request, response) -> "Route 1");
get("/v2/pet/findByStatus", (request, response) -> "Route2");
```

The second route is not reachable with this setup, even though the request path is exact `/v2/pet/findByStatus`.

**Comment by zeroflag** [comment]
What if you change the order of the routes?

**Comment by tipsy** [comment]
I think this is common/expected behavior for route-matching. How else is it supposed to work?
If you do findByStatus/:status, it works, right?

**Comment by haridas** [comment]
@zeroflag - If we change the order it work fine. 

@tipsy - `/v2/pet/findByStatus/:status` working correctly. I think I missed this point, the linear search based on the registering order of the route.

I agree that this is the expected behavior.

I'm closing this issue. Thank you.
