### ISSUE TITLE
Remove Server:Jetty header

### ISSUE THREAD

**Issue by magicgoose** [perwendel/spark#331]
Jetty by default puts additional header in HTTP responses, which reveals the server name ("Jetty" and its version). With current design, it's hard to get rid of it, but Jetty itself does allow disabling this behavior. It would be good to implement it in the Spark API.

This would save a bit of bandwidth and also, more importantly, reduce hacking risk because attacker will not know what's running on the server.

**Comment by ribomation** [comment]
+1

**Comment by spirosoik** [comment]
+1

**Comment by perwendel** [comment]
A workaround is setting the header e.g. in an after filter `response.header("Server", "something")`

**Comment by magicgoose** [comment]
I would prefer to remove it at all, instead of changing.

**Comment by yeroc-sebrof** [comment]
If this is set to a null value instead of `some-value` does it still show up?

**Comment by magicgoose** [comment]
sorry I have no idea, it has been almost 3 years, I am doing completely different things and have no time to test this

**Comment by HinduDharma** [comment]
> If this is set to a null value instead of `some-value` does it still show up?

Setting null or empty String simply uses the default Jetty server String. 

Set it to something interesting like FBI or  CIA :-)

**Comment by robax** [comment]
Can we re-open this? I'd still find this helpful.
