### ISSUE TITLE
Allow `null`/empty response body

### ISSUE THREAD

**Issue by opsonsy** [perwendel/spark#335]
For example:

``` groovy
post("/accounts", { req, res -> res.status(201) })
```

Currently this fails with as a 404.
`INFO spark.webserver.MatcherFilter - The requested route [/accounts] has not been mapped in Spark`

In MatcherFilter.java:227, `bodyContent == null` is not enough to indicate the request hasn't been consumed.

```
        boolean consumed = bodyContent != null;

        if (!consumed && hasOtherHandlers) {
            throw new NotConsumedException();
        }

        if (!consumed && !isServletContext) {
            LOG.info("The requested route [" + uri + "] has not been mapped in Spark");
            httpResponse.setStatus(HttpServletResponse.SC_NOT_FOUND);
            bodyContent = String.format(NOT_FOUND);
            consumed = true;
        }
```

**Comment by Tradunsky** [comment]
The pull request:
https://github.com/perwendel/spark/pull/352
should fix the issue

**Comment by tipsy** [comment]
I've changed my mind here, this actually makes sense. If the route is null, nothing has been mapped, so 404 is appropriate.
