### ISSUE TITLE
Path is not matched if path param contains slash

### ISSUE THREAD

**Issue by kliakos** [perwendel/spark#343]
Take the following example:

``` java
        Spark.get("/orders/:order_id", (request, response) -> {
            return request.params("order_id");
        });
```

The path /orders/ABC1 is matched, the path /orders/ABC%2F1 not. Major problem. Wildcard parameters instead work fine though.

**Comment by perwendel** [comment]
@kliakos 
It seems like Jetty allows encoded slashes. However Apache does not by default and other web server might not (https://stackoverflow.com/questions/3235219/urlencoded-forward-slash-is-breaking-url). I'm not sure what is best practice. May I ask why your URL contains slashes?

**Comment by kliakos** [comment]
Hm, I wasn't aware this is a general issue with web servers. But nginx which I use has no problem.

Regarding why I need them, I actually have a REST api with order ids that contain forward slashes.
