### ISSUE TITLE
Websocket: Requested route has not been mapped in Spark

### ISSUE THREAD

**Issue by vemacs** [perwendel/spark#345]
In the same class I map my get()s and so on, I map:

        webSocket("/testsock", PingWebSocket.class);
        // a bunch of get()s
        init();

I am using this implementation: https://github.com/perwendel/spark/blob/master/src/test/java/spark/examples/websocket/PingWebSocket.java
Now, when I do the following on the client (JS):

    new WebSocket("ws://127.0.0.1:4567/testsock");

I get this on the server, and the client fails:

    [qtp362039908-13] INFO spark.webserver.MatcherFilter - The requested route [/testsock] has not been mapped in Spark

Considering I'm literally following the example, and my gets are being mapped fine, I'm pretty confused as to what's going on. I had this exception if I ran webSocket() after the get()s, but I fixed it by moving it before.

````
Exception in thread "Thread-0" java.lang.IllegalStateException: This must be done before route mapping has begun
        at spark.SparkBase.throwBeforeRouteMappingException(SparkBase.java:302)
        at spark.SparkBase.webSocket(SparkBase.java:263)
        at me.vemacs.WebThread.run(WebThread.java:84)
        at java.lang.Thread.run(Thread.java:745)
````

I fixed this by moving it after, but Spark still claims that the route is not mapped. Even when I comment out the get()s, the websocket still doesn't work.

**Comment by vemacs** [comment]
In fact, the provided example doesn't work:

```java
public class WebSocketTest {
    public static void main(String[] args) {
        System.out.println("starting websocket tester");
        webSocket("/ping", EchoWebSocket.class);
        init();
    }
}
```

**Comment by vemacs** [comment]
I added some debug info in where the route mappings were being registered for WebSocket:

https://github.com/perwendel/spark/blob/master/src/main/java/spark/webserver/SparkServer.java#L137

It looks like my WebSocket is being registered, as my debug statement comes in there. SparkJava is not handling the handshake properly.

**Comment by vemacs** [comment]
It's not just me: https://twitter.com/perwendel/status/631488674207780864

**Comment by nacx** [comment]
Strange. There is already a [test that verifies it works](https://github.com/perwendel/spark/blob/master/src/test/java/spark/GenericIntegrationTest.java#L409-L428), and I'm using it without issues.

I've been trying to reproduce and I've confirmed the examples don't work. It appears that the WebSocket mapping *only* works if a static route has been configured. If you add this dummy line to the example *before* the websocket mapping it should work:

```java
staticFileLocation("/foo");
```

I have a limited knowledge of Jetty, but I'll investigate why this happens and how to properly add the websocket handler to the list of handlers. @joakime, do you have  any clue about the right way to configure the websocket handlers?

**Comment by vemacs** [comment]
I can confirm that the workaround works. If you can't get an actual fix, maybe just call that in webSocket()?

**Comment by joakime** [comment]
@nacx the implementation you are using is now based on WebSocketUpgradeFilter.

Since it's a filter, it needs a servlet (of any kind) to hit (at an overlapping url-pattern), before the filter becomes valid.
Consider having a servlet that just returns 404 (Default404Servlet) if there is only websocket endpoints declared, but no servlets.  

When you add a staticFileLocation() you are likely ending up with a DefaultServlet mapped to a url-pattern that is also caught by the WebSocketUpgradeFilter.

**Comment by perwendel** [comment]
Fixed!

**Comment by joakime** [comment]
In your terminology, what happens if you have no get/post mappings (and no websockets declared).
Do you have a custom servlet that reports something useful for the end-user? 

    Hi, spark here, you have no mappings declared!
    Go declare some.

I would bet that the problem here is identical to if you did this ...

      public static void main()
      {
          before("/hi/*", new MyFilter());
      }

**Comment by perwendel** [comment]
@nacx @vemacs @joakime 
Pls verify that it works with the fix!

**Comment by perwendel** [comment]
As you can see in the code it had nothing to do with what happens in staticFileLocation.  We just missed to inform the MatcherFilter to look for more handlers.

**Comment by pufferbatterie** [comment]
I also detected that problem in combination with jetty-9.4 packages.
My working configuration now is spark 2.5.4 and jetty-9.3.6
