### ISSUE TITLE
Cache-control for static files

### ISSUE THREAD

**Issue by tchoulihan** [perwendel/spark#357]
I'd like to set the cache control on external static files(which contains some .css and .html files), so that my web client's browsers don't have to fully reload the page every time.

How do I do this?

edit: Or any response header for the external static files for that matter.

Currently, when looking at the headers with my browser, it looks like the current cache-control header is: `"max-age=0"`

**Comment by tchoulihan** [comment]
I'd like to keep this issue open, because client-caching static files with a last-modified when spark was started seems like a no-brainer, but I've developed a workaround for serving up folders:
**Make sure this is the last endpoint referenced**
```java
		get("/*", (req, res) -> {
			Tools.allowAllHeaders(req, res);
			Tools.set15MinuteCache(req, res);
			
			String pageName = req.splat()[0];
			
			String webHomePath = DataSources.WEB_HOME() + "/" + pageName;
			
			Tools.setContentTypeFromFileName(pageName, res);
			
			return Tools.writeFileToResponse(webHomePath, res);
			
		});
```

**Comment by tipsy** [comment]
Can't you just use an after-filter?

    after((request, response) -> {
        response.header("Cache-Control", "max-age=2592000");
    });

**Comment by tchoulihan** [comment]
I don't think after/before works for static files, but someone could correct me.

**Comment by tipsy** [comment]
@tchoulihan Sorry, you are correct. You really shouldn't have to do this manually though.

**Comment by tom-smalls** [comment]
The introduction of cache-control for static files would be great. Has this been prioritised?

**Comment by christopheblin** [comment]
Hi,

I'd like to know if any progress has been made on this subject ? 
To me, it also seems like a no brainer thing "a priori" but given the amount of effort needed this is not :) 

@tchoulihan could please post your Tools class somewhere so that I can reuse your workaround ?

**Comment by tipsy** [comment]
This was introduced in 2.5 :)
```java
staticFiles.expireTime(600);
//or
staticFiles.header("Some header key", "Some header value");
```

**Comment by tchoulihan** [comment]
Thanks!

**Comment by chibongho** [comment]
I want to add a "Last-Modified" header to static resources (which, if I understand correctly, offers a different type of caching than "Expires" or "Cache-Control": https://stackoverflow.com/a/22188521)

However, `staticFiles.header(key, value)` still seems inadequate to me, as I have to somehow get a reference to the File being served to determine the last modified date. 

I see that the `AbstractFileResolvingResource` class, used by the static file loader, already has a `lastModified()` function implemented, but the function is not used for much right now. In particular, it would be good if I can make `StaticFilesConfiguration.consumeWithFileResourceHandlers()` inject the "Last-Modified" header while it has a reference to the `AbstractFileResolvingResource`.

Am I missing something?
