### ISSUE TITLE
req.params() best practice, colon or no colon?

### ISSUE THREAD

**Issue by timmattison** [perwendel/spark#361]
In the the [README](https://github.com/perwendel/spark/blob/master/README.md#examples) request.params() is used in two different ways.  When referencing the `:name` variable it shows this:

```
request.params(":name")
```

When referencing the `:section` variable it shows this:

```
request.params("section")
```

Then in the [request documentation](http://sparkjava.com/documentation.html#request) it uses the syntax without the colon like this:

```
request.params("foo");
```

What is the best practice when referencing parameters?  Should you use a colon or leave it out?

**Comment by Ariel-Isaacm** [comment]
Well i reviewed the code, and the params method in the spark.Request.java does this exactly 
```
public String params(String param) {
        if (param == null) {
            return null;
        }

        if (param.startsWith(":")) {
            return params.get(param.toLowerCase()); // NOSONAR
        } else {
            return params.get(":" + param.toLowerCase()); // NOSONAR
        }
    }
```

So, i think it's better practice to add the " : " to avoid the concat and creating a new String
