### ISSUE TITLE
isAsyncSupported returns true but async code fails

### ISSUE THREAD

**Issue by timmattison** [perwendel/spark#362]
I haven't seen any examples of using `AsyncContext` with Spark.  I decided to put together a simple route to test it but it isn't working despite `request.raw().isAsyncSupported()` returning `true`.

Example:

```
        get("/test", (request, response) -> {
            HttpServletRequest httpServletRequest = request.raw();
            boolean isAsyncSupported = httpServletRequest.isAsyncSupported();
            System.out.println("Is async supported? " + (isAsyncSupported ? "Yes" : "No"));
            AsyncContext asyncContext = httpServletRequest.startAsync();

            asyncContext.start(() -> {
                response.type("text/plain");
                response.body("Async worked!");
                asyncContext.complete();
            });

            return "";
        });
```

When hitting this test URL I see this in the console:

```
Is async supported? Yes
[qtp902091968-26] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - 
java.lang.NullPointerException
    at org.eclipse.jetty.server.AsyncContextState$2.run(AsyncContextState.java:168)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
[qtp902091968-26] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@252330a9 in qtp902091968{STARTED,8<=8<=200,i=2,q=0}
```

And my curl client hangs.  If I replace `return "";` with `return "SOME STRING";`, hit the URL, see the exceptions in the console, and then kill the application curl will show me the "SOME STRING" text because the connection closes but reports this in my Terminal:

```
curl: (18) transfer closed with outstanding read data remaining
```

Is there a way to use asyncContext with Spark?  If so, can you link to an example?  If not, should I submit a PR for making `isAsyncSupported` return false?  I haven't gotten that deep in the code so I don't know if that's easy but I'd be willing to try to make it consistent.

**Comment by code-guru** [comment]
Vote up for async connection handling in Spark :+1:

**Comment by luolong** [comment]
Me too :+1:

**Comment by timmattison** [comment]
I'd love to help to get this going but the project feels a bit lifeless.  Is it dying or are the developers just busy working on other parts?  If it's the latter then maybe I'll revisit this and see if I can help.

**Comment by tipsy** [comment]
Definitely not dying @timmattison, but we currently only have one maintainer (Per) who is working full-time, and (somewhat selfishly) has a family too. Unfortunately he hasn't got a ton of time for Spark at the moment, but this will hopefully change next year.

**Comment by timmattison** [comment]
Understood. Glad to hear it is still alive!



—

**Comment by tipsy** [comment]
This is duplicated by two other issues with more comments.
