### ISSUE TITLE
Route groups

### ISSUE THREAD

**Issue by OpsRJ** [perwendel/spark#363]
I would like a feature to help organize routes into logical groups. This would work like this: Each group’s route pattern is prepended to the routes or groups contained within it, and any placeholder arguments in the group pattern are ultimately made available to the nested routes.

Simple case:

`group("/users/", (response, request) -> {
       put(":id", (response, request) -> {
            //some code here
       });
});`

More complicated:

`group("/users/{id:[0-9]+}", (response, request) -> {
       get("reset-password", (response, request) -> {
            //some code here
       });
});`

**Comment by scadgek** [comment]
Could you please provide some real examples, in which this functionality adds simplicity or reasonably reduces the amount of code? For the given ones you could just have `put("/users/:id", ...)` and `get("/users/{id:[0-9]+}/reset-password")`.

**Comment by OpsRJ** [comment]
I already did.

The way I suggested, this would make the code more organized readable in case or large apps.

With the groups i can organize the differents types of routes (users, cars, dogs, whatever.....) in a group. So when another dev get the code and see a group of route, he knows that group will only have routes to a specific type.

**Comment by tipsy** [comment]
@OpsRJ One year late: https://github.com/perwendel/spark/pull/707
