### ISSUE TITLE
Update documentation: add warning that it's impossible to change Jetty settings, among others "maxFormContentSize"

### ISSUE THREAD

**Issue by QMG-kazala** [perwendel/spark#364]
Since there is no option to change Jetty settings through Spark config, pls, just add relevant info to the documentation. So that others do not have to waste their time as I did. I understand this is minor issue but still. Adding warning seems to be ta fair solution, doesn't it? Thx.

Original issue:
https://github.com/perwendel/spark/issues/314 - "How to change Jetty settings through SparkJava? / Form too Large Exception / org.eclipse.jetty.server.Request.maxFormContentSize"

**Comment by Melody12ab** [comment]
get the jetty source from git and change maxFormContentSize,maxFormKey in the Rquest.java.
Then it solved

**Comment by QMG-kazala** [comment]
But you have to do it each time you want to use new version of Spark -> new version of Jetty. Nope, not good enought for us. We're already using Dropwizard. 

I created this issue because I just want docs to be updated. I want others to be warned so that everyone can make their decision if they're fine with this problem or not.

Thx anyway :)

**Comment by tipsy** [comment]
Can configure jetty now, thanks to #813

**Comment by QMG-kazala** [comment]
Awesome!!!!
BIG THX to everyone involved! :)
Cheers
