### ISSUE TITLE
Add ability to store Spark sessions into external storage (Redis or other)

### ISSUE THREAD

**Issue by vagabond9995** [perwendel/spark#366]
It would be great if Spark will have a configuration option, which allows to store sessions into external storages that may be clustreized. Basicly, I want to have an access to sessions from multiple application instances.

**Comment by CyborTronik** [comment]
I'm also looking for a way to share sessions between applications. Otherwise came senseless microservices if you have to duplicate the code.

**Comment by tipsy** [comment]
This is outside of the scope of the project.
