### ISSUE TITLE
Add new websocket method overload

### ISSUE THREAD

**Issue by soundvibe** [perwendel/spark#367]
Currently, mapping path to websocket handler is done using this static method:

```
public static void webSocket(String path, Class<?> handler) {
    getInstance().webSocket(path, handler);
}
```

It works but the downside is that WebSocketCreatorFactory is now responsible for creating handler instance and no argument constructor should be used for the handler class. 
It would great if I could set already instantiated handler, so a simple manual DI through constructor would be possible.

The new method could look something like this:

```
public static void webSocket(String path, Object handler) {
    getInstance().webSocket(path, handler);
}
```

And example code using it could be something like this:
`webSocket("/status", new StatusWebSocket(dependency1, dependency2));`

**Comment by jakaarl** [comment]
I'm reviewing different libraries and frameworks for an application utilizing WebSockets, and this is **exactly** what I found problematic with Spark, which I would otherwise love to use.

**Comment by jakaarl** [comment]
I looked into this a bit, hoping it would be trivial to do. However, it's a bit complicated: handlers are first added to a path-to-handlerclass map and only instantiated when starting JettySparkServer. The simple solution would be to instantiate eagerly to avoid dealing with both classes and object instances. I wonder if there is a valid reason for the delayed instantiation?

**Comment by tipsy** [comment]
Nice work!
