### ISSUE TITLE
the path ending with "/" proplem

### ISSUE THREAD

**Issue by hatem-badawi** [perwendel/spark#369]
when write 

```
 spark.Spark.get("/test/", (req,res)->  "hello");
 spark.Spark.get("/test/*", (req,res)->  "hello"+req.splat()[0]);
```

in that order it works fine 
but when write on that order:

```
 spark.Spark.get("/test/*", (req,res)->  "hello"+req.splat()[0]);
 spark.Spark.get("/test/", (req,res)->  "hello");
```

when call "http://localhost:4567/test/" with "/" at end as i declared it ;it return

**Comment by ErickSanVal** [comment]
That's happening because there's an out of bounds exception when calling splat(). When requesting without any parameter in the route, it'll try to look in an empty array. Also, You're missing an asterisk in the route. In order to send parameters and use splat, you should put an asterisk like this depending on the number of parameters.
 
```
spark.Spark.get("/test/*", (req,res)-> "hello"+req.splat()[0]);
```

**Comment by hatem-badawi** [comment]
ErickSanVal 
the * was not appear in the end of the link because i think editor of github dont show them any ways i edit it the * is appear ;
so you can reread it with the right format

**Comment by ErickSanVal** [comment]
Thank you @hatem-badawi, I'll look into it, and see if I can help. A workaround I found was using 
```
        spark.Spark.get("/test/:name", (request, response) -> "Selected user: " + request.params(":name"));
        spark.Spark.get("/test/", (req, res) -> "hello");
```
Instead of splat().

**Comment by hatem-badawi** [comment]
@ErickSanVal  this work arround is working fine ;then i think this may be count as a bug ..??!!

**Comment by Ariel-Isaacm** [comment]
I looked into it, when you define your endpoints, there's a class called SimpleRouteMatcher.java that adds it to a list of routes/paths and it( the list) behaves as a queue, as do the request you are trying to do, so your request's path matches the first one : "/test/*" but due it has no parameters it crashes. i'll try to find a way to order these routes

**Comment by hatem-badawi** [comment]
one more thing @Ariel-Isaacm  , you can also make the path  with "/test/" act exactly as "/test" 
this may fix the problem and also add more flexibility in the path 

     spark.Spark.get("/test/", (req, res) -> "hello");
is the same as 

     spark.Spark.get("/test", (req, res) -> "hello");

so when /test or /test/ is called it call the same method

**Comment by Ariel-Isaacm** [comment]
I looked into the issue and i found out something worth checking 
to the file SimpleRouteMatcher.java and i added this piece of code 
 // routes =routes.stream().sorted(comparing(RouteEntry::getPath)).collect(toList());
In this specific line
https://github.com/perwendel/spark/blob/master/src/main/java/spark/route/SimpleRouteMatcher.java#L183
This solves your problem but it's not a defenitive solution due some tests start to fail :/

**Comment by hatem-badawi** [comment]
private boolean matchPath(String path) { // NOSONAR
        if (!this.path.endsWith("*") && ((path.endsWith("/") && !this.path.endsWith("/")) // NOSONAR
                || (this.path.endsWith("/") && !path.endsWith("/")))) {
            // One and not both ends with slash
            return false;
        }
        if (this.path.equals(path)) {
            // Paths are the same
            return true;
        }

this checking for the slash must be alter to make the path endwith slash act like as the path that  not ending with slash
as i think

**Comment by AzureusNation** [comment]
@perwendel @tipsy Is it a case where Spark should be stripping the last '/' off of the string if there is nothing after it? Surely that would be best practice as you never see urls that end in a '/' unless it is the root.

**Comment by hatem-badawi** [comment]
it will give more flexibility to Spark users; with / or not the framework will work .... some users may see the end / as the closing of the uri

**Comment by AzureusNation** [comment]
Ok, so I think I've found the source of the issue. Only thing being is that it breaks one test. Seems to me like this method could be due a refactor to simplify and get the correct out put from it instead of adding more complexity to the current method.

This I think should be scheduled for the 3.x release but a hack could be added for 2.6 just to get us by for now.

**Comment by perwendel** [comment]
`.../foo/` and ...`/foo` are two different URLs even if they often are treated the same.
some reference:
https://cdivilly.wordpress.com/2014/03/11/why-trailing-slashes-on-uris-are-important/
