### ISSUE TITLE
iOS 9 app transport security

### ISSUE THREAD

**Issue by neilyoung** [perwendel/spark#370]
Using 1.7 and I'm ok with it. Now my iOS 9 compiled app cannot connect anymore using HTTPS, because the new iOS 9 app transport security requirements:

<snip>
These are the App Transport Security requirements:

The server must support at least Transport Layer Security (TLS) protocol version 1.2.
Connection ciphers are limited to those that provide forward secrecy (see the list of ciphers below.)
Certificates must be signed using a SHA256 or greater signature hash algorithm, with either a 2048-bit or greater RSA key or a 256-bit or greater Elliptic-Curve (ECC) key.
Invalid certificates result in a hard failure and no connection.

These are the accepted ciphers:

TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA

</snip>

Is the latest version supporting that or is there a way to make 1.7 fit for that?

**Comment by neilyoung** [comment]
Uhm.. maybe I'm on the wrong track here and this is an issue for Jetty (?)

**Comment by tipsy** [comment]
Probably jetty, yes. You can try changing the dependency? 
Since we unfortunately can't support < 2.0, I'm closing this, but please reopen if you upgrade and the issue persists.
