### ISSUE TITLE
Tests failing when run them all together

### ISSUE THREAD

**Issue by Ariel-Isaacm** [perwendel/spark#372]
The following tests somehow are failing (maybe my environment) cause if i run the separately they pass without trouble, but if i run all the test these test fail
StaticFilesTest
 -testStaticFileCssStyleCss
 -testExceptionMapping404
 -testExternalStaticFile
 -testStaticFilePagesIndexHtml
 -testStaticFilePageHtml

ServletTest
 -textExternalStaticFile
 -testStaticResource
 -testStaticWelcomeResource

The StaticFileTest's throws this exception 
         org.apache.http.NoHttpResponseException: localhost:4567 failed to respond
Meanwhile the ServletTests, the assertions fail
         
textExternalStaticFile:
           org.junit.ComparisonFailure: 
           Expected :Content of external file
           Actual   :echo: externalFileServlet.html

testStaticResource
           java.lang.AssertionError: 
           Expected :200
           Actual   :404

testStaticWelcomeResource
            java.lang.AssertionError: 
            Expected :200
            Actual   :404

As i say, if i run only these tests they seem to work fine.

**Comment by tipsy** [comment]
This has been open for a while without anyone else reporting it, so I think it was probably your environment.

**Comment by kfh** [comment]
Just observed the same problem, maybe reopen? For now i have to use Thread.sleep() (ughhh) to 
avoid it.

**Comment by jakaarl** [comment]
Anything to do with this? https://github.com/perwendel/spark/issues/400

**Comment by kfh** [comment]
That could be the case, yes. I'm just setting the port manually now to avoid any problems in the tests.
Anyway, this shouldn
