### ISSUE TITLE
Why have slf4j-simple as a dependency ?

### ISSUE THREAD

**Issue by fzakaria** [perwendel/spark#379]
Seems like anyone would want to bring their own binding.
Why does the framework force slf4j-simple ?
We always have to exclude it.

**Comment by travisspencer** [comment]
Yes, this is a bug. Excluding it is the work around, but it would be preferred to not have it coming in at all. The tests need some sort of logging binding, so it may simply be that slf4j-simple needs to have its scope set to test.

**Comment by fzakaria** [comment]
you can add slf4j-simple as a test scpoe.

**Comment by bentolor** [comment]
@fzakaria Why not prepare & test a merge request which solves your issue?

It should be that dead-simple, that the obstacles of reviewing and pressing the "Merge"-Button should be very low for the maintainer.

**Comment by fzakaria** [comment]
Please see https://github.com/perwendel/spark/pull/381

**Comment by tipsy** [comment]
Fixed in dc3a971.
