### ISSUE TITLE
Routes do not respect the order they are defined

### ISSUE THREAD

**Issue by bentolor** [perwendel/spark#380]
[The documentation](http://sparkjava.com/documentation.html#routes) states:

> Routes are matched in the order they are defined. The first route that matches the request is invoked.

Nevertheless the following code 

```
import static spark.Spark.get;

public class HelloWorldService {
  public static void main(String[] args) {
    get("/hello", (req, res) -> "Hello World");

    get("/hello/:varname", ((req, res)
      -> "Hello " + req.params("varname")));

    get("/hello", "text/html", (req, res)
            ->  "<!DOCTYPE html><html><h1>" +
            "Hello World</h1></html>");
  }
}
```

behaves as follows:

```
$  wget -qO- "http://localhost:4567/hello"
Hello World⏎
$ wget -qO- "http://localhost:4567/hello" --header "Accept: text/html"
<!DOCTYPE html><html><h1>Hello World</h1></html>⏎    
```

Following the documentation I'd expect the second request should also return the plain/text response unless the order of the `get()` is reversed.

**Comment by franklinexpress** [comment]
No issue here. you are specifically specifying to accept html in the second request. To accept just text you need to specify "text/plain" in the header.

**Comment by franklinexpress** [comment]
No issue here. you are specifically specifying to accept html in the second request. To accept just text you need to specify "text/plain" in the header.

**Comment by bentolor** [comment]
@franklinexpress I found it rather convenient to work the way it is. The javadoc doesn't state anything about defaults. Diving into the Code of `get(path, route)` reveals a `*/*` as content type which I would read as catchall.

**Comment by franklinexpress** [comment]
I see, but I thought this was an HTTP thing. Isn't the default content-type text/plain when not specified? I'm not on my laptop now but I thought it was an RFC822 thing. but don't hold me to it because I'm not sure, I just didn't think it had anything to do with the framework. Maybe you are correct though.
