### ISSUE TITLE
Response body

### ISSUE THREAD

**Issue by danieledangeli** [perwendel/spark#385]
Hi,
I was starting to use Spark Framework.
I have to say thai is well done, but I need an help.
I'm a bit confused about the Route interface:
```java
Object handle(Request var1, Response var2) throws Exception;
```
So let's consider an HelloWorldHandler:

```java
public class HelloWorldHandler implements Route
{
    public Object handle(Request request, Response response) throws Exception {       
        response.body("my body");
        return "my body"
    }
}
```

it works well, but I'm wondering about how to set the body in the response. 
Usually other languages have a "middleware style chain" where you don't have to return nothing, but just "decorate" the response (headers, body etc).

Instead here I have two way to "set the body response" (even if I have always return the body response, otherwise it will be not setted")

```java
public class HelloWorldHandler implements Route
{
    public Object handle(Request request, Response response) throws Exception {       
        response.body("my body");
        return ""
    }
}
```
In this example above, the response body it will be "".

Just to understand a bit better, why not having something like:

```java
public class HelloWorldHandler implements Route
{
    public void handle(Request request, Response response) throws Exception {       
        response.body("my body");
    }
}
```
Probably, I'm missing something?

**Comment by perwendel** [comment]
To achieve that you'd have to do:

```java
response.body("my body");
return null;

or just:

return "my body";

```
