### ISSUE TITLE
Using a <form action="/"> Redirects but returns a 404 error but when accessing that webpage normally it works

### ISSUE THREAD

**Issue by VortexCoder** [perwendel/spark#387]
Using a form action="/" Redirects but returns a 404 error but when accessing that webpage normally it works

**Comment by VortexCoder** [comment]
I forgot to mention, I'm using the freemarker template also.

**Comment by tipsy** [comment]
Do you have a post route mapped to "/" ?

    post("/", (request, response) -> {
        // do something
    });
