### ISSUE TITLE
Server shuts down when given port is in use

### ISSUE THREAD

**Issue by Prototype1** [perwendel/spark#388]
Hello, 

we have a little problem with this code (JettySparkServer in method ignite()): 

} catch (Exception e) {
            logger.error("ignite failed", e);
            System.exit(100); // NOSONAR
}

System.exit is actually pretty bad here. We have no chance in stopping the server from shutting down. 

In our application we start a webserver and some other server. It is perfectly fine for us when the given port of the webserver is already in use but System.exit shuts down the whole jvm and thus our other server also.

Would be nice when there was some workaround (like an exception handler which is configurable outside of spark)

Thanks in advance! 

Cheers,

**Comment by arunwizz** [comment]
Even I am facing exactly the same problem, in our application its perfectly fine if Spark doesn't ignite due to port conflict. But the mail application should continue running. However due to System.exit(); the primary application is killed. IMHO System.exit should be optional, at least in embedded mode.

**Comment by Prototype1** [comment]
Hi, 

Its pretty easy to patch the class file to remove the problematic code.
What I did: 
Copy the source code of the class JettySparkServer to a new File. Remove System.exit and compile it. Open Spark jar file and replace JettySparkServer class with your custom class.

It's an ugly workaround but works for us. The change was quite simply and didnt take me more than 15min.

**Comment by arunwizz** [comment]
Thanks @Prototype1, I too thought of changing the source and recompile for our internal purpose. But was wondering if this behavior can be fixed in upstream too?

**Comment by Prototype1** [comment]
My idea (sadly no time to implement yet) to have a default handler which exits the VM and is mutable. The handler is in fact a simply Consumer<Exception>

**Comment by arunwizz** [comment]
That's a good idea, so you mean users can supply custom handler/consumer which can choose not to exit VM in situation as ours?

**Comment by Prototype1** [comment]
Since I opened the issue the package structure changed quite a bit.

I would suggest having a `private Consumer<Exception> fatalErrorHandler = (ex) -> {
logger.error(ex); 
System.exit(100); 
} `
In Class `EmbeddedJettyServer `

The fatalErrorHandler gets called everywhere where System.exit() shows up and has a simple setter to overwrite the default behavior.

**Comment by arunwizz** [comment]
Seems perfect to me. If committer agrees we can provide PR. I can spare some time for this, if needed. :)

**Comment by Prototype1** [comment]
Well our program works with spark now and I am at vocation the next 2 weeks and wont have time to do it.

Feel free to provide a PR. :+1:  Would be cool!

**Comment by arunwizz** [comment]
Alright, I am off till this weekend. Will try to do after that.

**Comment by arunwizz** [comment]
@Prototype1 - You are right hard part is to expose the functionality to the user. I was wondering how about using some program argument or configuration to decide exit on exception vs. throwing exception to the caller?  That may avoid changing interfaces.

**Comment by Prototype1** [comment]
Hi @arunwizz 

passing a argument at start time works is however inflexible (I dont mind).

My idea is we delegate the functionality to the Service. 
So [https://github.com/perwendel/spark/blob/master/src/main/java/spark/Service.java](url)

We add a method boolean onFatalException(Consumer<> handler) and return true if the given Server (EmbeddedJettyServer in our case) supports the functionality to set a fatalExceptionHandler.

Something like this:
`boolean onFatalException(Consumer<> handler)
if(embeddedServer instance of EmbeddedJettyServer){
embeddedServer.onFatalExcpetion(handler); 
return true; 
}else{
logger.log("embeddedServer doesnt support this feature");
return false; 
}
`

 In [https://github.com/perwendel/spark/blob/master/src/main/java/spark/Spark.java](url) we simple have the same static method wich calls the service.

**Comment by arunwizz** [comment]
Hi @Prototype1 

You are right. Above approach is more flexible. I have one additional idea though, how about wrapping code inside Service.init() with try-catch block. We can define `Service.fatalErrorHandler` with default implementation. And allowing users to override Service.fatalErrorHandler with custom consumer.

This way EmbeddedServer and its underlying implementation should just throw all exception to the caller init() function of Service.java. 

So something like this in `Service.java`

 // default exception handler, same as what you suggested inside
  // EmbeddedJettyServer.java,
`private Consumer<Exception> exceptionHandler = (ex) -> {
    LOG.error(ex.getMessage());
    System.exit(100);
  };`

// we can even call this configureFatalExceptionHandling()
`public void onFatalException(Consumer<Exception> handler) {
    this.exceptionHandler = handler;
  }`

`public synchronized void init() {
    try {
     //existing code which invokes EmbeddedServer.ignite();
     //...
    } catch (Exception e) {
      exceptionHandler.accept(e);
    }
  }`



And as you suggested we can have same static function "onFatalException" in Spark.java to allow users to override the behavior.

`//we can even call this configureFatalExceptionHandling()
public static void onFatalException(Consumer<Exception> handler) {
    getInstance().onFatalException(handler);    
}
`

After this we can remove try/catch from EmbeddedJettyServer.ignite() method and may add throws Exception clause in EmbeddedServer.ignite() method. 

Does this make any sense? 

Regards,
Arun

**Comment by Prototype1** [comment]
Hi @arunwizz 
this would work too but only catches errors during server start up or?  
Cheers,

**Comment by arunwizz** [comment]
Yes @Prototype1 only during startup, I am under assumption that any exception during routing will be handled with existing exception mapping mechanism. I am not too verse with complete spark framework, so excuse me if I have missed out anything :)

Regards

**Comment by Prototype1** [comment]
Well I am not too much into spark either. But i guess your solution is simpler (didnt found any System.exit beside the start of the server, so handling ignit only is enough).

Cheers, 

Moritz

**Comment by arunwizz** [comment]
Appreciate your guidance @Prototype1 , I am not sure how this community works. I will probably incorporate this change in my fork, generally the authors/committers has to approve any change before raising PR. There are already 47 pending PRs :)

Regards
Arun

**Comment by Prototype1** [comment]
No Problem :) Always cool to help.

**Comment by tipsy** [comment]
> There are already 47 pending PRs :)

Just 37 now :smirk: 
This seems like a minor change, so please create a PR, and we'll have a look at it soon™.

**Comment by arunwizz** [comment]
Thanks @tipsy 

> Just 37 now :smirk:

That's pretty quick!! 

By the what is ™ doing after soon :smile: ?

**Comment by tipsy** [comment]
I just dismissed most of them, so don't be too impressed.
That **soon** is more of a **eventually** :smile:

**Comment by PaulBGD** [comment]
Turns out that rethinkdb already listened on the port I was using (8080) 😌 I thought I was going crazy that a random 100 exit code kept popping up.

**Comment by tipsy** [comment]
You can now override the default behavior like this:
 `initExceptionHandler((e) -> System.out.println("Uh-oh"));`
