### ISSUE TITLE
Static files are locked

### ISSUE THREAD

**Issue by deepakrm90** [perwendel/spark#393]
Static files changed are not updated to maven target directory because its static files are locked I need to restart every time changing of js files. I used this code to staticFileLocation("/public"); set static files . IDE is intelli jIDEA

**Comment by tipsy** [comment]
Is this really because of Spark? Either way, it should be enough to make your project (CTRL+F9), you shouldn't have to restart the application.

**Comment by deepakrm90** [comment]
I manually checked my maven target static  folder and tried to modify static files via notepad ,its gives error like 'File is locked' after stopping application its works fine.
I looked some already raised issues about static file locking in spark,it occurs only in windows os because of bug in  jetty server ,the same project works well in linux (ubuntu)

**Comment by tipsy** [comment]
Oh, wow. I see what you mean now. That must be extremely annoying.

**Comment by deepakrm90** [comment]
This bug already raised in #307

**Comment by tipsy** [comment]
Thanks, I'll close this one then :)
