### ISSUE TITLE
Feature request: Debug mode

### ISSUE THREAD

**Issue by tipsy** [perwendel/spark#402]
It would be nice to have a debug mode where exceptions would be displayed in the browser, with the filename, the problematic line, and maybe the stacktrace... and maybe an option to google the exception, and/or link to relevant docs?

Ideas are welcome!

I can do the HTML/JavaScript work.

**Comment by mschurr** [comment]
I actually implemented something similar to https://github.com/filp/whoops for Spark. I can see about open sourcing it if you are interested.

![image](https://cloud.githubusercontent.com/assets/3498024/12015973/7b658faa-ad0a-11e5-8d3b-cf89efb9aa12.png)

**Comment by tipsy** [comment]
Looks very nice, and pretty close to what I had in mind. Would be great if you could open source it.

**Comment by tipsy** [comment]
@mschurr any news on this?

**Comment by mschurr** [comment]
I didn't have time to package this and put it on maven central, but here is the code:
https://github.com/mschurr/spark-whoops

**Comment by tipsy** [comment]
Very nice, thanks. I'm having some issues, but we can continue the discussion in your repo :)
