### ISSUE TITLE
How to dynamically update variable even after client has recieved webpage.

### ISSUE THREAD

**Issue by VortexCoder** [perwendel/spark#409]
I have a webpage with variables connectedClients which is from some other server. I know the variable but is it possible to keep the connection established and update the client's page every time connectedClients changes in the code?

**Comment by tipsy** [comment]
You can use WebSockets and send a message to the client every time your variable changes?

**Comment by VortexCoder** [comment]
And How do I use webSockets?

**Comment by tipsy** [comment]
https://sparktutorials.github.io/2015/11/08/spark-websocket-chat.html

**Comment by VortexCoder** [comment]
Yes, I have now seen this, @tipsy 
org.eclipse.jetty.websocket.api is not an import, Any help?
