### ISSUE TITLE
Not possible to override headers

### ISSUE THREAD

**Issue by tipsy** [perwendel/spark#413]
The **header(String header, String value)** method only adds headers (contrary to what the javadoc states)

```
response.header("X-Frame-Options", "DENY");
response.header("X-Frame-Options", "SAMEORIGIN");
//X-Frame-Options is now "DENY, SAMEORIGIN"
```

I suggest setHeader and addHeader.

**Current workaround**
`response.raw().setHeader("X-Frame-Options", "SAMEORIGIN");`

**Comment by qwIvan** [comment]
Can you remove it before add?

**Comment by tipsy** [comment]
You can't remove a header. Not in Spark, and not in HttpServletResponse (the class Spark's Response wraps).

The implementation of **header(...)** should be changed from using **httpServletResponse.addHeader(...)** to using **httpServletResponse.setHeader(...)**, as adding multiple values to the same header is probably a lot less common than just setting them. If you really want to add multiple values you could always do **header("Header", header("Header") + "New value")**
