### ISSUE TITLE
Is this a router bug?

### ISSUE THREAD

**Issue by qwIvan** [perwendel/spark#414]
```java
get("/hello", (request, response) -> null);
```
```shell
curl localhost:4567/hello
```
will get
> <html><body><h2>404 Not found</h2></body></html>

and the terminal print
> The requested route [/hello] has not been mapped in Spark

**Comment by qwIvan** [comment]
https://github.com/perwendel/spark/pull/352 will fix it

**Comment by basdek** [comment]
See #489

**Comment by Tradunsky** [comment]
#405 fix the issue

**Comment by tipsy** [comment]
Covered more accurately in #489
