### ISSUE TITLE
add route without keyword "return" .

### ISSUE THREAD

**Issue by qwIvan** [perwendel/spark#416]
I am try to add a feature that allow developer can add a route without keyword "return" .
https://github.com/perwendel/spark/compare/master...qwIvan:feature_router_without_return
example code:
```java
get("/simple",(request, response) -> {
    response.body("Simple");
});
```
but these are some problem in lambda block that only contain code with throw exception, like:
```java
get("/simple",(request, response) -> {
    throw new RuntimeException();
});
```
I was get a warning message from Intellij IDEA:
> Ambiguaus method call. Both
my solution is add a condition before throw:
```java
get("/simple",(request, response) -> {
    if (true)
        throw new RuntimeException();
});
```

but it is not elegant at all.

**Comment by tipsy** [comment]
Why? Your example: 
```java
get("/simple", (request, response) -> {
    response.body("Simple");
});
```

Is a lot simpler with return:

```java
get("/simple",(request, response) -> return "Simple");
```

Think of it as ```get(input, output)```
