### ISSUE TITLE
letsencrypt support?

### ISSUE THREAD

**Issue by tchoulihan** [perwendel/spark#420]
Has anyone gotten spark working with letsencrypt?

I have an issue over there, and someone seems to have got letsencrypt working with jetty, but nothing I have is working.

https://github.com/letsencrypt/letsencrypt/issues/1701

**Comment by tchoulihan** [comment]
Here's the command, after I've generated the keystore. its giving me no errors, but my domain is still unavailable:

`Spark.secure(DataSources.KEYSTORE(), "changeit",null,"changeit");`

**Comment by tchoulihan** [comment]
Nevermind, I figured this one out. Follow the instructions in that letsencrypt issue, and also, make sure you set the `spark.setPort` to 443 .

**Comment by Gronis** [comment]
Could you link the issue on letsencrypt? I cannot find it there...

**Comment by Gronis** [comment]
Ok, found it now. This is the link in case anyone else is reading this https://github.com/letsencrypt/letsencrypt/issues/1701
