### ISSUE TITLE
Routes having issues with /

### ISSUE THREAD

**Issue by SonarBeserk** [perwendel/spark#421]
Spark Version: 2.3

``` java
        get("api/v1.0/test", (req, res) -> {
            return "String Test";
        });
```

When going to /api/v1.0/test it prints "String Test" as expected. However going to /api/v1.0/test/ causes a 404 error and a message in console.

```
spark.webserver.MatcherFilter - The requested route [/api/v1.0/test/] has not been mapped in Spark
```

**Comment by franklinexpress** [comment]
Yup, happens to me too, been wondering about that. I think it sees it as a different route.

**Comment by tipsy** [comment]
Duplicates #109
