### ISSUE TITLE
NotFoundException exists in documentation, and example/test class, but nowhere else

### ISSUE THREAD

**Issue by dhoss** [perwendel/spark#422]
Hi,

I'm new to Spark and re-acquainting myself with Java, and I've noticed the docs are a little confusing at times.  They make mention of several things that are either difficult to find documentation for, or that plain don't exist.

For example, NotFoundException is mentioned here: http://sparkjava.com/documentation.html#exception-mapping, and it exists here: https://github.com/perwendel/spark/blob/master/src/test/java/spark/examples/exception/NotFoundException.java, and in http://docs.oracle.com/javaee/7/api/javax/ws/rs/NotFoundException.html, but not in the actual framework itself.  This is really confusing for someone like myself coming and hoping to use NotFoundException in places where it would be really convenient.

Am I missing something?  If this exists, and I'm just being thick, I'd love to know so I can update my code.  I'd be more than happy to get some tutelage on this matter and submit a doc patch.

For the time being, I've yoinked the pertinent code from the test file I cited above and will be trying to make do with that.

Thanks!

**Comment by tipsy** [comment]
Thanks, I've changed it to be "YourCustomException" for clarity.
