### ISSUE TITLE
SSL / https redirect?

### ISSUE THREAD

**Issue by dessalines** [perwendel/spark#425]
Does anyone know a good way, with jetty, to basically to a redirect to the https version?

For example, You have to use `spark.setPort(..` to either 80  or 443. But I want people who accessed my old site, IE `http://mydomain.com` to be automatically redirected to the `httpS://mydomain.com` version. 

Does anyone know a good way to do this?

Thanks in advance.

**Comment by tom-smalls** [comment]
Do you mean something like this?
```java
Spark.before((req, res) -> {
            final String url = req.url();
            if (url.startsWith("http://"))
            {
                final String[] split = url.split("http://");
                res.redirect("https://" + split[1]);
            }
        });
```

**Comment by tom-smalls** [comment]
I removed my response as it only works for me as my application runs on Heroku, so my application doesn't actually deal with https itself so is able to re-route http requests to https.

It's a bit more tricky if you're using Spark.secure as it only creates a ServerConnector for SSL (from what I can tell), so http traffic never makes it to the Spark filters.

I've included my original answer just in case it is helpful to anyone else.

```java
Spark.before(((request, response) -> {
            final String url = request.url();
            if (url.startsWith("http://"))
            {
                final String[] split = url.split("http://");
                response.redirect("https://" + split[1]);
            }
        }));
```

**Comment by tchoulihan** [comment]
How would've that've handled the port issue? So heroku just let you run your webserver at port 80, even though it was SSL?

**Comment by tom-smalls** [comment]
@tchoulihan Heroku handles SSL at their load balancers (I believe). When your app "spins up" you're provided with a port via a environment variable in which you will receive traffic; it's neither 80 or 443.

**Comment by tchoulihan** [comment]
This is still unsolved for me. I found a couple of threads that can tune jetty to do this, but have no idea how to get it working for spark:

http://stackoverflow.com/questions/20611815/redirect-from-http-to-https-in-jetty
http://stackoverflow.com/questions/24991508/jetty-9-2-1-redirect-http-to-https

**Comment by tchoulihan** [comment]
Still a big issue for me, does anyone have an SSL site working?

**Comment by mschurr** [comment]
You can run a separate web server that listens on port 80 and redirects all HTTP requests to HTTPS. This may not be possible in all hosting situations, though.

**Comment by gimlet2** [comment]
#329 should help with running with http and https in same time.

**Comment by tchoulihan** [comment]
This would be hugely helpful. Right now, I've written another spark webserver whose only job is to redirect to the SSL!

**Comment by SirWellington** [comment]
This please.

**Comment by SirWellington** [comment]
For now I have setup a single server to open up a secure and a non-secure port using the `Instance` API. See my code here:

```java
 Service http = Service.ignite();
        final int port = 9100;
        
        setupPort(http, port);
        setupExceptionHandler(http);
        setupRoutes(http);
```

https://github.com/BlackWholeLabs/BlackNectar-Service/blob/c8837fc4468d32c6158c8c9b31c730ff6ea59ecd/src/main/java/tech/blackhole/blacknectar/service/Server.java

**Comment by tipsy** [comment]
Yes, instance API should take care of this.

**Comment by dessalines** [comment]
Are there any docs for instance API? I don't see any on the website.

**Comment by tipsy** [comment]
No, @perwendel doesn't want to promote it to new users. I think this is something we have to reconsider though. The instance API offers the same functionality as the static API, but on an instance (the static wrapper really just calls an instance). A basic example is available in the news-section: http://sparkjava.com/news#spark25released

**Comment by rococode** [comment]
It's been a while but consider me a vote for "put this on the docs". It could literally be a sentence or two in the documentation but it'd be nice to know it exists! I think that requiring SSL is at the very least a somewhat common use case.
