### ISSUE TITLE
Jinjava

### ISSUE THREAD

**Issue by besil** [perwendel/spark#427]
Hi,

Thank you for this great work!

Support for Jinjava as template engine would be great.
https://github.com/HubSpot/jinjava

Jinja is a very popular templating engine python/django world and, immo, more intuitive than the others.

**Comment by tchoulihan** [comment]
I don't see what this has to do with spark. Just do whatever templating you need to do, and serve up the json string. 

I use [mustache.java](https://github.com/spullara/mustache.java) myself.

**Comment by tipsy** [comment]
I made an issue in the template-engine repo.
