### ISSUE TITLE
Disable Jetty's locking of static files

### ISSUE THREAD

**Issue by sparkforreg** [perwendel/spark#432]
reproduced on windows 7.
steps:
1. start server
2. change content of static file (any html for example)
3. try to save this file. Eclipse or any ide starts to complain

Static files were configured via Spark.externalStaticFileLocation.
looks like the same issue as https://code.google.com/p/run-jetty-run/issues/detail?id=7

I tried to configure "useFileMappedBuffer=false" according to above link but I didn't find how to do it

**Comment by tipsy** [comment]
This should be fixed already. Did you try the master branch?
