### ISSUE TITLE
Support for template engines that support streaming responses

### ISSUE THREAD

**Issue by nanodeath** [perwendel/spark#443]
Presently [TemplateEngine](https://github.com/perwendel/spark/blob/c248dce38665d80981aec9bb1a9cf2f6d0333927/src/main/java/spark/TemplateEngine.java) assumes that the template engines can only return a String, but some engines (such as [Pebble](https://github.com/mbosecke/pebble/blob/afd7807965f3725bf664d7e339b5a70e632557f7/src/main/java/com/mitchellbosecke/pebble/template/PebbleTemplate.java)) support writing output directly to a Writer. Pebble also has an explicit [flush](http://www.mitchellbosecke.com/pebble/documentation/tag/flush) call that requires writing directly to the buffer (and not to a String or StringWriter) to actually do anything.

It seems like it could be a significant performance win to add this functionality.

---

Sorry for the awkward title, or if this has already been opened previously. I looked for TemplateEngine and didn't find anything.

**Comment by tipsy** [comment]
This is somewhat outside the scope of Spark. I'll close the issue, but you can create a PR if you really want this @nanodeath .
