### ISSUE TITLE
Add an "after" filter that accepts ModelAndView

### ISSUE THREAD

**Issue by nanodeath** [perwendel/spark#445]
The current `before` and `after` filter only have access to the request/response. It would be useful to have a filter that runs _after_ the route, but _before_ the `render` method, i.e. [right here](https://github.com/perwendel/spark/blob/c248dce38665d80981aec9bb1a9cf2f6d0333927/src/main/java/spark/webserver/MatcherFilter.java#L171).

---
## Background

I'm using Spark with [Pebble](http://www.mitchellbosecke.com/pebble/home) as well as [Persona](https://login.persona.org/). Persona requires that you emit the authenticated user's email address into the page as a JavaScript variable. So the question is, how do I pass the email address into every view's ModelAndView instance? I don't want to manually add this one assignment to every route; that's not sustainable. I think the answer is to create a new type of filter that runs just before the `render` method -- it's the only sane way to attach additional data to many routes.

**Comment by craigsdennis** [comment]
I've written some middleware using `Request.attributes`.  You can push stuff in there from a before method and then have access in every route.

I haven't done this but if your Model portion of the Model and the view has the same datastructure, you could create it in the before and access it in each route.

Something like this might do the trick.
```
before("/", (req, res) -> {
   Map<String, Object> model = new HashMap<>();
   model.put("email", "however@yougetthis.com");
   req.attributes("model", model);
});

get("/random", (req, res) -> {
   req.attributes("model").put("more", "things");
   return new ModelAndView(req.attributes("model"), "view.html");
}
```
