### ISSUE TITLE
A way to get the port if you specify `port(0)`

### ISSUE THREAD

**Issue by dkowis** [perwendel/spark#446]
As best as I can tell, once you do this, there's no way to get the port programmatically. I haven't found a way to get to the underlying Jetty server to get those port details, and the port parameter can only be set, never queried.

It would certainly make integration style testing a whole lot easier, and more reliable, if I could start spark on a random port, and then inspect that port for use in my integration tests.

**Comment by dkowis** [comment]
For cross linking, in case someone comes across it here, I have done dirty reflection hacks to get at this port.
http://stackoverflow.com/a/34687059/423218

I would love for there to be an API approved way to get the port for use during integration testing.

**Comment by IRus** [comment]
Related to #400
