### ISSUE TITLE
Difficulty  to read dynamic path parameters

### ISSUE THREAD

**Issue by jamsheer-thottathil** [perwendel/spark#448]
I have a end point and  tail contains with its return type's extension

Example :name/test.json

Here i can read path parameter as  follows  

```
get("/:name/test.json", (request, response) -> {
    return "Hello: " + request.params(":name");
});
```

But i am getting difficulty to read path parameters if  it is in last part of URL 

Example test/:name.json

Here i need to read  as request.params(":name")  ,Is it possible with spark .

Jersey , restlet  like frameworks are  support it by the help of {}.

**Comment by craigsdennis** [comment]
With the current implementation, this doesn't look to be possible.

The entire part of the path is stored, see the [Request code here that gets the parameters](
https://github.com/perwendel/spark/blob/master/src/main/java/spark/Request.java#L462)

Unfortunately, in your example, `request.params(":name.json")` will return the entire portion and match anything in that part of the path.

**Comment by perwendel** [comment]
I have difficulties seeing how this an actual problem. Why not just read the parameter value and parse the string to the two parts you need? E.g. with split(".") ?

**Comment by jamsheer-thottathil** [comment]
Than you all for your reply  and I am sorry ,i did not get you @perwendel 

In my example i cannot read name value as its is available in URL with .json tail.

Here 'name' is my variable name and .json came apart  of my rest standard

**Comment by tipsy** [comment]
Added to v3 roadmap

**Comment by adityakapre2009** [comment]
Is v3 released yet ?
