### ISSUE TITLE
docs request - discussion of concurrency model

### ISSUE THREAD

**Issue by the1mills** [perwendel/spark#454]
Hi there!

I have been thinking about using Spark for awhile now. I am mostly unfamiliar with Java based servers and I would like to know about the concurrency model used by Spark.

I have mostly been doing node.js lately, and Express is also similar to Sinatra, and I like it all.

Frankly, looking through the docs, I have no real idea how Spark achieves concurrency. Is is standard Java threads or is message passing like in Akka.io?

Is the concurrency mostly abstracted away in Spark, or do we need to worry about it?

Please let me know, thanks!. t might be useful to describe how this works in the docs (at least I didn't see it in the docs anywhere).

I see this about the available threadpool:

http://sparkjava.com/documentation.html#threadpool

my use case is that I want a small Java server that can run a certain type of CPU intensive job

I imagine I would like about 8 or so workers (about as many workers as there are cores) that can process the job.

Is there any example of how to create some sort of job queue with Spark, and have about 8 workers processing the job?

Is Spark a good match for this use case? thanks! :)

**Comment by tipsy** [comment]
See #208
