### ISSUE TITLE
Error while generating apidocs

### ISSUE THREAD

**Issue by bml13** [perwendel/spark#460]
Executing the task
`mvn javadoc:javadoc`
produced this error:
`Exit code: 1 - spark-2.3/src/main/java/spark/Request.java:267: error: semicolon missing`
`     * Example: query parameter 'id' from the following request URI: /hello?id=foo&id=bar`

The problem is with the ampersand character (&), it should be replaced by `&amp;`

**Comment by IRus** [comment]
Fixed.
