### ISSUE TITLE
how do i get or set context path in SparkInstance ? 

### ISSUE THREAD

**Issue by liniu** [perwendel/spark#465]
how do i get or set context path in SparkInstance ?

**Comment by MouettE-SC** [comment]
I assume your are not running int the embedded jetty server. AFAIK there is currently no way to get the context path in a Spark application.

I am working on a slightly modified version of spark which add a ServletContext parameter in the init method so I can get the context path while initializing my application. Maybe it would be less overkill to only provide the context path as a String to the SparkApplication init method. Either way it's a small patch that I can provide as a pull request if you're interested.

As for setting the context path I don't think that's even possible.

**Comment by liniu** [comment]
@MouettE-SC thank you
