### ISSUE TITLE
Reload static files

### ISSUE THREAD

**Issue by jonaszuberbuehler** [perwendel/spark#472]
Is there a way to tell Spark to reload the static file location?
My use case: a user uploads a cropped image that is stored in the static file location and then served to the client. Currently we get a 404.

**Comment by ilja903** [comment]
Hey! Had a same issue a few days ago. Try this workaround:
externalStaticFileLocation(Paths.get("").toAbsolutePath().toString() + "/src/main/resources/public");

**Comment by jonaszuberbuehler** [comment]
@ilja903 Thx, this works. Would still be nice if this also works with `Spark.staticFileLocation("/public")`.

**Comment by tipsy** [comment]
Seems wrong to upload images to the src dir though?

**Comment by tipsy** [comment]
Using external location is the correct way of doing this, I think.
