### ISSUE TITLE
Allow to match paths where the client send end or no ending slash

### ISSUE THREAD

**Issue by davsclaus** [perwendel/spark#474]
If you have a REST service that maps to path `user/list` then clients may call the service with context-path `user/list` or `user/list/` - eg notice the extra ending slash. 

It would be nice if you could configure spark-rest to allow to match both situations. Today only the former is matched.

You can see this in the logs as

```
[qtp1966741820-28] INFO spark.webserver.MatcherFilter - The requested route [/user/list/] has not been mapped in Spark
```

**Comment by davsclaus** [comment]
Btw this is with version 2.3

**Comment by tipsy** [comment]
You can create a filter to strip/add trailing slashes.
