### ISSUE TITLE
[Feature request] Support for reporting data about responses

### ISSUE THREAD

**Issue by NachoSoto** [perwendel/spark#475]
I'm in the process of sending some data from `Spark` to `Graphite`. I'm currently sending response times by calculating the duration between `after` and `before`.
However, I'd like to be able to report the different status codes, but this is impossible to do using `after` right now because the `Response` is not guaranteed to be completely formed yet.

I'm not sure what the best way to handle this is (maybe this is actually already possible, but I couldn't find any way to do it). All I can think is something like `afterResponse` (with probably a better name) that takes a closure with an immutable `Response`, that can be used to inspect all outbound responses.

**Comment by tipsy** [comment]
Would the proposed "finally" filter (https://github.com/perwendel/spark/pull/406) cover your needs?

**Comment by bademux** [comment]
how about
```java
  @FunctionalInterface
  public interface MyRoute extends Route {

    Object handleExtended(Request request, Response response) throws Exception;

    default Object handle(Request request, Response response) throws Exception {
      //before();
      final Object result = handleExtended(request, response);
      //after();
      return result;
    }
  }
```

**Comment by tipsy** [comment]
Use `afterAfter`
