### ISSUE TITLE
[Enchancement] Simplify route creation

### ISSUE THREAD

**Issue by bademux** [perwendel/spark#479]
1. There are no way to create all routes then start instance - for each addRoute\addFilter  `init()` method is invoked.
   [SimpleRouteMatcher.parseValidateAddRoute](https://github.com/perwendel/spark/blob/master/src/main/java/spark/SparkInstance.java#L282)  get some string concatenation `httpMethod + " '" + route.getPath() + "'"` as argument and internally parse it with [validation](https://github.com/perwendel/spark/blob/master/src/main/java/spark/route/SimpleRouteMatcher.java#L64). IMHO, we should pass `spark.route.HttpMethod` and `url` as separate arguments 
2. Shouldn't spark.Routable be an interface with default method as [comment states](https://github.com/perwendel/spark/blob/master/src/main/java/spark/Routable.java#L44)
3. spark.route.HttpMethod enum naming convention is confusing: enum names (GET\POST...) should be uppercased.
4. spark.routematch.RouteMatch#target is type of java.lang.Object it destroys typesafety and complicates the code.

What do you think about this changes? If you ok with changes I can prepare commit.

**Comment by bademux** [comment]
btw, what does mean ```acceptType``` in signature ``void get(String path, String acceptType, Route route)```? Is it response type?

**Comment by bademux** [comment]
Exception can be simplified, too

spark.SparkInstance#exception
```java
    public synchronized void exception(Class<? extends Exception> exceptionClass, ExceptionHandler handler) {
        // wrap
        ExceptionHandlerImpl wrapper = new ExceptionHandlerImpl(exceptionClass) {
            @Override
            public void handle(Exception exception, Request request, Response response) {
                handler.handle(exception, request, response);
            }
        };

        ExceptionMapper.getInstance().map(exceptionClass, wrapper);
    }
```
In java8 it can be done in more elegant way, smth like
```java
ExceptionMapper.getInstance().map(exceptionClass, () -> handler.handle(exception, request, response));
```
so ExceptionHandlerImpl can be safely removed, although it will be breaking change

**Comment by tipsy** [comment]
Sounds reasonable to me. @perwendel ?

**Comment by mahmed8003** [comment]
```java
public class Routes implements ApplicationRoutes {

	@Override
	public void init(Router router) {

		router.BEFORE().with(BeforeLoggerFilter.class);

		router.GET("/").with(HomeRoute.class, JsonTransformer.class);
		router.GET("/test").with(EchoRoute.class, JsonTransformer.class);
		router.BEFORE("/api/users/*").with(UserAuthenticationFilter.class);
		router.BEFORE("/api/boards/*").with(UserAuthenticationFilter.class);

		/*
		 * Authentication section(not included under any filter)
		 */
		router.POST("/api/create/user").with(CreateUserRoute.class, JsonTransformer.class);
		router.POST("/api/authenticate/user").with(AuthenticateUserRoute.class, JsonTransformer.class);
	}

}
```

This is how I manage my routes in my current project. I will create a git repo for better explanation if I get the time

**Comment by bademux** [comment]
@mahmed8003 it looks like you use some reflection `.with(BeforeLoggerFilter.class)`. Imho it isn't the best solution, imho.

**Comment by tipsy** [comment]
Some of this has been addressed, will try to fix all of it (except 1.) in v3.
