### ISSUE TITLE
[Q] Some tests are broken on master

### ISSUE THREAD

**Issue by bademux** [perwendel/spark#481]
Hi,
trying to contribute.

looks like spark.GzipTest and spark.RedirectTest are broken.
Running the test form maven verify task on Windows.
for 2.3 tag all tests pass.

Can anyone confirm\fix this?
Thanks

**Comment by dinesh707** [comment]
Tests are not broken in following configuration. Ran "mvn clean test" and they were okay.
```
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_72-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-38-generic", arch: "amd64", family: "unix"
```
But when I run the tests from eclipse, it got stuck at following
`[main] WARN spark.Spark - Static file location has already been set`
