### ISSUE TITLE
No logging of uncaught exception in user code

### ISSUE THREAD

**Issue by MouettE-SC** [perwendel/spark#486]
Previous versions of spark would log uncaught exceptions in filter/routes especially when there is no exception handler but it doesn't log anything which makes it difficult to debug problems in user code during development. Based on what was done in 2.3 (adapted to the new codebase of 2.4) I will provide a small pull request to fix it.

**Comment by MouettE-SC** [comment]
I've created pull request #487 to resolve this.

**Comment by edwardmp** [comment]
Indeed this is very annoying and makes it hard to track down stuff. Hope this gets merged in soon.

**Comment by tipsy** [comment]
You can always add slf4j for it to behave like before:

```xml
 <dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.7.13</version>
</dependency>
```

**Comment by MouettE-SC** [comment]
Adding slf4j-simple does not solve the issue. Firstly because I already use log4j for my project with its slf4j wrapper, it will conflict with the simple wrapper. Secondly because adding a wrapper won't make spark log the exception. In any case I tried to create an test project with a single route throwing an exception and slf4j-simple ; A 500 error is returned to the browser (expected) but except for startup message and favicon not found, nothing is logged in the console.

**Comment by tipsy** [comment]
You're correct, I was confusing this with the BYOL change we made earlier. Any reason not to merge this @perwendel ?

**Comment by MouettE-SC** [comment]
See #585

**Comment by hisham** [comment]
+1
