### ISSUE TITLE
Inaccurate error message when handler returns null

### ISSUE THREAD

**Issue by chrisranderson** [perwendel/spark#489]
Here is the code, x is an object I've created:

```
 post("user/login", (request, response) -> {
           ...
           return x.getResponse(); // *x.getResponse() is null at this point*
});
```

When null is returned, Spark sends a 404 and reports in the console that `The requested route [/user/login] has not been mapped in Spark`. The route was found (so 404 probably isn't correct), and the route has been mapped, it just isn't working correctly. 

P.S. Awesome library! Thank you!

**Comment by basdek** [comment]
I agree that this is somewhat irky behaviour.

**Comment by ruurd** [comment]
Uhm well a response should be returned so if the implementor decides that x == null then he should create a response indicating the desired result and HTML result code. It is hard for spark to guess what the HTML result code must be in this case so 404 is as good as any.

**Comment by chrisranderson** [comment]
Wouldn't 404 be more appropriate if you didn't define a `post` or `get` for that route? It found a route, just the route returned null.

**Comment by ruurd** [comment]
No if get or post are not defined I would return a 405 or a 501. Have a look at HTTP result codes. My point is: if you end up in a condition that you cannot return a valid response, you should define a response that must be returned instead.

**Comment by chrisranderson** [comment]
I'm talking more for debugging. The error message leads me to believe that I never defined anything for `user/login`, but it's pretty clear that I did "map a route in spark".

**Comment by ruurd** [comment]
I think the HTTP response mechanism leaves ample room to pass a good message to the browser in that case. You can just return null and spark will catch that for you but the onus is on you and not spark if you want to have meaningful error messages in that case.

**Comment by tipsy** [comment]
Changed my mind, this is not actually a bug. If your route is null, 404 seems fine.
