### ISSUE TITLE
Faster route matching algorithms.

### ISSUE THREAD

**Issue by mschurr** [perwendel/spark#500]
The current route matching (SimpleRouteMatcher) is very slow... it runs in O(n) time with respect to the number of routes installed.

You should move to using a radix-tree based route matching system. These run in O(n) time with respect to the length of the request path (regardless of the number of routes installed).

See:
https://github.com/augustl/path-travel-agent
https://github.com/mschurr/lightning/blob/master/src/main/java/lightning/routing/RouteMapper.java

**Comment by tipsy** [comment]
Is this an actual problem though? The number of routes is usually in the tens to hundreds, what kind of performance improvement would this yield for a typical application?

**Comment by tipsy** [comment]
Had a chat with the creator of Path Travel Agent, seems we're talking improvements on the micro-second scale here (given worst case scenario routes in a normal sized application). I won't close the issue, but I'll mark it as low priority.

**Comment by tipsy** [comment]
Realistically we won't be able to prioritize this, so I'm closing it for now.
