### ISSUE TITLE
WebSocket client

### ISSUE THREAD

**Issue by Willsr71** [perwendel/spark#504]
There is a websocket server in spark, is there any websocket client currently implemented or planned?

**Comment by tipsy** [comment]
Why would you want to add a client to a web server project?

**Comment by Willsr71** [comment]
Not necessarily a part of this project, but I was asking because I don't particularly want to use netty if there was something much more compact available.

**Comment by tipsy** [comment]
@perwendel was talking about creating a (non-websocket) client library actually, but I'm guessing he doesn't have the time currently :smile:

**Comment by tipsy** [comment]
I'll close this, since it's not really related to the Spark core.
