### ISSUE TITLE
Setting Content-Encoding to gzip does not compress static files.

### ISSUE THREAD

**Issue by jannotti** [perwendel/spark#522]
Static files, served after a call to  Spark.externalStaticFileLocation are not gzipped, even if

```
Spark.after((req, res) -> {
    res.header("Content-Encoding", "gzip");
  });
```

is used.  The header is indeed added to the response, but the content is sent without compression.  That confuses browsers pretty badly.  Chrome, for example, says net::ERR_CONTENT_DECODING_FAILED, and seems to keep the socket open for a long time, but certainly never renders the content.

The same issue is described by someone else in the google group here: https://groups.google.com/forum/#!searchin/sparkjava/gzip/sparkjava/B6mcqjGn-Jk/bPbiA6ueIAAJ

As a temporary workaround, is there an easy way to inspect the request to find out if it was handled by the static file code?  That way I can skip adding the header.

**Comment by tipsy** [comment]
This was fixed some time ago (although not in the after-filter, you can use `staticFiles.header()` now.

**Comment by Billgeorge** [comment]
Hello,
@tipsy 
Right now, I am having the same problem, I need to compress the js and css files, I have been searching but don´t find any example of this, could you help me please?...
Thanks
