### ISSUE TITLE
Custom 404 Page when using Static File Route?

### ISSUE THREAD

**Issue by heller** [perwendel/spark#54]
When using `staticFileRoute("/foo")`, is there an easy way to configure a static, catch-all 404 error page? (Defining a `get(new Route("*"){…})` at the end causes the static files to not be served.)

**Comment by mnrasul** [comment]
+1
Even if there is a special route for errors, it would be useful. Right now, there is no way to handle any error messages and staticFileRoutes at the same time.

Thanks.

**Comment by draeron** [comment]
started using spark framework 2 weeks ago, about and this is the first issue i ran into

**Comment by mnrasul** [comment]
I looked under the hood, and there is no reasonable way to fix this. Perhaps, I couldn't understand it.

Either ways, its telling that this has been open for 2 years, and I expect it to be a basic feature.

I'm tinkering with Dropwizard.io now and like it so far, perhaps, you will consider it worthwhile as well.

**Comment by nkavian** [comment]
+1

**Comment by perwendel** [comment]
Implementation of static resources changed. This is now fixed.

**Comment by perwendel** [comment]
re-opening until PR merged...
