### ISSUE TITLE
Support reading static files from multiple sources in classpath (jars and/or physical folders)

### ISSUE THREAD

**Issue by MouettE-SC** [perwendel/spark#547]
The current implementation of classpath static resource handling does not allow in some cases to read static files splitted in both physical folders and jars. The behaviour is spark is dependant of the classpath entries order.

This is problematic when deploying on tomcat because the war is unpacked so if the war contains some static files, all static files in jar dependencies are not accessible. It's possible to disable war unpacking but the webapp performance is affected.

The issue can be hard to apprehend ; I can provide more details with examples if needed.

I've written a patch which fixes the issue in PR #548 .

**Comment by cricket007** [comment]
@MouettE-SC I just made a new issue for a problem I am having, but would your PR help with #557?
