### ISSUE TITLE
2.5 tag (not a code issue)

### ISSUE THREAD

**Issue by federicoboerr** [perwendel/spark#560]
Thanks for this great contribution.
So far, I have a great experience using it. Nothing like it in the market.

Just a quick question. I'm trying to access the source code that was released in 2.5 and was not able to find the tag.
Did you forget to push it?

**Comment by MouettE-SC** [comment]
The tag is indeed not present. The commit ID for 2.5 is fe3ffdc

**Comment by tipsy** [comment]
Has been fixed.
