### ISSUE TITLE
Controllers for spark?

### ISSUE THREAD

**Issue by Shujito** [perwendel/spark#569]
There's this library called [pippo](http://pippo.ro/) that has a [module for controllers](http://www.pippo.ro/mod/controller.html)
it goes like this:

    public class ContactsController extends Controller {    
        public void index() {
            List<Contact> contacts = contactService.getContacts();
            getResponse().bind("contacts", contacts).render("contacts");
        }
    
        public void getContact(@Param("id") int id) {
            Contact contact = contactService.getContact(id);
            getResponse().bind("contact", contact).render(contact);
        }
    }

it is used like this:

    Pippo pippo = new Pippo();
    pippo.getApplication().GET("/", ContactsController.class, "index");
    pippo.getApplication().GET("/contact/{id}", ContactsController.class, "getContact");
    pippo.start();

Is there a way to make this sort of controllers in Spark?
Thanks beforehand.

**Comment by ernestomancebo** [comment]
Hi,

To setup and put a service to run, you have to import the static method you're pretending to use from the spark.Spark class, 'get' in this case; then, you have to compile and build your application and deploy it or run it with the embedded server.

Following the example extracted from the project page and adapted to yours:

```Java
import spark.Spark.get;
import spark.servlet.SparkApplication;

public class ContactsController implements SparkApplication {

	@Override
	public void init() {
		get("/", (request, response) -> {
		    // Show something
		});
	}
}
```

Take in count that if you're going to use the embedded server, then you don't have to implement the SparkApplication interface nor override any method.

Hope this could answer your question.

**Comment by Shujito** [comment]
Not really, but thanks anyway (:

**Comment by ernestomancebo** [comment]
I might be confused about your question, it's possible to explain a little more?

**Comment by Shujito** [comment]
I figured I should had given more details.

What I want, or want to know, is if there is a way to make controllers the way pippo does (that library I linked up there): make a class, write your methods - wich are mapped to your defined routes, and get the parameters you want mapped into the parameters of the method.

**Comment by fwgreen** [comment]
You might have to stick with Pippo as Spark doesn't have any means of extracting the parameters for you.  You can get a similar code pattern by placing your handlers in a separate class... 
```Java
import spark.ModelAndView;
import spark.Request;
import spark.Response;

public class ContactsController {
    
    public static ModelAndView index(Request req, Response res) {
        Map<String, Object> map = new HashMap<>();
        List<Contact> contacts = contactService.getContacts();
        map.put("contacts", contacts);
        return new ModelAndView(map, "index.mustache");
    }
   public static ModelAndView getContact(Request req, Response res) {
        Map<String, Object> map = new HashMap<>();
        int id = Integer.parseInt(req.params(":id"));
        Contact contact = contactService.getContact(id);
        map.put("contact", contact);
        return new ModelAndView(map, "contact.mustache");
    }
}
```
and access them by method reference
```Java
import static spark.Spark.*;

public class WebApp {
    
    public static void main(String[] args) {
        get("/", ContactsController::index, new MustacheTemplateEngine());
        get("/contact/:id", ContactsController::getContact, new MustacheTemplateEngine());
    }
}
```
but you are on your own for everything else.  Spark is intentionally very stripped down.

**Comment by Shujito** [comment]
That helps, I'll try that

Thanks, I appreciate your response

**Comment by tipsy** [comment]
This example also shows using Route fields for controllers: https://sparktutorials.github.io/2016/06/10/spark-basic-structure.html#applicationjava

**Comment by Shujito** [comment]
That's new, I haven't seen it, thanks.
