### ISSUE TITLE
Static instance of ExceptionMapper.

### ISSUE THREAD

**Issue by nkavian** [perwendel/spark#570]
When using the new multi-service feature, the wrong exception mapper is used between 2 services because it's using a static shared exception mapper: https://github.com/perwendel/spark/blob/114d245ef68b1f25d9793d099ae1ca25bd63f1b7/src/main/java/spark/Service.java#L390

**Comment by melges-morgen** [comment]
Guys, can i hope that this bug will be fixed, as far as I can see, pool-request is ready?

**Comment by perwendel** [comment]
Fixed by #1033
