### ISSUE TITLE
NPE because ResponseWrapper does not override a method.

### ISSUE THREAD

**Issue by nkavian** [perwendel/spark#573]
Response.java has this method:     public void cookie(String path, String name, String value, int maxAge, boolean secured, boolean httpOnly)

The same method doesn't exist in ResponseWrapper.java, so if you happen to be setting a cookie it calls into Response instead of the wrapper and an NPE occurs.

ResponseWrapper simply needs to add:
````
    @Override
    public void cookie(String path, String name, String value, int maxAge, boolean secured, boolean httpOnly) {
        delegate.cookie(path, name, value, maxAge, secured, httpOnly);
    }
````

I'm not sure about what tests are needed so not eager to send a PR.

**Comment by leap-nk** [comment]
Solved by PR https://github.com/perwendel/spark/pull/572
