### ISSUE TITLE
Apply after filters if exception occurs

### ISSUE THREAD

**Issue by Yqwed** [perwendel/spark#577]
After filter aren't applied if exception happened while processing request even if exception was handled

**Comment by AzureusNation** [comment]
@Yqwed  Do you have a way to reproduce this?

**Comment by ferwasy** [comment]
It's clear in the source code of MatcherFilter#doFilter()

```
try {

            BeforeFilters.execute(context);
            Routes.execute(context);
            AfterFilters.execute(context);

        } catch (HaltException halt) {

            Halt.modify(httpResponse, body, halt);

        } catch (Exception generalException) {

            GeneralError.modify(httpResponse, body, requestWrapper, responseWrapper, generalException);

        }

```

AfterFilters.execute(context) is not executed if Routes.execute(context) throws an Exception

**Comment by MouettE-SC** [comment]
We have a pull request to address this : #546 which add the finally after filter, always executed even when an exception is thrown

**Comment by MouettE-SC** [comment]
PR has been merged, this issues can be closed now.
