### ISSUE TITLE
Response status is always 404 when ExceptionHandler is executed

### ISSUE THREAD

**Issue by CarlosMChica** [perwendel/spark#582]
I'm facing the following issue. Whenever I set up an exception handler for a particular exception the response has a 404 status code. 

What I'm trying to do is to set a status code in the response object received in the handle method of the ExceptionHandler. 

Thanks in advanced

**Comment by TuxGamer** [comment]
Hm, that's not the case for me (catching java.lang.Exception)

You can set the status manually:
`res.status(500);`

**Comment by pgKuantic** [comment]
Hi all, 

I was facing the exact same issue. And I just find the solution : 

To overwrite the response status, you need to set the new response status **AND** a body: 

```
public void handle(Exception e, Request req, Response res) throws Exception {
    // your code
    res.status(500);
    res.body(e.getMessage());
}
```

without the body, you get a 404 (not defined path).
