### ISSUE TITLE
Porting to gradle

### ISSUE THREAD

**Issue by imrichardcole** [perwendel/spark#584]
Would there be any interest in a PR that ports spark to gradle?

**Comment by tipsy** [comment]
Are there any benefits?

**Comment by imrichardcole** [comment]
I believe that's subjective.

**Comment by jamespedwards42** [comment]
+1 ... Completely agree with the sentiment of @imrichardcole.  Gradle versus maven is up there with number of stars/watchers/contributors when selecting between projects for me.  Unfortunately, I also cannot think of a more objective argument, maybe one can be found in: http://gradle.org/maven_vs_gradle/.

**Comment by imrichardcole** [comment]
I'm more than happy to just do it, submit a PR and people can decide for themselves.

**Comment by tipsy** [comment]
Do you think switching to Gradle would make it easier for people to contribute to the project? My understanding is that most people learn Maven before Gradle. Also, our Maven config pretty is minimal, and most people won't really touch it when working on the source code.

**Comment by jamespedwards42** [comment]
It is always a nightmare for me to get a maven project to work in my eclipse.  In comparison with the gradle eclipse plugin, just run gradle eclipse form the command line and everything just works and I don't need to add any plugins to eclipse.

I suspect most maven users have never really used gradle, where as most gradle users have used maven and hope they never have to again.

**Comment by jamespedwards42** [comment]
Also, if you properly use the [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) it will automatically handle installing gradle for the user on any platform.

**Comment by jkwatson** [comment]
I'm the opposite. I've used gradle, and have to use it at work, and desperately wish I never had to touch gradle again for anything. Not saying maven is awesome, but at least you get xml schema validation for your build scripts.

**Comment by imrichardcole** [comment]
@jamespedwards42 gradle wrapper and idea integration (Intellij) is a big plus for me as well.  @tipsy in my case yes, I checked spark out hoping to make a change and then realised it was maven, then I realised I didn't have maven installed, then I broke out in cold sweats about having to install it, set random ENV variables until it worked etc etc.  

Again, I'm not naive enough to think that someone coming from a maven background wouldn't feel the same way about gradle.  My fork is almost ready, so should have something for people to take for a spin shortly.

**Comment by thomaseizinger** [comment]
OT: 
> Also, if you properly use the Gradle wrapper it will automatically handle installing gradle for the user on any platform.

There are also maven wrapper projects out there. I prefer [this](https://github.com/takari/maven-wrapper) one and usually install it through the embedded maven installation that comes with IntelliJ.

**Comment by sp-1234** [comment]
@jkwatson not sure what exactly brings XML schema validation in Maven; if there's some syntax (or other) error in gradle build script, it'll show some sane error message, there are no real problems with that.

**Comment by tipsy** [comment]
Doesn't seem like a lot of people want this.
