### ISSUE TITLE
maybe some type error in readme.md

### ISSUE THREAD

**Issue by magicly** [perwendel/spark#586]
In the readme.md file, there is a comment:

 * Note: There is a second "before filter" that adds a header to the response
 * Note: There is also an "after filter" that adds a header to the response
 */

I think "before filter" is that adds a header to the request.  Maybe it's typo error, but confuse me. 

Thanks~

**Comment by tipsy** [comment]
You can use before-filters on responses to, but if you point me to the specific line I can have a look.

**Comment by tipsy** [comment]
Found it, everything seems to be in order.
