### ISSUE TITLE
Overriding stop

### ISSUE THREAD

**Issue by leenasn** [perwendel/spark#587]
Hi,

Thank you for providing such a lightweight MVC framework, its really cool. I've question related to stop.

This is my requirement i.e. I've an embedded Redis server which I would like to start when the app starts and I also would like to stop when the app gets stopped. Hows can I that? I saw that that stop method is available, but its static and there are no hooks/callbacks I could see to change it. 

Can someone help to answer this? Thanks.

Leena

**Comment by AzureusNation** [comment]
Hmm... good question, I cant see a way of doing this without creating a class that extends Spark and one that extends Service and then overriding the methods needed.

Maybe this is feasible to look at adding a very light weight call back system.

any thoughts @tipsy @perwendel ?

**Comment by tipsy** [comment]
@perwendel was looking into life-cycle events at one time, but I'm not sure what happened.

**Comment by AzureusNation** [comment]
@tipsy I could make a proposal for an events system.

```java
event(Priority.NORMAL, Event.STOP, (some parameters) -> {
    insertLogicHere();
});
```

**Comment by tipsy** [comment]
That looks pretty cool. @perwendel has final say on what goes into Spark, but I know he was looking into this some time ago, so I think he would like it. Could you create a new issue?

**Comment by AzureusNation** [comment]
@tipsy Sure I'm on it.

**Comment by leenasn** [comment]
Thank you for taking this up. I could find a way to shutdown using the Runtime class. I added the following code snippet in my Application class :

```
            Runtime.getRuntime().addShutdownHook(new Thread() {
                public void run() {
                    try {
                        redisServer.stop();
                        mainThread.join();
                    } catch (InterruptedException e) {

                    }
                }
            });

```

I assume this is a good workaround until Spark introduces lifecycle event hooks.
