### ISSUE TITLE
response.status() throws NullPointerException

### ISSUE THREAD

**Issue by aurabhi** [perwendel/spark#592]
I am using a simple app from the documentation. 

``` java
import static spark.Spark.*;

public class HelloWorld {
    public static void main(String[] args) {
        get("/hello", (req, res) -> "Hello World");
        after((request, response) -> {
            try{
                System.out.println("" + request.url() + " " + request.contentLength() + " " + response.status());
            } catch(Exception e){e .printStackTrace();}
        });
    }
}
```

The response.status() throws the NullPointer.

**Comment by tipsy** [comment]
Well that's puzzling: 
```java
import static spark.Spark.*;

public class HelloWorld {
    public static void main(String[] args) {
        get("/hello", (req, res) -> "Hello World");
        after((request, response) -> {
            try {
                System.out.println("Raw status: " + response.raw().getStatus());
                System.out.println("Wrapped status: " + response.status());
            } catch (Exception e) {
                e.printStackTrace();
            }
        });
    }
}
```
The raw status is fine, the wrapped one causes a NPE... but the wrapper just calls getStatus() on the raw response. Hm.

**Comment by zmalik** [comment]
Happened to me also. 
Its because of the missing implementation of the status() in the ResponseWrapper.

The next override in the ResponseWrapper solved the problem.

```
@Override
public int status() {
       return delegate.getStatus();
}
```

**Comment by jacopofar** [comment]
Great! Do you know when will this fix appear on the Maven repository?

**Comment by AzureusNation** [comment]
@jacopofar It will be in release 2.6 and there hasn't been any release date given as yet.

**Comment by tipsy** [comment]
Was released a long time ago!

**Comment by jacopofar** [comment]
Sorry but I can't see it, has it a different name now, or the maven repo is not updated ?
https://repo1.maven.org/maven2/com/sparkjava/spark-core/

**Comment by tipsy** [comment]
What can't you see? `status()` and `type()` should be available (and working) on `Response` now.

**Comment by jacopofar** [comment]
Oh I see, it was said above that it would have been the version 2.6, but I see that 2.5.5 was released recently. Thanks!
