### ISSUE TITLE
Invoke route from with the server

### ISSUE THREAD

**Issue by KevinMitchell** [perwendel/spark#595]
Within the handler for a route I'd like to be able to invoke other routes.  Now I could do the required dispatching myself.  But it seems undesirable to do this when we already have the find method defined in the Routes class.  But I can't see any way of accessing the instance of the Routes class that holds the routes I've defined.   I'd been expecting the Spark class to expose a static Routes object.  So are we supposed to work with our own Routes instance somehow, or is there a better way of doing this?

**Comment by tipsy** [comment]
I usually do this:

```java
Route routeOne = (Request request, Response response) -> {
    return "Route One";
};

Route routeTwo = (Request request, Response response) -> {
    return routeOne.handle(request, response);
};
```

**Comment by KevinMitchell** [comment]
Thanks for the suggestion.  That works fine for a "static" case where you know at compile time what route you want to invoke.  But ideally I'll like to make use of the find method within the Routes class.  However the Service instance inside the Spark class is private and the Routes instance inside the Service class is also hidden.  I could obviously maintain my own Routes object, but this seems messy.  So is there a reason for hiding these things?

**Comment by tipsy** [comment]
> So is there a reason for hiding these things?
@perwendel would have to answer that.

**Comment by tipsy** [comment]
Duplicates #386
