### ISSUE TITLE
CSS files served as text/plain

### ISSUE THREAD

**Issue by Ribesg** [perwendel/spark#598]
This is, I think, similar to #373, but I'm using standalone mode with jetty.

Static CSS files are served as plain/text. This is a problem. There are two changes needed:
- [ ] Automatically add Content-Type header when statically serving CSS files, as it's common sense
- [ ] Allow before and after filters to work for static file requests, as people may need to do things depending on the served file. For example here this would allow adding the Content-Type for CSS, but there are a lot of use cases.

Please also note that this is a high priority issue, as it completely breaks internet explorer support.

**Comment by Ribesg** [comment]
Ok I just noticed this commit https://github.com/perwendel/spark/commit/4a2b982b39d279350663e6ff926ea4ee26aafdd3

You may want to close this issue once it's completely implemented/tested (if it isn't yet), hopefully this will get released ASAP!

**Comment by tipsy** [comment]
This should work!
