### ISSUE TITLE
Missing getters in ResponseWrapper

### ISSUE THREAD

**Issue by KevinMitchell** [perwendel/spark#599]
Not sure if I'm just getting confused, but it looks like the setters on ResponseWrapper just delegate to the delegate Response object.  But most of the corresponding getters aren't overridden and so just get their values from the response field rather than the delegate field.  And as the response field is null this makes the getters such as response.status() and response.type() fall over.  So is the response field inside the wrapper instances supposed to be non-null?  And if it can be null, shouldn't the class override all the getters to use the delegate?

**Comment by dherges** [comment]
``((ResponseWrapper) response).status()``.. throws a ``NullPointerException`` 💣 

however

``((ResponseWrapper) response).getDelegate().status()`` .. returns an int  😄

**Comment by tipsy** [comment]
Should be fixed.
