### ISSUE TITLE
Read Headers from Response object

### ISSUE THREAD

**Issue by dherges** [perwendel/spark#601]
IMPROVEMENT: `response.header()` --> return a `Map<String, String>` with the header values that have been set.

USE CASE: Say, one wants to implement a thin caching layer using `after()` and `before()` filter. Right now, only possible to put `response.body()` in cache, thus being inable to retrieve headers from cache entries.

What do you think?

Know that it's possible to maintain an external web proxy / caching by infrastructure. So, still not quite sure whether it's a good idea to have in-memory caching in the app ... anyway though, why not let people read response headers?

**Comment by jakaarl** [comment]
I don't know how necessary this would be, but I guess it wouldn't hurt either?

Implementation could be something as trivial as adding a small method to `spark.Response`:
```
public Map<String, Collection<String>> headers() {
    Map<String, Collection<String>> headers = new HashMap<>(response.getHeaderNames().size());
    for (String header : response.getHeaderNames()) {
        headers.put(header, response.getHeaders(header));
    }
    return headers;
}
```

**Comment by jakaarl** [comment]
Yes, `Collection<String>`, since multiple headers with the same key are allowed.

**Comment by dherges** [comment]
I remember that I tried to do so but it's not too trivial because of the servlet API underneath. One needs to store the headers in private field and then flush to the ``ServletRequest`` when needed, much like ``serializeTo`` in ``Body``: https://github.com/perwendel/spark/blob/e213a92ba6b7c18b20cdc387c43e944caec0d6c0/src/main/java/spark/http/matching/Body.java#L59-L77

--

regarding the API: there could be multiple methods, maybe like

``headers(): Map<String, String>``
``headersMultiValue(): Map<String, Collection<String>>``
``header(key: String): String``
``header(key: String): Collection<String>``

.. or there could be an abstraction like a ``ResponseHeaders`` class?

**Comment by jakaarl** [comment]
I wrongly assumed Response simply wraps the underlying servlet response - clearly there's more going on. I tried this out, and trying to get the headers in Response resulted in an NPE.

**Comment by tipsy** [comment]
Since this sounds like something very few people will use, I think 
```
after((req, res) -> {
    res.raw().getHeaderNames().forEach(h -> System.out.println(h + ":" + res.raw().getHeader(h)));
});
```

Should be fine. I'll close the issue, but feel free to create a PR if you really want this functionality.
