### ISSUE TITLE
if i want to use velocity toolbox  ，  What should I integrate

### ISSUE THREAD

**Issue by 602884291** [perwendel/spark#609]
if i want to use velocity toolbox  ，  What should I integrate。thanyou

**Comment by tipsy** [comment]
Just add the dependency? https://mvnrepository.com/artifact/org.apache.velocity/velocity-tools/2.0

**Comment by chess-levin** [comment]
Hi there,
I've tried to use the Escape Tool $esc  from velocity tools and added therefore 


```
  <dependency>
      <groupId>com.sparkjava</groupId>
      <artifactId>spark-template-velocity</artifactId>
      <version>2.7.1</version>
  </dependency>
  <dependency>
      <groupId>org.apache.velocity</groupId>
      <artifactId>velocity-tools</artifactId>
      <version>2.0</version>
  </dependency>
```

to my pom.xml

Unfortunately $esc is not found in my templates. But there is also no error in the log output of spark, that could help for further debugging.

How to correctly integrate velocity tools and how to configure log levels? And where to put velocity.properties / tools.xml?

Can anybody help?
