### ISSUE TITLE
Removing routes at runtime

### ISSUE THREAD

**Issue by gtwardus** [perwendel/spark#610]
Is there any way to remove a route at runtime? I've seen this thread https://github.com/perwendel/spark/issues/231 which ended up being implemented in version 2.2 but I can't find it anywhere in version 2.5 which I am currently using. There is a remove() message in Routes class but it is cannot be called since Routes is a protected property of Service. PS. Great software by the way :)

**Comment by AzureusNation** [comment]
Hmm, looks like we might need a method or two in the Service class to access the routes or just to remove a route. I'll create a pull request later on fixing this.
