### ISSUE TITLE
Event System

### ISSUE THREAD

**Issue by AzureusNation** [perwendel/spark#615]
The idea is to have a very dynamic event system where events can be registered and removed at runtime if needed.

These event would be registered in the same way as your GET or POST methods would be in the main Spark class. These would then have a priority, the event type, some parameters and then the logic to be executed. So it would look a little something like this:

``` java
event(Event.SERVER_STOP, (some parameters) -> {
    insertLogicHere();
});
```

This would be the default implementation  and the priority will be normal and the time it would be executed would be before the stop method. But there are more complex event handlers you could have. For instance how about an event priority:

``` java
event(Priority.NORMAL, Event.SERVER_STOP, (some parameters) -> {
    insertLogicHere();
});
```

Or if you want your code run before or after the event (i.e. for the stop method your code could be run before or after the server has been stopped)

``` java
event(Priority.HIGH, Event.SERVER_STOP, Event.AFTER, (some parameters) -> {
    insertLogicHere();
});
```

This is backed up with a great use in issue #587 where they have an embedded Redis server that they would like to start and stop when the Spark server starts and stops.

So for the removing of events at runtime, the event method that is called to register an event will return either a event id or an event class so that each event handler is identifiable. These could then be removed by calling eventRemove(id); with either the id of the class being an integer or an object of an event class.

All suggestions are welcome and this is up for discussion but I would be writing the implementation.

12/07/16 Update 1:
Just a quick update to let everyone know that I have a very early working version of this and it is **VERY** small. The handler class is only about 8 lines of code for this to work. I am chuffed but a little kid could do what I've done. I will keep working and keep you all updated as I need more input.

**Comment by BrickXu** [comment]
Is there any ideas to merge this feature into next release ?

**Comment by AzureusNation** [comment]
@BrickXu This tbh is more than likely going to be in Spark 3.x

**Comment by jakaarl** [comment]
Well, having an event system would be a game changer for the requested SSE and 202 Accepted features, since they would all of a sudden make much more sense.

**Comment by tipsy** [comment]
Added to v3 wishlist
