### ISSUE TITLE
Don't write startup message into stderr

### ISSUE THREAD

**Issue by mastertinner** [perwendel/spark#617]
When Spark ignites, many messages get written to standard error. In my opinion, these should be written to standard out instead. My logs show errors as red text so it always looks like something failed when actually everything started successfully. These messages include:

* `[main] INFO spark.staticfiles.StaticFilesConfiguration - StaticResourceHandler configured with folder = /public`
* `[Thread-0] INFO org.eclipse.jetty.util.log - Logging initialized @180ms`
* `[Thread-0] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...`
* `[Thread-0] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:8080`
* `[Thread-0] INFO org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT`
* `[Thread-0] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@11343699{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}`
* `[Thread-0] INFO org.eclipse.jetty.server.Server - Started @278ms`

**Comment by AzureusNation** [comment]
Agreed, these should be set as INFO log level. I will look at making a PR and changing this tonight.

**Comment by AzureusNation** [comment]
Jut a quick update, I have had a look and because we use sfl4j-simple this passes all logs no matter what they are to the System.err. I propose that we migrate to Logback.

Logback is the successor to log4j. We can still use the sfl4j api but as a backend and extensively configurable Logback is the best way to go.
Thoughts @tipsy @perwendel ?

**Comment by MouettE-SC** [comment]
slf4j-simple is a test dependency of spark (only used for tests) therefore it should not be in the classpath when running a project with spark as a dependency (unless you add it explicitely in your pom.xml). Without slf4j-simple or any slf4j binding, the console only prints :
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
You can use any binding with slf4j such as log4j, logback or slf4j-simple. Do not mix the standard error output and the log levels. slf4j-simple writes everything with info log level (and below) to System.err by default; @mastertinner if you want the output to go to System.out while using the slf4j-simple binding, see http://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html and set the system properties (or a simplelogger.properties file in the classpath) accordingly.

Being a library project, spark do not use any log implementation, only the slf4j API which is the right way to go. It's only needed in the test phase in which slf4j-simple is sufficient.

**Comment by mastertinner** [comment]
Thanks for your help, @MouettE-SC! I chose `slf4j-nop` and now it works without writing into stderr. I'll close this issue since the problem described by me was not one of Spark.
