### ISSUE TITLE
Returning null from a Route implementation results in 404

### ISSUE THREAD

**Issue by pedromss** [perwendel/spark#620]
**Spark version:** 2.3

It seems to be impossible to return no body. For example when I execute a POST request sometimes I don't want to return any content in the body. Currently I think returning an empty string can accomplish this. In my opinion it makes more sense to return null from the route handler, however when I returned `null` the control flow defaults to "route '/someroute' as not been mapped in spark".

This is misleading because the route was matched and the request was processed, therefore it makes no sense to default to 404.

**Comment by AzureusNation** [comment]
I'm not sure but I'll check later on to see if this is fixed in version 2.5 and also if my PR #616 fixes this as well.

**Comment by AzureusNation** [comment]
Ok so done some reading... the response to send back needs to be a 204 there is no body that needs to be set as it terminates the first line under the head.

I think that this is going to need to be postponed to version 3.x as there may need to be changes made to the api and I know that @tipsy and @perwendel don't want to do api changes on minor versions if they can help it.

@tipsy any thoughts on this? refactoring the MatcherFilter and also the Spark and Service to allow for more diverse requests like this one.

**Comment by pedromss** [comment]
Should alter the Matching logic not be an option at this time I suggest at least annotating the return time of the `handle` method on the `Route` interface with some `@Nonnull` and write on the javadoc something like: "Shouldn't return null".

**Comment by tipsy** [comment]
> @AzureusNation @tipsy any thoughts on this? refactoring the MatcherFilter and also the Spark and Service to allow for more diverse requests like this one.
Yup, we need to do a bit of a rewrite, and rethink how we do a couple of things... But as you said we have to wait for 3.x.

**Comment by yegeniy** [comment]
Maybe I'm misunderstanding, but what about using an empty string instead of null to represent an empty body?

```
  Scenario: Should return 201 on                           # features/api-v0.feature:6
    When the client performs GET request on /empty         # WhenSteps.perform_Http_Request(String,String)
    Then status code is 201                                # ThenSteps.response_Status_Code_Is(int)
    And response is empty                                  # ThenSteps.response_Body_Is_Empty()
```

```java
... implements Route {
    @Override
    public Object handle(final Request request, final Response response) {
        response.status(201);
        return "";
    }
}

**Comment by tipsy** [comment]
Won't change this for 2.X.
