### ISSUE TITLE
staticFiles.location("/public");

### ISSUE THREAD

**Issue by ph-hs** [perwendel/spark#632]
Examples in new documentation site, don't repeatedly remind folks that /public isn't a root directory on a Unix system, it is root with ./src/main/resources

It should do - classic noob mistake.

I'd have issued a pull request but I don't know where the site source is.

**Comment by tipsy** [comment]
This should be independent of OS, public is just a common name for a static files dir in a resource dir. What do you want to change in the docs?

**Comment by paul-hammant** [comment]
I'm OP, by another name. 

I'd want to lose the convention of the preceding slash for public, or call out more clearing it is not what you initially think - a ref to a true root FS location.

**Comment by wkhudgins92** [comment]
I'm a self-admitted Spark "noob." I didn't think `/public` was a root directory but I had no idea where to put it until I found this PR. FWIW, this was definitely helpful.

**Comment by ph-hs** [comment]
This just needs a JavaDoc comment really. To help us noobs.

**Comment by tipsy** [comment]
This has been added!
