### ISSUE TITLE
[MESSAGE TO COMMUNITY] Vacation without computer

### ISSUE THREAD

**Issue by perwendel** [perwendel/spark#636]
I'm currently on vacation in the "wild" without access to a computer and sporadic internet on my phone. This means that my activity here will be low. 
Combined with the fact that my daughter will undergo an operation in the end of Auguest no complex PRs will be merged and no code contributions from my side will be done before September.

**Comment by ruurd** [comment]
Your Significant Other insisted on this, right?  :-) :-) 

I once had a coworker that proposed to his SO to take his phone with him on vacation. She sweetly asked him 'Can it swim?' The phone staid at home :-)

**Comment by ruurd** [comment]
Oh and have a nice vacation!

**Comment by yegeniy** [comment]
I hope all goes well @perwendel.
