### ISSUE TITLE
Support for 202 Accepted

### ISSUE THREAD

**Issue by binkley** [perwendel/spark#641]
It would be nice to see 202 Accepted support in Spark with clean callbacks for status and completion.  For example, something like a JDK CompletionService for coding the server-side of a 202 interaction (but not necessarily this exact API).

See http://farazdagi.com/blog/2014/rest-long-running-jobs/ for motivation.

**Comment by binkley** [comment]
I don't really mean `CompletionService`.  :-)

The Spark API is much cleaner.  Perhaps something like web sockets.  Nothing in the existing API quite fits.  There's need to be a callback to send status updates to client when polled by them, and a final redirect to the completed resource when it's ready.

**Comment by jakaarl** [comment]
If I understand correctly, Spark cannot really provide horribly much of support without being "overly opinionated" about things it shouldn't be concerned with. IMO the exact responses and such are left to the developer and should not be dictated by the framework:

>    The request has been accepted for processing, but the processing has
>    not been completed.  The request might or might not eventually be
>    acted upon, as it might be disallowed when processing actually takes
>    place. There is no facility for re-sending a status code from an
>    asynchronous operation such as this.
> 
>    The 202 response is intentionally non-committal. Its purpose is to
>    allow a server to accept a request for some other process (perhaps a
>    batch-oriented process that is only run once per day) without
>    requiring that the user agent's connection to the server persist
>    until the process is completed. The entity returned with this
>    response SHOULD include an indication of the request's current status
>    and either a pointer to a status monitor or some estimate of when the
>    user can expect the request to be fulfilled.

**Comment by binkley** [comment]
@jakaarl Thanks for looking at this.  I understand your perspective.

**Comment by jakaarl** [comment]
Well, #615 would certainly open up possibilities with regards to this. Spark could offer "deferred" routes that return 202 Accepted. The API would take some serious consideration though - it should be possible to provide at least: a handler for the response (perhaps Spark could provide an opinionated base class?), a deferred/async job (`Future`s or something?), a handler for queuing/status, and a handler for completion.

**Comment by binkley** [comment]
Thank you for continuing to look at this!

The view with respect to 202 expressed in #615 makes sense to me.  An initially 202 followed by a series of 200 responses when queue status is queried, ending in a 303, seems reasonable.  A great design question is what to do with stale queues, i.e., client abandons the initial request so never follows up, so Spark never sends a 303.  Some mechanism for cleaning out stale queue members seems needed.

In the normal case the client polls and gets a 303 when all is done would naturally clean up the queue, so I would not expect garbage to build up in the normal case.  Either the client would explicitly `DELETE` the queue resource, or the server would have an optional policy to do this automatically.

An example implementation mentioned by a colleague is for `/queue` resources to be backed with persistent storage and never go away (a "soft delete"), or only go away following some server-defined policy.  Of course how to handle this case should be up to the the Spark API consumer.

**Comment by perwendel** [comment]
Asynch requests are contemplated for 3.0 and there are issues/PR for this.
