### ISSUE TITLE
please make server threads more customizable

### ISSUE THREAD

**Issue by pyloque** [perwendel/spark#642]
AFAK, jetty acceptors and selectors threads number cannot be customized.

cores = Runtime.getRuntime().availableProcessors()
selectos = Math.max(1,Math.min(4,cores/2))
acceptors=Math.max(1, Math.min(4,cores/8));

If I set threadpoolsize to 4 for example, it's enough for my macos computers.
But they might not enought for production computers with lots of cpus and cores.
And is some situations, it's kind of waste to start so many threads.

**Comment by tipsy** [comment]
Jetty should be configurable after #813
