### ISSUE TITLE
Image file after being viewed on local server on windows cannot be deleted

### ISSUE THREAD

**Issue by nehasaha** [perwendel/spark#643]
Please find the steps to reproduce
1) Clone the project https://github.com/nehasaha/spark-project
2) Run App.java as java application. This will run the spark server.
3) Navigate to localhost:4567. Two images will be displayed.
4) Run SparkTest.java.

On windows, I get an error that image file cannot be deleted. On Mac it works fine.

**Comment by tipsy** [comment]
This should be fixed (?)
