### ISSUE TITLE
Spark does not start w/ only static file location set

### ISSUE THREAD

**Issue by acwwat** [perwendel/spark#648]
I have just started learning about Spark with the intention of using it as a lightweight application server that mostly serve static files and occasionally use templates for pages with data. I created a simply main method in my application class as follows:

```
public static void main(String[] args) {
    staticFiles.location("/public");
}
```

When I start my application, it seems that Spark will not start and immediately exits with RC 0. However, if I add a route (e.g. using get() or even adding the route overview module, then Spark would ignite and start as expected.

I can also get the server to start by calling Spark.ignite() but according to the code comment I am only to call this method directly when websocket is used.

I am pretty sure that I'll add a route to my application eventually so this is not really a problem here. But I'd still like to know 1) If this is a bug, or 2) if it is not a bug, what is the correct way to get Spark to ignite/start when serving only static files.

Thanks.

**Comment by s-rajaraman** [comment]
I just added a get method inside so the server is listening.

```
import static spark.Spark.*;
public class FileServer {
    public static void main(String [] args){
        staticFiles.location("/public");
        get("/", (res, req) -> "hello world");
    }
}
```

**Comment by acwwat** [comment]
Just spent a bit more time looking at the code, and the behavior seems to be by design. As with  webSocket(), staticFileLocation() or externalStaticFileLocation() must be called before init() is run for the first time. Meanwhile init() is called by any of the routing methods via addRoute(), so Spark is ignited properly whenever a route is added. Otherwise init() must be manually called in the correct sequence.

The requirement of method call sequence has been documented for the WebSocket case in http://sparkjava.com/documentation.html#websockets, but would be nice if the same can be mentioned in http://sparkjava.com/documentation.html#static-files. That means:

1. staticFileLocation() or externalStaticFileLocation() must be called before init() is called or routes are added
2. If using only static file and WebSocket, init() must be called manually.

Please consider this as a doc update. Thanks.

**Comment by tipsy** [comment]
Added to docs (but not currently live)
