### ISSUE TITLE
Consistent 500's after implementing filters.

### ISSUE THREAD

**Issue by RingoMckraken** [perwendel/spark#650]
Currently having an issue where my after filter logic (on a single route) causes the entire application to throw 500 errors on all routes. Removal of the code and recompilation sometimes works but it appears there is something weird going on.

**Comment by nikku** [comment]
Could you add a simple test case that reproduces your issues? Some source code / main class would be very helpful here.

**Comment by perwendel** [comment]
Can't do anything with this without any reproduction steps? Please provide or this will be closed.

**Comment by RingoMckraken** [comment]
Sorry for the late response. I was able to fix the issue.

May be intended functionality but to reproduce the error I had to after() filters in a single controller. One which had a path to "/*" and another that was "/foo/bar". The first filter fired off an expensive operation to the database.
