### ISSUE TITLE
Using spark with mongodb async driver

### ISSUE THREAD

**Issue by shakdwipeea** [perwendel/spark#657]
``` java
post("/save-link", (req, res) -> {
            Document newUser = new Document("username", "foo");
            userCollection.insertOne(newUser, (result, throwable) -> res.body("usersaved"));
            return null;
 });
```

Doing sth like the above is not working. What is the approach to handle async functions ?

**Comment by jakaarl** [comment]
AFAIK, async is not supported. Perhaps you could implement "by hand" something to the effect of 202 Accepted? See #641 for links and discussion.

Or if you're OK with having the client wait, and deploying Spark in non-embedded mode, make an asynchronous servlet?
