### ISSUE TITLE
Unexpected <char>

### ISSUE THREAD

**Issue by stephenjfox** [perwendel/spark#670]
I'm using Spark to write a REST API, with many layers of query-able properties
Spark will regularly ignore my programmatic JSON returns (serialized with org.json) and emits [the title] instead, usually as one of the following:
- Unexpected: 'A'
- Unexpected: 'T'
- Unexpected: '<'

Of course, this is a 500 internal error. 

I can't speak to the rhyme or reason of this error. It could very well be programmer error on my part, but the cause of this issue (via reading source code) is nigh untraceable.

**Comment by stevemasta34** [comment]
My tests are being run with Postman
