### ISSUE TITLE
Most (all?) code examples seem to ignore that the requests/WS messages are processed in different threads

### ISSUE THREAD

**Issue by sp-1234** [perwendel/spark#673]
Typical example: https://sparktutorials.github.io/2015/11/08/spark-websocket-chat.html

> static Map<Session, String> userUsernameMap = new HashMap<>();

This map is in fact written and read from different threads, and this can cause data corruption if I understand right.
It should be probably replaced by thread safe alternative (ConcurrentHashMap), or put behind locks.

https://stackoverflow.com/questions/2688629/is-a-hashmap-thread-safe-for-different-keys

**Comment by tipsy** [comment]
I'm aware of the example in the tutorial, but I figured it's not really relevant to Spark itself, so I left it as a plain map just to be more beginner friendly. It might sound silly, but ConcurrentHashMap will scare people off. I could add comments about it though?

For the docs page I used `ConcurrentLinkedQueue`, did you find anything else in the official docs (not tutorial) which should be fixed?

**Comment by sp-1234** [comment]
>ConcurrentHashMap will scare people off

Broken code will scare people off, because they will assume that the framework itself is written in similar way.
And people who don't even know/think about concurrency issues have no business writing server software…

**Comment by jakaarl** [comment]
I think @tipsy is right in wanting stuff to be simple and concise, but I'll have to agree that having erroneous example code is the greater evil here - not only does it show Spark in a bad light, but also sets a bad example. Thousands of programmers have picked up their bad habits (lack of error handling, non-thread-safety, you name it) from examples and tutorials they've read while learning the ropes.

**Comment by veeti** [comment]
> I left it as a plain map just to be more beginner friendly

There is nothing "beginner friendly" about intentionally broken code and documentation. A beginner can learn about thread safety the easy way through correct documentation, or the hard way when their app starts randomly misbehaving in the strangest ways.

**Comment by tipsy** [comment]
Alright, thanks for your input everyone. I will change it to `ConcurrentHashMap` and add a comment explaining why this is needed.
