### ISSUE TITLE
spark.Service is final, but it has some protected members

### ISSUE THREAD

**Issue by magicgoose** [perwendel/spark#675]
`spark.Service` is final, but it has some protected members.

What's the point of doing this? If the class is final, then protected is effectively the same as private, isn't it?

**Comment by jakaarl** [comment]
No. Protected members are package-visible, unlike private members. Unit tests are a likely explanation here.

**Comment by magicgoose** [comment]
then there should be no modifier

https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html
see table "Access Levels"

**Comment by jakaarl** [comment]
Yes, perhaps. Some people prefer `protected` over "default" visibility, because it's explicit. Omitted modifier -> "default" is just weird language design, IMHO.
