### ISSUE TITLE
Freemarker Maven Dependency Outdated on com.sparkjava

### ISSUE THREAD

**Issue by qjflores** [perwendel/spark#677]
This doesn't work for me when I try to iterate over lists in freemarker with Spark:

```
<dependency>  
  <groupId>com.sparkjava</groupId>
  <artifactId>spark-template-freemarker</artifactId>
  <version>2.3</version>
</dependency>
```

I got this snippet from the Spark documentation.

The latest freemarker version from the maven2 repo is 2.3.9
http://repo.maven.apache.org/maven2/freemarker/freemarker/

I'm able to iterate over lists with :

```
<dependency>
    <groupId>org.freemarker</groupId>
    <artifactId>freemarker</artifactId>
    <version>2.3.25-incubating</version>
</dependency>
```

**Comment by tipsy** [comment]
Bumped.
