### ISSUE TITLE
Use byte[] instead of String for Request.body as well as Response

### ISSUE THREAD

**Issue by bmharper** [perwendel/spark#68]
It's not clear how one is supposed to handle arbitrary binary data inside Spark, since String is used both for request input, and for response output.
If there IS a reliable way in Java to convert between String and arbitrary byte[], then I can't find what it is. I suggest that if such a method exists, then it should be made clear in the docs how to do it.
If not, then I suggest using byte[] in place of String, both for Request.body(), Response.body(), and for all the return phases of the pipeline.

**Comment by psacc** [comment]
+1 we ran into this issue, content encoding should be detected from request headers and worked around the problem with something like this:
```java
new String(request.body().getBytes(), request.raw().getCharacterEncoding());
```

**Comment by tipsy** [comment]
We have bodyAsBytes now

**Comment by fsilkswan** [comment]
Hi everybody,

unfortunately bodyAsBytes is only available for Request, but still not for Response. (-_-)

See issue title: "Use byte[] instead of String for Request.body **_as well as Response_**"

Cheers
-Ferdinand-
