### ISSUE TITLE
URL paths ending in / vs not

### ISSUE THREAD

**Issue by qubbit** [perwendel/spark#685]
Why is `get("/headers"), (req, res) -> "Hello")` different from `get("/headers/"), (req, res) ->  "Hello")`?

**Comment by MartinsThiago** [comment]
One finishes with "/" and the other not :D

Anyway... spark really shouldn't treat them as the same

**Comment by tipsy** [comment]
This is standard behavior for most routing libraries. You can use a `before()` filter to add trailing slashes, or create your own `get()` that maps both routes to the same handler.
