### ISSUE TITLE
Unable to find resource in any resource loader

### ISSUE THREAD

**Issue by Blok5** [perwendel/spark#686]
Hello, mi name is Igor. I saw that you good in Spark java.

I started to learn sparkjava with velocity template engine and faced with the problem, java can't find a template, which i put into public/templates/ folder. I say that staticFileLocation is ("/public"); So, java should find "templates" folder in "public" folder... But i have a wrong unable to find resource 'templates/layout.vm' in any resource loader And This is my tree structure

import java.util.HashMap;
import spark.ModelAndView;
import spark.template.velocity.VelocityTemplateEngine;
import static spark.Spark.*;

public class Main {

    public static void main(String[] args) {
        port(4567);
        staticFileLocation("/public");

        get("/", (request, response) -> {
            return new ModelAndView(new HashMap(), "templates/layout.vm");
        }, new VelocityTemplateEngine());

    }
}
I have not found how to use staticFileLocation! Plz, help, thx!

**Comment by tipsy** [comment]
A template is not static, so you should put it in `resources/templates/layout.vm`

**Comment by tipsy** [comment]
You can look at this project if you still have trouble: https://github.com/perwendel/spark-template-engines

**Comment by Blok5** [comment]
Oh, thank you, thank you very much! 
What is mean "is not static"?

Can you advice, what should I read about spark and where I can take a good information.

**Comment by Blok5** [comment]
Oh, thank you very much!

What is mean, template is not static? 
In which case template is static

**Comment by tipsy** [comment]
Static resources are resources that do not change. The point of velocity files is that they are dynamic, you can define variables like `$username` and pass that from Java.

**Comment by pabloquinci** [comment]
Hi Tipsy!
I'm facing the same issue with a Maven project, so I cloned the repository you provided. Im deploying to a local apache tomcat server 7.0 but no resources are found when I try to open it in the browser
Any idea?

Thanks in advance!
Pablo
