### ISSUE TITLE
Autodetecting mime-type of resources in fat/uber jar in 2.5.1

### ISSUE THREAD

**Issue by kozhevnikov** [perwendel/spark#687]
2.5.1 added auto detecting mime types of static resources and it works when run from within IntelliJ for example but not from a [shaded](https://maven.apache.org/plugins/maven-shade-plugin/examples/executable-jar.html) fat jar hence still blocked in IE and Chome logs a warning. Since `before` is not longer called for static resources after 2.3 how does one get around it and when might fat jar mime guessing be fixed?

I've written a simple shaded sample project below.

https://github.com/kozhevnikov/spark-mime-test

```
mvn clean package
java -jar target/spark-mime-test-1.0-SNAPSHOT.jar
open http://localhost:4567/
```

`Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://localhost:4567/style.css".`

**Comment by tipsy** [comment]
I think #682 fixed this?

**Comment by kozhevnikov** [comment]
Tried `mvn install` off latest `master` and running jar with `2.5.2-SNAPSHOT` straight up downloads `index.html`, nothing gets rendered and it never get to the `style.css`.

**Comment by tipsy** [comment]
I'll check it out in the weekend.

**Comment by tipsy** [comment]
Thanks, will have a lot at it.

**Comment by AmaranthLIS** [comment]
I'm sorry, can you tell, when may be it fixing?
we have same problem:
`Resource interpreted as Stylesheet but transferred with MIME type text/plain`

> for: *.css, *.svg

**Comment by kozhevnikov** [comment]
@tipsy Any luck? Is downgrading to 2.3 and adding a `before` for static the only option?

**Comment by AmaranthLIS** [comment]
2.5.2 had fixed it.

**Comment by kozhevnikov** [comment]
@AmaranthLIS It did not. It made it worse as with 2.5.2 even the `index.html` cannot be rendered, let alone the `style.css` with correct mime type.

**Comment by AmaranthLIS** [comment]
After update up 2.5.2 i build fat jar and the site started to respond correct mime type for css/svg (other mimes didn't check)

**Comment by kozhevnikov** [comment]
Indeed, you are correct. In case of an SPA where `index.html` is implicitly accused via `/` it no longer defaults to html mime type and instead downloads it as file, but hitting `/index.html` explicitly works as expected.

**Comment by tipsy** [comment]
@kozhevnikov you also have the option of disabling the mimetype guessing in 2.5.2. Also, there will be a few improvements to static files handling again in 2.5.3.
