### ISSUE TITLE
Is it possible to use apache shiro with sparkjava? If yes how?

### ISSUE THREAD

**Issue by SeunMatt** [perwendel/spark#690]
I want to setup apache shiro for my authentication. Have got shiro to work in test. Now to plug it in to sparkjava instance seems to be the problem. I have enabled shiro using classpath shiro.ini file but that doesn't seems like it will do. Everytime after successful login, call to subject.isAuthenticated() is always false.

So please, is it possible to use apache shiro with sparkjava? have read [this discussion on the sparkjava google forum](https://groups.google.com/forum/#!topic/sparkjava/HymQ04gVTNs) about using jwt alongside. But that's not what I want.

Tried using web.xml - that is not even visible to sparkjava. So people, please contribute and let me know if it's possible or not. In case it's possible, how?
Thanks for your time.

**Comment by srbattula** [comment]
Please check this:
https://www.allions.net/blog/post/a-simple-back-end-for-web-authentication-built-on-apache-shiro-and-spark-java

**Comment by jmiguel77** [comment]
is there any documentation about how to do this with shiro 1.4.* ?

**Comment by srbattula** [comment]
I believe there are good references over internet. Give me a day to dig
them out
