### ISSUE TITLE
Update Jetty Please

### ISSUE THREAD

**Issue by airinfection** [perwendel/spark#694]
9.3.13.v20161014 released, but your's is 9.3.6.201511..

**Comment by jakaarl** [comment]
Oddly enough, Jetty internals have changed enough for Spark compilation to fail. Perhaps Spark uses "internal" classes or Jetty developers don't bump their version numbers enough to signify breaking changes?

Hopefully I'll find time to look more closely into this.

**Comment by jakaarl** [comment]
Breakage was limited to one test class, didn't take much to fix. Unit tests OK and a minimal Spark test project ran without issues.

**Comment by airinfection** [comment]
rakastan sinua
