### ISSUE TITLE
[Documentation]: Instance API in documentation

### ISSUE THREAD

**Issue by GRIM2D** [perwendel/spark#713]
Instance API should be included in documentation on project's website (http://sparkjava.com/)

Currently, the only way to read about this - searching in "News" category.

**Comment by tipsy** [comment]
Mm.. this is on purpose. Initially Per was not a big fan of the instance API, and wanted to only promote one way of doing things. Have you changed your mind @perwendel ?

**Comment by tipsy** [comment]
Closing this.
