### ISSUE TITLE
Spark.after not being called when there is an exception or halt is called

### ISSUE THREAD

**Issue by javiercanillas** [perwendel/spark#715]
Hey guys, You really have a nice API in here, congratulations.

I have been working with it and I found out that the filters to handle "after" actions are not being invoked after an exception arise on the real method. Also this happens when you call Spark.halt() or any other of its overrides. 

Even though it might not seem like a bug from the definition of "after" I think it would be nice to have some sort of after(path,(e,req,res)) to be able to handle something after a method was called and executed, despite if it ends in an exception or in a halt.

To reproduce this behavior just follow this code:

> Spark.get("/hello", (req,res) -> "hello you!");
> Spark.get("/throw", (req,res) -> { throw new RuntimeException("Ouch!"); });
> Spark.before("/halt/*", (req,res) -> { Spark.halt(); });
> Spark.before("/", (req,res) -> System.out.println("before"));
> Spark.after("/", (req,res) -> System.out.println("after"));

So if you call "/hello" you will get as a response "Hello you!" and you will see in console something like:

> before
> after

If you call "/throw", you will end up with an exception in your logs, but in your console you will only find:

> before

(No after is called, but if you register any exception handler it will get fired up).

And the last one, if you call "/halt", no error in logs, only a 404 or something is returned and in the console you will see only:

> before

Nothing else.

Hope you understand this post. (And sorry for the length).
Javier.

**Comment by MouettE-SC** [comment]
There is already PR #546 for that and issues #195 #324

**Comment by javiercanillas** [comment]
Thanks! At least I'm not the only one. Any ideas when it might be released?

**Comment by MouettE-SC** [comment]
PR has been merged, this issues can be closed now.

**Comment by tipsy** [comment]
@MouettE-SC Thanks!
