### ISSUE TITLE
Javadoc hosting?

### ISSUE THREAD

**Issue by keirlawson** [perwendel/spark#716]
I'd find it handy to have the latest javadoc of Spark hosted somewhere for quick reference rather than having to generate it myself.

**Comment by SirWellington** [comment]
Check it
---
http://javadoc.io/doc/com.sparkjava/spark-core/2.5.3

**Comment by keirlawson** [comment]
Ah fantastic, it would be good to mention this in the javadoc section of the documentation

**Comment by sgwerder** [comment]
You could host it with Java 9 and get a searchbar.

**Comment by tipsy** [comment]
Added link from docs
