### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by YamilBracho** [perwendel/spark#718]
Hi,
Maybe this one has nothing to deal with spark...
I built a small restfull api and try to use from an Angular app in another server.
I set in my spark code
```
after((request, response) -> {
    response.header("Content-type", "application/json"); // ;charset=utf-8
    response.header("Access-Control-Allow-Origin", "*");
    response.header("Access-Control-Allow-Headers", "X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method, Authorization");
    response.header("Access-Control-Allow-Methods", "GET, POST, OPTIONS, PUT, DELETE");
});
```

In my angular form I fill in a combo with information given by the rest service and works fine, say
this url is http://MyServer:4023/items. The combo box is filled fine.

In tha angular form I got some data and want to send this info via post to another url in the same restfull api, say  http://MyServer:4023/register and when i try to do this I got this in my javascript console

```
OPTIONS 
XHR 
http://lMyServer:4023/register [HTTP/1.1 404 Not Found 3ms]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://MyServer:4023/register. (Reason: CORS preflight channel did not succeed).
```

Any hint to solve this ?

TIA,
Yamil

**Comment by mehdone** [comment]
Adding a route to handle all options requests should fix your problem.

options("*", (req, res) -> "{}");

**Comment by jakaarl** [comment]
Check out this also: https://sparktutorials.github.io/2016/05/01/cors.html
