### ISSUE TITLE
Use of template engines with POST routes

### ISSUE THREAD

**Issue by reallinkD** [perwendel/spark#720]
At the moment, you can use template engines with GET routes, but not with POST routes.

**Comment by tipsy** [comment]
What about
```
/**
 * Map the route for HTTP POST requests
 *
 * @param path   the path
 * @param route  The route
 * @param engine the template engine
 */
public static void post(String path, TemplateViewRoute route, TemplateEngine engine) {
    getInstance().post(path, route, engine);
}
```

**Comment by tipsy** [comment]
That being said, I recommend creating a rendering-util and using the non-template-engine route.

`post("/path", (req, res) -> Util.render("templatePath", model));`
