### ISSUE TITLE
Get session data from session ID string?

### ISSUE THREAD

**Issue by jkpr** [perwendel/spark#721]
My larger problem is this: how do I associate an incoming websocket connection with a specific user that has a session id cookie. From other questions/answers I am pulling the cookie: 

    @OnWebSocketConnect
    public void onConnect(Session session) throws Exception {
        List<HttpCookie> cookies = session.getUpgradeRequest().getCookies();
        String sessionId = null;
        if (!cookies.isEmpty()) {
            // I will get the correct cookie by searching for a cookie with name JSESSIONID
            String sessionId = getJsessionId(cookies);
        }
        usernameMap.put(session, sessionId);

So now I have the session ID string. Can I get the session data by querying somehow? My session has `username` stored in it, so if I could get the session, I could connect the websocket to the username of the person who is logged in.

Is there a better way to connect the websocket connection to the session data?

I have modified the tutorial at https://sparktutorials.github.io/2015/11/08/spark-websocket-chat.html ever so slightly.

**Comment by tipsy** [comment]
Better to ask this on SO: stackoverflow.com/questions/tagged/spark-java
