### ISSUE TITLE
Post route not working

### ISSUE THREAD

**Issue by rainitesh** [perwendel/spark#728]
I came across spark framework for creating api. I am able to access the GET routes but somehow the POST route don't work for me. Am i missing something? Can someone please guide.

Thanks.

**Comment by jakaarl** [comment]
@rainitesh that certainly sounds peculiar. Please describe the steps to reproduce the problem.

**Comment by rainitesh** [comment]
@jakaarl : I am trying to run the CRUD example provided here.

`post("/books", (request, response) -> {
            System.out.println("Inside post");
            String author = request.queryParams("author");
            String title = request.queryParams("title");
            Book book = new Book(author, title);

            int id = random.nextInt(Integer.MAX_VALUE);
            books.put(String.valueOf(id), book);

            response.status(201); // 201 Created
            return id;
        });`

Once I start the spark jetty server, I am trying to access this POST route using - localhost:4567/books?author=test&title=sparktest

This does not really trigger anything at all. All the get routes work fine as expected.

Not sure if POST route requires any additional code.

**Comment by jakaarl** [comment]
@rainitesh have you checked standard out and log output, any hints there? I tried this out and it worked fine. You sure you made a proper POST request (with, say, Postman or HttpRequester tool)?

**Comment by rainitesh** [comment]
@jakaarl I am not using any tools at the moment. Running the jetty server locally so I am trying to access the route using (localhost:4567/books?author=test&title=sparktest) in my browser.

**Comment by jakaarl** [comment]
@rainitesh well unless you have an HTML form for sending a POST request, you're doing a GET - no wonder POST route doesn't get invoked!

**Comment by rainitesh** [comment]
@jakaarl I wasn't aware of that. Will give that go.
