### ISSUE TITLE
How to delete a temporary file after returning it?

### ISSUE THREAD

**Issue by dessalines** [perwendel/spark#736]
So I'm creating a very large file, and returning it with the following code:

```java
HttpServletResponse raw = res.raw();
res.header("Content-Length", String.valueOf(file.length()));
writeToServletOS(file, raw.getOutputStream());
return res.raw();
```

I have a `file.deleteOnExit();`, but unfortunately this isn't sufficient, since these temporary files are several gigabytes. How do I return a file, and delete it after its returned?

**Comment by DOFandersolsen** [comment]
Have you tried with a `try-finally` ?

```
try {
    writeToServletOS(file, raw.getOutputStream());
    return res.raw();
} finally {
    file.delete();
}
```

Otherwise move it into the writeToServletOS() so once it's done writing the OutputStream, remove the file ?

The only times finally won't be called are:

1. if you call System.exit() or
2. if the JVM crashes first
3. if there is an infinite loop in the try block
4. if the power turns off

**Comment by jakaarl** [comment]
Probably `File.deleteOnExit()`and shutdown hooks (see `Runtime.addShutdownHook()`) are not allowed enough time to delete several gigabytes. Should probably have some sort of clean up thread running in the background instead.

The suggested finally mechanism could be problematic: finally executes when the try block exits, ie. before actually returning, potentially blocking for a long time.

**Comment by dessalines** [comment]
I could close this out, because I found a way around it is to redirect the output of my command instead of building and reading a file, like so:
```java
{
ProcessBuilder pb = new ProcessBuilder("/bin/bash", "-c", "my command with output");

final Process process = pb.start();
writeToServletOS(process.getInputStream(), res.raw().getOutputStream());
process.waitFor();

return res.raw();
}

private static void writeToServletOS(InputStream is, OutputStream os) throws IOException {

        byte[] buffer = new byte[1024];
        int bytesRead = 0;

        while ((bytesRead = is.read(buffer)) != -1) {
            os.write(buffer, 0, bytesRead);
        }

        is.close();
        os.flush();
        os.close();

}
```
