### ISSUE TITLE
Prevent JVM shutdown on closing Spark

### ISSUE THREAD

**Issue by ChristianSchuit** [perwendel/spark#737]
Hi all,

I run my Spark application embedded within an application platform. At times, I need to stop and start the Spark application *without* shutting down the JVM and thus the application server hosting the application. When using `Spark.stop()`, the complete JVM shuts down.

Is there a way to shutdown or *recycle* a Spark instance without shutting down the JVM?

Many thanks, Chris Schuit

**Comment by ph-hs** [comment]
For automated functional testing cycles too, spark may be stopped/restarted many times in one testsuite. I agree with @ChristianSchuit that SparkJava shouldn't System.exit()

```
$ ack "System\.exit"
src/main/java/spark/embeddedserver/jetty/EmbeddedJettyServer.java
134:            System.exit(100);
152:            System.exit(100); // NOSONAR
```

**Comment by jakaarl** [comment]
Totally agree on not calling `System.exit()`. But changing this behaviour might be quite a big surprise to users. Of course, running in embedded mode should ideally terminate normally after the server is shut down. Judging from a quick look at the sources, this would require big changes to how the server is started and stopped, and potentially complicate the API.

**Comment by DOFandersolsen** [comment]
Note: I am assuming a lot here, based on my own environment so please dont be upset if my advice doesn't work

**Embedded**
If you are running your spark-server in an embedded .jar file, you should be able to find the process that is running the .jar and kill it

```bash
ps aux | grep "<filename.jar>"
# Returns:
user      22350  0.1  7.8 4710636 476424 ?      Sl   05:45   0:50 java -jar /home/user/current.jar
# Kill it with the PID:
kill 22350
```

This should not affect anything other Java process as they will be running in their own processes with their own instance of the JVM

**Application Server**
I dont know which application server you're using, but I know that Tomcat can stop individual applications through the management interface without stopping Tomcat or other hosted applications.

See: 
https://tomcat.apache.org/tomcat-7.0-doc/manager-howto.html#Stop_an_Existing_Applicationhttps://tomcat.apache.org/tomcat-7.0-doc/manager-howto.html#Start_an_Existing_Application

**Comment by tipsy** [comment]
I think this would be too big a change for 2.X, maybe in 3.
