### ISSUE TITLE
externalStaticFileLocation forces browser downloads of files since 2.5.4

### ISSUE THREAD

**Issue by toni07** [perwendel/spark#739]
Hi, I previously used the 2.5 version with this code: 
`externalStaticFileLocation("src/main/resources/public/");`

I have an "index.htm" file in src/main/resources/public/, and with the 2.5 version I could see my html page in a browser. When I switch to the 2.5.4 version, the browser forces me to download the html page, thus I can no longer see it.

I did not check the header of the HTTP response, but I suppose it is something like "Content-Description: File Transfer".

Cheers and thanks for this great framework!

**Comment by tipsy** [comment]
Maybe not related, but `src/main/resources` should be `staticFiles.location()` not  `staticFiles.externalLocation()` ?

**Comment by toni07** [comment]
This is the same problem with staticFiles.location().
The header of the server response (content-type) is: "application/octet-stream".
