### ISSUE TITLE
basic spark docs do not mention concurrency model

### ISSUE THREAD

**Issue by ORESoftware** [perwendel/spark#740]
I remember filing an issue like this a long time ago

I first discovered this project after I read about Akka. I have always been under the impression that this project uses actors for concurrency, instead of the standard thread-per-request server model.

where can I read about how servers written with Spark handle concurrency? thanks!

**Comment by tipsy** [comment]
Spark blocks. Check out #549.

**Comment by the1mills** [comment]
Thanks for the info, I had been waiting for a response on this for so long.

**Comment by the1mills** [comment]
I originally had an identical question and I had to open a new issue - the ultimate issue is that the docs do not mention the concurrency model.
