### ISSUE TITLE
stop service gracefully

### ISSUE THREAD

**Issue by zjiash** [perwendel/spark#741]
Is there any method to stop the service gracefully when I need to restart or redeploy the web service?
thanks.

**Comment by zjiash** [comment]
Is there anybody encountered a similar problem?
thanks.

**Comment by jakaarl** [comment]
Have you checked out this: http://sparkjava.com/documentation.html#stopping-the-server

Also, whether you run Spark in embedded mode or in a servlet container makes all the difference here.

**Comment by zjiash** [comment]
@jakaarl 
Thanks for your response.
I run my Spark in embedded mode.
I try to use `stop()` method to stop the application but all requests being in processing fail. I want the service stops after in-progress requests finished.

**Comment by jakaarl** [comment]
I guess Jetty's `Server.stop()` by default does that. Perhaps we should set a modest default time-out (a couple of seconds?), or allow the end-user to set one and default to current behaviour?

**Comment by zjiash** [comment]
@jakaarl 

I test `stop()` with the follow codes. 
I first request with `/hello/3000` and then immediately request with `/stop`.
I expect to receive `Hello: 3000` response but the server has already shut down and I get `ERR_CONNECTION_REFUSED `.
In real application, we expect the server can finish all in-process requests (at the same time stop receiving new requests) before exiting.
 
```
        get("/stop", (request, response) -> {
            stop();
            return "stopped!";
        });

        get("/hello/:time", (request, response) -> {
            int time = Integer.parseInt(request.params(":time"));
            Thread.sleep(time);
            return "Hello: " + time;
        });
```

Thanks.
