### ISSUE TITLE
Create a TodoBackend implementation using Spark

### ISSUE THREAD

**Issue by moredip** [perwendel/spark#746]
Hi,

I'm a curator for [todobackend.com](http://todobackend.com), a community resource showing examples of how to build the same simple HTTP API using different frameworks. We'd love to get a Spark implementation contributed - in fact we have an [issue filed](https://github.com/TodoBackend/todo-backend-site/issues/66) for it!

Creating a todobackend implementation usually only takes a hour or two for someone experienced in the framework they're using. There's lots more information about how to do it on the todobackend site [here](http://todobackend.com/contribute.html).

**Comment by jakaarl** [comment]
Checked the contribution guidelines and investigated a little - this could come in handy wrt. CORS:
https://sparktutorials.github.io/2016/05/01/cors.html

**Comment by moredip** [comment]
I ended up building [my own implementation](https://github.com/moredip/todobackend-spark).

This was my first time using Spark, so I probably didn't do everything in the nicest way. Would love feedback.
