### ISSUE TITLE
sparkjava with templates

### ISSUE THREAD

**Issue by anxiaoyi** [perwendel/spark#748]
After I add templates dependency to `pom.xml`:

```xml
<dependency>
  <groupId>com.sparkjava</groupId>
  <artifactId>spark-template-freemarker</artifactId>
  <version>2.3</version>
</dependency>
```

So far, I want to know where should I put `hello.ftl` to which folders ? 

```
src/main/resources/hello.ftl ?
```

But, This path not working. Should I add the code ?

```java
FreeMarkerEngine freeMarkerEngine = new FreeMarkerEngine();
Configuration freeMarkerConfiguration = new Configuration();
freeMarkerConfiguration.setTemplateLoader(new ClassTemplateLoader(App.class, "/"));
freeMarkerEngine.setConfiguration(freeMarkerConfiguration);
```

After specified the public resource folder, How to config the templates path ? This problem really annoyed me.

```
if (LOCAL) {
    String projectDir = System.getProperty("user.dir");
    String staticDir = "/src/main/resources/public";
    Spark.staticFiles.externalLocation(projectDir + staticDir);
} else {
    Spark.staticFiles.location("/public");
}
```

Should I put the template to 

```java
src/main/resources/public/hello.ftl ?
```

Should I configure freemarker to :

```java
freeMarkerConfiguration.setTemplateLoader(new ClassTemplateLoader(App.class, "/public"));
```

But It still dit not work ... How to config freemarkder, and which folder should I put the templates to?

**Comment by tipsy** [comment]
Have a look at the example: https://github.com/perwendel/spark-template-engines/tree/master/spark-template-freemarker/src/test
