### ISSUE TITLE
Halting inside an exception handler causes a 500

### ISSUE THREAD

**Issue by pedromss** [perwendel/spark#749]
Using Spark Java 2.5, Java 8.

Recently trying the exception mapping feature. However when I `halt` inside the exception mapper the server returns a 500 probably because that exception will remain uncatched.

I'm forced to do:

```java
res.status(errorCode);
res.body(myErrorBody);
```
Instead of what was intuitive for me:
```java
halt(errorCode, myErrorBody); // causes a 500
```

If  you were aware of this and this is how it is intended to work close the issue, but please add a disclaimer to the documentation.

**Comment by tipsy** [comment]
If you're mapping an exception, execution has already been 'halted', so it doesn't make sense to call halt. `halt()` just throws an exception.

Docs say: 
```
Halting
To immediately stop a request within a filter or route
```

I think this should be clear? Closing now, feel free to keep commenting if you want to suggest an improvement.
