### ISSUE TITLE
Default ResponseTransformer for route pattern

### ISSUE THREAD

**Issue by SirBraneDamuj** [perwendel/spark#755]
I know how to use `ResponseTransformer` for individual routes, but it would be nice if I could specify that a given transformer should be used for all routes under a given pattern.

For example, all of my endpoints under the pattern `/api/*` use my `JsonTransformer`. Specifying that as an argument into each route seems redundant. I would prefer to use some kind of filter syntax to give a particular route pattern this transformer by default.

**Comment by tipsy** [comment]
Hi @SirBraneDamuj,

This is interesting to me. I want to get rid of the ResponseTransformer (and the similar concept, ViewRoute, as described in #513). Could you explain how you're using it/how you want to use it? 
If you currently do 

```
get("/hello", "application/json", (req, res) -> {
    return new MyMessage("Hello World");
}, new JsonTransformer());
```

Why not do: 

```
get("/hello", "application/json", (req, res) -> toJson(new MyMessage("Hello World")));
```

Anyway! Is your wish to do:

```
get("/api/hello", (req, res) -> new MyMessage("Hello Api"));
responseTransformer("/api", "application/json", gson::toJson);
```
?

**Comment by SirBraneDamuj** [comment]
I was already doing the second thing, but I don't find it much different than using the response transformer. The third thing is exactly what I'm thinking of.

**Comment by tipsy** [comment]
> The third thing is exactly what I'm thinking of. I could even imagine it being supported by the RouteGroups (Spark.path)

If we can catch the the response before it's stringified, creating a 
`responseTransformer(path, acceptType, transformer)` method should be pretty simple, and it would work with `path()`. I'll have a look.

**Comment by tipsy** [comment]
Update: Seemed simple enough, adding to v3 wishlist.

**Comment by tipsy** [comment]
Added to v3 wishlish
