### ISSUE TITLE
QueryParams doesn't seem to work 

### ISSUE THREAD

**Issue by AlexisVisco** [perwendel/spark#756]
Hello I think there are some problems with the data retrieved in post. 

`[17:47:08 INFO]: ------WebKitFormBoundaryox489tCMjCKXHvQN
Content-Disposition: form-data; name="uuid"

ba804244-3406-4d0e-9e80-628513ac930b
------WebKitFormBoundaryox489tCMjCKXHvQN
Content-Disposition: form-data; name="reason"

Tu as Ã©tÃ© kick
------WebKitFormBoundaryox489tCMjCKXHvQN--

[17:47:08 INFO]: executed
[17:47:08 INFO]: qparams null`

http://i.imgur.com/LSTOMyy.png

**Comment by eHattori** [comment]
Whats is your router path??
