### ISSUE TITLE
Allow to set cookie domain

### ISSUE THREAD

**Issue by sebaes** [perwendel/spark#757]
"spark.Response" class allows to set most of the "javax.servlet.http.Cookie attributes", but not domain.
The method in Response:
public void cookie(String path, String name, String value, int maxAge, boolean secured, boolean httpOnly)
Should be extended with a "String domain".
This is standard in the Cookie class and would be a useful addition.

**Comment by MouettE-SC** [comment]
That's a simple enough modification, I've created PR #758 . I think it would be a good idea too

**Comment by sebaes** [comment]
Thank you for your quick fix!.
