### ISSUE TITLE
Cannot set httpOnly and secure flag

### ISSUE THREAD

**Issue by nmarquesantos** [perwendel/spark#759]
I was just trying to setup a simple app to check some cookie logic.

What I want is a cookie that is both secure and http only.

Using the latest version of spark (2.5.4 at the time of this writing), I always get a null pointer exception.

This line throws a NullPointerException:
` rs.cookie("access-token", "test test", 100, true, true);`

While this one does not throw and I get a successful response:
` rs.cookie("access-token", "test test", 100, true);`

By using the debugging tools, it seems the **response** attribute inside the **Response** class is null when I call the first method.

It's throwing an exception on the last line of this method, whe trying to add the cookie:

```
public void cookie(String path, String name, String value, int maxAge, boolean secured, boolean httpOnly) {
        Cookie cookie = new Cookie(name, value);
        cookie.setPath(path);
        cookie.setMaxAge(maxAge);
        cookie.setSecure(secured);
        cookie.setHttpOnly(httpOnly);
        response.addCookie(cookie);
    }
```

Gist -> https://gist.github.com/nmarquesantos/05f74013313285b82513d9f2e129dc24

**Comment by roqmarcelo** [comment]
I tried to reproduce the error using the version 2.5.5 and it works fine using your simple example.

Do you have any other information that can help ? Or maybe you should upgrade your version an try aganin.
