### ISSUE TITLE
Consider using retrofit.converter and retrofit.mimetype packages

### ISSUE THREAD

**Issue by heuermh** [perwendel/spark#76]
I have recently used retrofit

http://square.github.io/retrofit/

on a couple of client-side projects and like its APIs, in particular the converter

http://square.github.io/retrofit/javadoc/retrofit/converter/package-summary.html

and mimetype packages

http://square.github.io/retrofit/javadoc/retrofit/mime/package-summary.html

I wonder if it might be possible to reuse these on the server side in spark for aid in implementing the newly added transform and template features.

**Comment by tipsy** [comment]
Seems outdated. Let me know if I'm wrong.

**Comment by heuermh** [comment]
Fine to close, thanks.
