### ISSUE TITLE
visit static resources file from jar

### ISSUE THREAD

**Issue by anxiaoyi** [perwendel/spark#768]
I write a small project in Eclipse, everything works well when I press the run button, However, I want to deploy this App to my own ubuntu server, So I export my project to a Runnable Jar, all static resources are packaged into the jar files:

![screenshot from 2017-02-11 22-50-32](https://cloud.githubusercontent.com/assets/4382796/22854577/a4073332-f0ac-11e6-93a5-f6415f784069.png)

finally, I got two files:

![image](https://cloud.githubusercontent.com/assets/4382796/22854589/e14b76e0-f0ac-11e6-8f7b-05f632cb21b5.png)

This is what inside app.jar:

![image](https://cloud.githubusercontent.com/assets/4382796/22854592/079f3110-f0ad-11e6-9bf6-aa67701d5aaf.png)

All resources that I need are copied to the folder resources in app.jar, later, I run app by type command:

```bash
java -jar app.jar
```

the server starts running, everything gets OK!

But immediately I realized that I cannot visit any resources I need, and the page writes "Internel Server Error", who can help me how to solve this problem ?

**Comment by toddknapek** [comment]
Have you set the staticFileLocation() ?

If you make a folder called public in your resources folder, you would set that up like :

staticFileLocation("/public");

Also, have you defined the port that you would like the application to serve on?

**Comment by anxiaoyi** [comment]
@knapekt Hello, I had already write the code:

```java
private static final String RESOURCE_FOLDER = "/public/";
if (LOCAL) {
    String projectDir = System.getProperty("user.dir");
    String staticDir = "/src/main/resources" + RESOURCE_FOLDER;
    Spark.staticFiles.externalLocation(projectDir + staticDir);
} else {
    Spark.staticFiles.location(RESOURCE_FOLDER);
}
```

I also defined the port

**Comment by knapekt** [comment]
Interesting.  The only thing I had to do was : 

staticFileLocation("/public");

Works locally as well as when it's deployed.  Maybe the trailing slash isn't necessary?
