### ISSUE TITLE
https example requires port to be defined in the url to work

### ISSUE THREAD

**Issue by knapekt** [perwendel/spark#769]
Using the example at : https://github.com/tipsy/spark-ssl

if I set the port to 80, and try to go to https://localhost/secureHello it doesn't work.  However, if I go to https://localhost:80/secureHello, I get the expected return.

I'm trying to use this on an application I am writing, I have purchased SSL certificates from SSL.com, and generated the java keystore.  If I don't implement the secure method, I can access the site fine.  When I implement the secure method, it gives me the error : 

"The xxxx page isn't working

xxx didn't send any data.

ERR_EMPTY_RESPONSE"

It's entirely possible I built the keystore wrong, I'm fairly certain what I did is correct, but I'm new with this security stuff.

**Comment by cassman42** [comment]
Why are you trying to run SSL on the pre-defined port for non-ssl traffic?
the service https runs by default on port 443. Why not just use the normal conventions?

**Comment by knapekt** [comment]
I didn't do a very good job of explaining things.

I define port(80) so my application will listen on the default http port.

If I don't use the secure(keystore, password, null, null) method, I can connect as expected on port 80.

When I use the secure method, the following happens : 

localhost - I get an empty response.  'localhost didn't send any data'  the same happens when I try to access the domain from a browser running on another machine. ERR_EMPTY_RESPONSE
localhost:443 - the site refuses to connect.  ERR_CONNECTION_REFUSED
localhost:80 - empty response again
if I use https://localhost:80, it will connect and work, but the connection is not secure, obviously.
if I use https://localhost:443, it redirects me to a google search for https

**Comment by cassman42** [comment]
OK lets start again.
1) don't pay for SSL certs go to https://letsencrypt.org/ and get it for free 
2) Are you trying to make your site run https ?

If you are calling port(80) you are telling the server to run on port 80. What you do on the port and what by convention is done on that port are 2 different things.

If you are doing 
port(80);
secure(keystore, password, null, null);

then you will be running https ssl encrypted traffic over port 80. 
ie https://localhost:80/ - whilst *WEIRD* will work fine no issues & be secure.
you might want to run it on the *NORMAL* port 443 for https traffic then 
https://localhost/ should go to your server & be encrypted. 

when you go to the  https://localhost:80  url what does your browser tell you 
does the secure connection light go on or ?

> if I use https://localhost:443, it redirects me to a google search for https

That's cos your server is not listening on that port !
What browser & OS are you using?

**Comment by knapekt** [comment]
I've used letsencrypt on other projects, unfortunately, I'm limited to using a windows host for this project, which makes utilizing letsencrypt challenging, especially since I am not using IIS.

And yes, trying to make the site run https, as there is login information that's being passed.

No matter how I set the port up, the browser never indicates a secure status.  

I did change the port definition to 443, and I have to enter the url specifically as https://localhost:443/index.html to get it to serve something up - anything else, and it gives me the empty return error again.  Even when I specifically craft the url this way, the browser is indicating an insecure connection.  This also only works on the local host, if I try to connect the same way using the domain name instead of localhost from another machine, it never connects.  Something is definitely goofy.

I'm going to try setting a stand-alone jetty instance up and see if I can get it to securely connect, to potentially rule out something with the underlying jetty instance in Spark.

Thanks for your help with this!

**Comment by cassman42** [comment]
Do you have either curl or openssl available to you ?
Try to use open ssl to validate that the SSL is "correct" 
openssl s_client -showcerts -connect www.domain.com:443
send us what it says !

**Comment by orcapt** [comment]
I've got this problem too

**Comment by cassman42** [comment]
orcapt - what is the url you are calling? what certificate did you register? have you installed the complete chain ?
