### ISSUE TITLE
Static files not served

### ISSUE THREAD

**Issue by livingcreative** [perwendel/spark#777]
I have this simple code just to try static files:

```
package app;

import static spark.Spark.init;
import static spark.Spark.staticFiles;

public class Application {

	public static void main(String[] args) {
		staticFiles.location("/public"); 
		init();
	}

}
```

I have all files copied to required paths (at least I can return file contents when I do implicit get mapping ans read file "manually"). And when I do a request from browser to any public file I get 404 error and the following message in a console:
The requested route [/index.htm] has not been mapped in Spark for Accept: [text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8]

What I did wrong? If I need to map any path I can get by hand, what is the purpose of staticFiles.location call then?

**Comment by tipsy** [comment]
From docs:
```
// root is 'src/main/resources', so put files in 'src/main/resources/public'
staticFiles.location("/public"); // Static files
```

**Comment by livingcreative** [comment]
This is exactly what I did. Relative to which path this location is?
I have following dir tree inside my target directory:
target
+----classes
+----public     <- my static files went here (copied during the build)

**Comment by livingcreative** [comment]
By trial and error I found out that I need to use `staticFiles.externalLocation` instead of `staticFiles.location`, because my `public` resources folder isn't copied into "class path". This is seems to be my lack of knowledge about java development itself. Anyway, thanks for help.
