### ISSUE TITLE
Static files inside fat-jar

### ISSUE THREAD

**Issue by vertex-github** [perwendel/spark#779]
We're packaging our app up with the Capsule plugin as a fat jar (all dependencies included).  We've configured `staticFileLocation( "/docs" );` but no files are being returned.  When run within our IDE, we can serve static files just fine from our src/main/resources/docs/ folder.  Ive confirmed that the far-jar has all the .html docs present in the compiled JAR under classpath of /docs.

Should we be able to serve static content from within a fat-jar?

Contents of app-jar within the larger fat-jar:
```
     0 Tue Feb 21 11:02:14 EST 2017 docs/
   269 Tue Feb 21 11:18:14 EST 2017 build.properties
   358 Tue Feb 21 11:18:14 EST 2017 docs/index.xml
  2878 Tue Feb 21 11:18:14 EST 2017 log4j.xml
     0 Tue Feb 21 11:18:16 EST 2017 META-INF/maven/
```

**Comment by tipsy** [comment]
Yes, it should work, that's how I deploy my apps. I don't have any `.html` files though (only js/css/images). In the snippet you pasted it says `xml` though, not `html`. Could that be it?

**Comment by vertex-github** [comment]
Thanks for pointing that glaringly obvious issue out.
