### ISSUE TITLE
Cookies with path (and possibly other attributes) can't be deleted

### ISSUE THREAD

**Issue by stevemcleod** [perwendel/spark#780]
Set a cookie as such:

`response.cookie("/", "name", "value", 36000, false, false);`

Now try to remove it (in a subsequent request):

`response.removeCookie("name");`

This doesn't work, because a cookie in the underlying HttpServletRequest seems to require all attributes to match in order to remove the cookie.

I propose adding at a minimum:

`response.removeCookie(String path, String name);`

I'm happy to implement this and make a pull request as my first contribution. Can any of the current contributors comment on my proposal to the problem?

**Comment by tipsy** [comment]
I've run into this problem myself, a PR would be great.

**Comment by tipsy** [comment]
@stevemcleod ping.

**Comment by stevemcleod** [comment]
I got a working solution done to this problem in February, but ran into problems with adding appropriate tests. IIRC, to get the unit tests done, I was going to need to learn more about how to use the Apache HTTP client with path-specific cookies.

I'll see if I can get this done this evening.

**Comment by tipsy** [comment]
Great!

**Comment by stevemcleod** [comment]
I've made a pull request with the fix.

**Comment by tipsy** [comment]
Thanks. Will merge it once I find out why travis is so angry.
