### ISSUE TITLE
Spark won't compile with Java 9, due to use of sun.reflect.ConstantPool

### ISSUE THREAD

**Issue by stevemcleod** [perwendel/spark#785]
When I forked Spark, I inadvertently tried to run with Java 9. It seems there is one use of a class not available in Java 9. 

```
/Users/steve/code/spark/src/main/java/spark/route/RouteOverview.java
Error:(29, 19) java: package sun.reflect does not exist
Error:(146, 13) java: cannot find symbol
  symbol:   class ConstantPool
  location: class spark.route.RouteOverview
```

There doesn't seem to be a simple solution to this, though.

**Comment by tipsy** [comment]
Well, the good news is that the RouteOverview is not an important feature. Does Java9 provide us with another way of doing reflection? If not, we will simply remove the route-overview.

**Comment by stevemcleod** [comment]
It seems the problematic code is only used by routes defined by lambdas. Lambdas + reflections seem to be murky in Java.

Some interesting things going on here in general in this problem.

I found this in the pom.xml:
    
    <exclude>**/spark/route/RouteOverviewTest.java</exclude>
    

RouteOverviewTest.java fails on my local machine (Mac, Java 1.8.0_111)

It seems the RouteOverview functionality has been failing for me and I didn't know. For lambda routes I see this in the route overview HTML:

    get	any	/lambdatest	:: (method reference)

Furthermore, the code that won't compile in Java 9 is only called for routes that are lambdas.

As it hasn't been working reliably, breaks the maven build without special attention, and is a problem in Java 9, I suggest dumbing down the handling of lambdas. I'll submit a pull request later today.

**Comment by stevemcleod** [comment]
Issue fixed by removing RouteOverview
