### ISSUE TITLE
Dependency Injection with Spark

### ISSUE THREAD

**Issue by eHattori** [perwendel/spark#786]
Hello Dear,

Congrats by make this exceptional microframework.

I liked so much

Do you have some plan about DI native in Spark project?

**Comment by tipsy** [comment]
Thanks! No plans for DI, we're trying to keep Spark as simple and small as possible.

**Comment by ramiresnas** [comment]
Hello!
Jetty 9, already support for CDI, therefore I guess that this feature will not make spark bigger.
