### ISSUE TITLE
before() not being called when inside path()

### ISSUE THREAD

**Issue by livingcreative** [perwendel/spark#804]
I can't get following code working as I understand it supposed to work (this is actually straight from documentation page)

```java
path("/api", () -> {
    before((q, a) -> { System.out.println("API REQUEST"); }); // I don't see this in log!
    post("/login", () -> {
        // this is called ok
    });
    post("/logout", () -> {
        // this is called ok
    });
});
```

I do POST requests to `/api/login` and `/api/logout` and they work just as expected, I see the result,
but I don't see "API REQUEST" in my console log. I put breakpoint there and it also not being hit.

I'm using version 2.5.5

What am I missing here?

**Comment by tipsy** [comment]
You need to specify the path when using before filters inside `path()`. I'll update the docs.
Ex: `before("/*", (q, a) -> { System.out.println("API REQUEST"); });`

**Comment by livingcreative** [comment]
Great, with the `/*` filter string it works! Thank you!

**Comment by rikukissa** [comment]
Hi! It seems that `before` isn't executed inside of a path block when user requests the index route of said path.

```java
path("/users", () -> {
  before("/*", Request::requiresAuthentication);

  get("", (req, res) -> {
    // before not executed
  });

  get("/me", (req, res) -> {
    // before executed
  });
```
It kind of makes sense, if `/*` requires you to have something after the slash, but currently the only way I managed to solve this was by doing 

```
before("", Request::requiresAuthentication);
before("/*", Request::requiresAuthentication);
```

Suggestions?

**Comment by tipsy** [comment]
Adding a trailing slash could fix it: 
```
path("/users", () -> {

    before("/*", Request::requiresAuthentication);

    get("/", (req, res) -> {
    // before should be executed
    });

    get("/me", (req, res) -> {
      // before executed
    });

});
```
But maybe this is not an option?

**Comment by rikukissa** [comment]
Thanks for the quick reply! It seems to work, but the thing that bothers me is the fact that I have to have a slash after the url 

`http://localhost:4567/users` vs `http://localhost:4567/users/`

For some reason I would assume there's no difference. At least http frameworks like [Express](https://github.com/expressjs/express) aren't making any distinction between the two formats. Is there a reasoning behind this or could this be something we might be able to change?

**Comment by tipsy** [comment]
Well, they are two separate URLs. Some frameworks choose to ignore this, we don't. As you saw, it's been discussed before, and we decided to leave how to handle this up to users. We could provide a method, something like `service.stripTrailingSlashes` or `service.addTrailingSlashes`, but we don't want to make either of those active by default.

**Comment by rikukissa** [comment]
Yeah, you're right. Interpreting them as the same url would definitely add more "magic" to this framework and could potentially also be confusing for some users.

Thanks for taking the time to answer my question!
