### ISSUE TITLE
Apache Shiro & SparkJava Embedded Jetty mode - Cannot configure Jetty

### ISSUE THREAD

**Issue by nilankanayana** [perwendel/spark#810]
My project uses stand-alone SparkJava (Jetty included).
I wanted to use Apache Shiro.
There is no web.xml for this project.
When I used shiro with stand-alone ini configuration, it was behaving in a weird manner, such as Subject.getSubject() calls returning different objects resulting in need of duplicated authentications.

The solution is to configure shiro in web mode.
But apparently there is no way to configure embedded jetty with SparkJava.

Needs support.

Thanks for all the great work done.
BR
Nilanka

**Comment by tipsy** [comment]
#813 was just merged, allowing you to customize jetty.
