### ISSUE TITLE
Jetty bug zombies Spark eventually. Upgrading Jetty fixes the problem. 

### ISSUE THREAD

**Issue by FrankHassanabad** [perwendel/spark#815]
We found an issue in production where the current version of Jetty used by Spark can consume and zombie all threads in the thread-pool causing a Spark server to eventually become a zombie and stop accepting requests until the process is restarted.

Details of the Jetty bug are here:
https://github.com/eclipse/jetty.project/issues/355
https://github.com/eclipse/jetty.project/commit/1eeecdaee515daf4e4fdf41e80d2b61678ba537d

Testing is basically you _SLAM_ spark with so many connection attempts it cannot keep up, then as disconnects and rejects start occurring your process becomes a zombie.

We manually upgraded spark's Jetty to 9.3.17v20170317:
https://github.com/LogRhythm/spark/pull/2/files

but had to comment out a few of the tests due to what looks like internal package name changes. 

Afterwards, heavy testing shows that Jetty does not zombie.

**Comment by perwendel** [comment]
Jetty has been bumped to higher version.
