### ISSUE TITLE
Can spark read values from yml or properties from files like spring ?

### ISSUE THREAD

**Issue by Galleria** [perwendel/spark#817]
Does Spark have a feature for reading values from files like spring ? 

Thanks,

**Comment by nitincoded** [comment]
I believe it doesn't as I couldn't find anything in the documentation or any references to java.util.Properties or the extension ".yml" through GitHub's search, but it's simple enough to read from one's own properties file and to call Spark's methods. For example, setting the HTTP port simply involves calling the port() method, while most IDEs automagically add the static import needed to get it to work.

For the one-person development teams that I'm working with, Spark is perfect the way it is and hardcoding everything into a config class doesn't seem like too much of a bother, but I can imagine different developers within a team wanting to [run the server on different TCP ports](http://turnoff.us/image/en/apache-vs-nginx.png). If somebody did build a config helper class, it would be nice if it could provide the ability to load different config based on hostname or an environment file so we can have a single copy of the config file residing in source control (this could spark yet another debate over whether or not the config should be in our source control). You've now set me on the path to build something fun this Sunday!

**Comment by daybologic** [comment]
What you're talking about it best handled by something like Puppet, which can write out different values from LDAP, depending on the environment.  It isn't a project specific problem IMHO.

**Comment by tipsy** [comment]
This is outside of the project scope, use something like [args4j](http://args4j.kohsuke.org/)?
