### ISSUE TITLE
Spark.port() returns 0 instead of the current port when you initialized the port with 0

### ISSUE THREAD

**Issue by agabi10** [perwendel/spark#830]
I wanted to use one available port for the Spark server (and I don't care which one is used as long as it doesn't take one which is already in use). The problem is that after initialization I need it to load a browser tab with the main page. To make that I need to know the port to which the server is listening, but the Spark.port() function always returns 0 instead of the port it is using if I initialize this way.

If I set the port to a given number it works as expected (as long as it is not in use), but it would be nice fixing the Spark.port() function to return the used port.

The version of Spark I'm using is the 2.5.5

**Comment by jakaarl** [comment]
See #714 .

**Comment by agabi10** [comment]
Then it doesn't make sense having a Spark.port() function at all. It's documentation says:
> Retrieves the port that Spark is listening on.
If it doesn't return the correct port number until the server stops it's execution it is completely useless. If it's going to stay there locked at least it should set the port number in any other way, like calling to a function to set the port value wherever Spark stores it.

**Comment by jakaarl** [comment]
I'm not in the know. @perwendel or @tipsy any input?

**Comment by tipsy** [comment]
We're aiming for *pretty soon*.
