### ISSUE TITLE
Any way to unit test websocket connection?

### ISSUE THREAD

**Issue by dessalines** [perwendel/spark#837]
I found this for testing spark: https://github.com/despegar/spark-test/ , but it seems only to work for GET, POST, etc.

Any way to test a websocket connection through spark?

**Comment by jakaarl** [comment]
Have you looked into any Java websocket clients?
Jetty seems to have one: https://www.eclipse.org/jetty/documentation/9.4.x/jetty-websocket-client-api.html
Also, a quick googling turned up Turys, which also AFAIK has a client: https://tyrus.java.net/
