### ISSUE TITLE
How to release resources (like database connection) when stopping Spark based app

### ISSUE THREAD

**Issue by feg624** [perwendel/spark#839]
Hi: I've been looking for a way to release resources, for example closing a database connection, when stoping an Spark based application/microservice.

I couldn't find any example on how to do this, as I understand the embedded Jetty runs on a separate thread.

Any help/idea is greatly appreciated,

Franco

**Comment by kendrickwilson** [comment]
I recommend added a static helper method to the Spark class.

see https://github.com/kendrickwilson/spark/blob/master/src/main/java/spark/Spark.java

**Comment by feg624** [comment]
Thanks @kendrickwilson , going to take a look at it and see whether it works for me.
