### ISSUE TITLE
[HELP WANTED] Test out Spark 2.6

### ISSUE THREAD

**Issue by tipsy** [perwendel/spark#845]
There were a lot of changes since Spark 2.5.0, so we're doing a release candidate this time. Please try it out, build your projects, test some of the new functionality, and report any bugs. Please use the 👍  emoji at the bottom of this post if you've tested and you didn't experience any trouble.

```xml
<dependency>
    <groupId>com.sparkjava</groupId>
    <artifactId>spark-core</artifactId>
    <version>2.6.0.RC0</version>
</dependency>
```
Changes:
* Embedded Jetty is now fully configurable **(!)**
* Added `path()` method for grouping routes
* Added `afterAfter()` filter (a finally-filter that runs after everything else)
* Added `initExceptionHandler()` for overriding default behavior if Sparks fails to start
* Added error page handlers `internalServerError()`, `notFound()` and `add()` (general)
* Added `queryParamsOrDefault()` method to `Request`
* Added typeinfo to exceptions in `ExceptionMapper`s
* A lot of improvements and fixes to static file handling
  * MIME-type guessing
  * Custom headers
  * Various bugfixes
* `ExceptionMapper`s are now cleared on `stop()`
* Fixed `OutOfMemoryError` due to caching of chunked data
* Domain has been added to `cookie()`, and a bug where cookies couldn't be deleted was fixed
* Added `activeThreadCount()` to expose number of active threads
* Added `port()` method to get current port
* Add general error logging
* Added `X-Forwarded-For` support in `request.ip()`
* `Spark.halt()` now returns `HaltException` instead of `void`
* Added `QueryParamsMap.hasKey()`
* Param/splat decoding now happens after matching
* Support for multiple Spark applications in filter configuration
* A lot of other minor fixes/features have also been added.

**Comment by sandronm** [comment]
Unfortunately, #812 is still not resolved.
I will do more tests later :-)

Thank you for your job!

**Comment by wmacgyver** [comment]
tested it out on 2 small apps, as well as one on google app engine java 8 alpha runtime. so far so good.

**Comment by atomfrede** [comment]
Updated one of my apps and everything works well.

**Comment by JWGmeligMeyling** [comment]
Recently started testing against `2.6.0.RC0`. Everything seems to work so far, I'll keep you posted as my testing progresses.

**Comment by JWGmeligMeyling** [comment]
I am having this weird issue where my controller method gets called twice, once with the message body, and once with an empty body. As my controller then fails on the empty body the entire request handling fails. It seems something is not quite right with this release after all, but I am not sure what exactly triggers the second invocation on the request handler. I suppose its introduced in the afterAfter feature, but even if I disable the afterAfter filter that I've added, the issue still occurs. Will keep debugging the issue but unfortunately I have to rollback too.

**Comment by tipsy** [comment]
> I'll keep debugging the issue but unfortunately I have to rollback too.

Well, that's what release candidates are for, I guess.
Please let us know when you find out.

**Comment by kliakos** [comment]
LGTM

**Comment by hannesUlrich** [comment]
Did you delete the experimental Routeoverview?

**Comment by tipsy** [comment]
> Did you delete the experimental Routeoverview?
Yes.
