### ISSUE TITLE
Can't use SparkJava 2.6.0 with Tomcat 8.5 or Tomcat 9.0.0-M20

### ISSUE THREAD

**Issue by cpc6128** [perwendel/spark#856]
I update to new version 2.6.0 from 2.5.5 of SparkJava and but it can't start. I've got this error :

>front_1  | Caused by: java.lang.NoSuchMethodError: org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(Ljavax/servlet/ServletContext;)V
front_1  |      at org.eclipse.jetty.websocket.server.NativeWebSocketConfiguration.<init>(NativeWebSocketConfiguration.java:53)
front_1  |      at org.eclipse.jetty.websocket.server.NativeWebSocketServletContainerInitializer.getDefaultFrom(NativeWebSocketServletContainerInitializer.java:36)
front_1  |      at org.eclipse.jetty.websocket.server.NativeWebSocketServletContainerInitializer.onStartup(NativeWebSocketServletContainerInitializer.java:46)
front_1  |      at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5185)
front_1  |      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
front_1  |      ... 38 more

I use tomcat 8.5 or 9.0.0-M20 : same error.

This is my dependency tree :

>[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ workingathome ---
>[INFO] fr.codevallee:workingathome:war:1.0-SNAPSHOT
[INFO] +- javax.mail:mail:jar:1.5.0-b01:compile
[INFO] |  \- javax.activation:activation:jar:1.1:compile
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.7:compile
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.7:compile
[INFO] +- org.apache.logging.log4j:log4j-web:jar:2.7:compile
[INFO] +- org.slf4j:slf4j-simple:jar:1.7.21:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.21:compile
[INFO] +- org.springframework:spring-context:jar:4.3.8.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.3.8.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.3.8.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:4.3.8.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:4.3.8.RELEASE:compile
[INFO] +- org.springframework:spring-context-support:jar:4.3.8.RELEASE:compile
[INFO] +- org.springframework:spring-web:jar:4.3.8.RELEASE:compile
[INFO] +- org.springframework.data:spring-data-mongodb:jar:1.9.6.RELEASE:compile
[INFO] |  +- org.springframework:spring-tx:jar:4.2.9.RELEASE:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:1.12.6.RELEASE:compile
[INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.22:runtime
[INFO] +- org.mongodb:mongo-java-driver:jar:3.4.1:compile
[INFO] +- com.sparkjava:spark-core:jar:2.6.0:compile
[INFO] |  +- org.eclipse.jetty:jetty-server:jar:9.4.4.v20170414:compile
[INFO] |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:9.4.4.v20170414:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-util:jar:9.4.4.v20170414:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-io:jar:9.4.4.v20170414:compile
[INFO] |  +- org.eclipse.jetty:jetty-webapp:jar:9.4.4.v20170414:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-xml:jar:9.4.4.v20170414:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-servlet:jar:9.4.4.v20170414:compile
[INFO] |  |     \- org.eclipse.jetty:jetty-security:jar:9.4.4.v20170414:compile
[INFO] |  +- org.eclipse.jetty.websocket:websocket-server:jar:9.4.4.v20170414:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-common:jar:9.4.4.v20170414:compile
[INFO] |  |  \- org.eclipse.jetty.websocket:websocket-client:jar:9.4.4.v20170414:compile
[INFO] |  |     \- org.eclipse.jetty:jetty-client:jar:9.4.4.v20170414:compile
[INFO] |  \- org.eclipse.jetty.websocket:websocket-servlet:jar:9.4.4.v20170414:compile
[INFO] |     \- org.eclipse.jetty.websocket:websocket-api:jar:9.4.4.v20170414:compile
[INFO] +- com.qmetric:spark-authentication:jar:1.4:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] +- com.sparkjava:spark-debug-tools:jar:0.5:compile
[INFO] +- com.sparkjava:spark-template-freemarker:jar:2.5.5:compile
[INFO] |  \- org.freemarker:freemarker:jar:2.3.23:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.9.0.pr3:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.0.pr3:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0.pr3:compile
[INFO] +- org.projectlombok:lombok:jar:1.16.12:provided
[INFO] +- com.navercorp.lucy:lucy-xss:jar:1.6.3:compile
[INFO] |  \- commons-logging:commons-logging:jar:1.0.4:compile
[INFO] +- javax.json:javax.json-api:jar:1.1.0-M2:compile
[INFO] \- org.glassfish:javax.json:jar:1.1.0-M2:compile
[INFO] ------------------------------------------------------------------------
`

**Comment by xudeheng** [comment]
I meet this issue

**Comment by xudeheng** [comment]
spark 2.5.5 jetty.version is  9.3.6, spark2.6.0 jetty.version is 9.4.4 which org.eclipse.jetty.websocket.server.WebSocketServerFactory lack of init method.


spark 2.5.5
<properties>
        <java.version>1.8</java.version>
        <jetty.version>9.3.6.v20151106</jetty.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <powermock.version>1.6.4</powermock.version>
        <mockito.version>1.10.19</mockito.version>
    </properties>

spark 2.6.0
<properties>
        <java.version>1.8</java.version>
        <jetty.version>9.4.5.v20170502</jetty.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <powermock.version>1.6.4</powermock.version>
        <mockito.version>1.10.19</mockito.version>
    </properties>

**Comment by xudeheng** [comment]
jetty 9.4.4 and later can work well with Spark 2.6.0+

**Comment by xudeheng** [comment]
I think Spark teams should better append servlet container server supported version.

**Comment by cpc6128** [comment]
Oh ! I find why !!
Its because i use spark-debug-tools 0.5.
I remove it and now, it's work !
