### ISSUE TITLE
Securing post requests to the server?

### ISSUE THREAD

**Issue by SimplySerenity** [perwendel/spark#861]
I read on an older, closed, issue that the standard post request and then reading from QueryParams isn't safe for passwords? If this is true what would be a simple way of securing the request?

**Comment by tipsy** [comment]
Which issue? It should be safe, it's just that`queryParams()` has a misleading name. Params sent with a login form will be sent as request body, not as query params, and the `queryParams` method just calls the underlying `getParameters` method on the servlet request, which has access to body params.

**Comment by SimplySerenity** [comment]
It was at the bottom of this issue https://github.com/perwendel/spark/issues/389

However it seems like they were just confusing them with actual query params too. Thanks for the clarification! 

By the way I really love your structure style in your application structure tutorial.

**Comment by tipsy** [comment]
> By the way I really love your structure style in your application structure tutorial.

Thanks!
