### ISSUE TITLE
Why Spark Performed Poorly At Techempower Benchmark?

### ISSUE THREAD

**Issue by tweenietomatoes** [perwendel/spark#866]
Here, Spark got 629 points while following framework is Dropwizard with 11,395
Is there any particular reason?

https://www.techempower.com/benchmarks/

**Comment by kendrickwilson** [comment]
You have to look at the code.....

Hibernate? I saw the plain java/servlet implementation use raw JDBC.
Session Pooling? Hibernate session are destroyed after every request.....
