### ISSUE TITLE
Run configuration?

### ISSUE THREAD

**Issue by realcake** [perwendel/spark#868]
I followed the example "hello world" but I am not getting anything.
In the docs you say to "run" it, but I would like to know what specific configurations to use.

**Comment by Galleria** [comment]
did you visit site http://localhost:4567/hello after ran spark?

**Comment by tipsy** [comment]
@realcake You just run it as any other Java application, no config necessary. If you're using an IDE just right click the file and click run. If you're getting a log-warning, do this: http://sparkjava.com/documentation#how-do-i-enable-logging
