### ISSUE TITLE
Being able to remove routes at runtime

### ISSUE THREAD

**Issue by tauraamui** [perwendel/spark#869]
Hi,

I know that there have been previous issues raised regarding this, such as: #231 #277 and #356

However, the fix suggested by @travisspencer in #356 doesn't seem to be possible anymore. I do have a use case where I would like to remove routes, as in if it was being used as a base for a CMS, and a page's route was changed or a page was deleted, you would no longer want this route to be valid anymore.

I can quite happily write a fix to re-add this back in, but I was just wanting to get an idea if there are any currently suggested alternative methods for solving this. Also I don't know if the community attitude to this feature has changed and whether this would be unwelcome.

**Comment by tipsy** [comment]
Could you show us your URL structure?

**Comment by tauraamui** [comment]
What do you mean by that?

**Comment by tipsy** [comment]
I would like to understand what kind of route you need to delete. Typically you would use path-params for a CMS, like `/:pageId`, `posts/:postId`. Why do you need to declare a separate route?

**Comment by tauraamui** [comment]
Oh I see. Because part of being able to create pages I would want users to be able to specify the full route that they want. I am using path params in the format you demonstrate for a lot of things, but not this.

**Comment by tauraamui** [comment]
Is there any further consensus on this? I don't really understand why it's not a simple request to just be able to unmap/remove routes. Spark allows you to map routes to handlers, why wouldn't you be able to unmap them too? Am I missing something here?

**Comment by tipsy** [comment]
Typically people *declare* an API, creating something absolute/stateless/deterministic. Allowing route-removal gives you an API with state (which could change at any moment).
A lot of other users feel strongly about not allowing this kind of behavior, as it has huge WTF-potential if used incorrectly.

**Comment by tauraamui** [comment]
Ok, I understand that. That kind of sucks, I don't really have time to fork my own version of Spark just for this feature. I'll stick with my hacky fix for now.

**Comment by nithril** [comment]
> Typically people declare an API, creating something absolute/stateless/deterministic. Allowing route-removal gives you an API with state (which could change at any moment).

Spark is not stateless, it has routes and route can be added while the server is running. 

> A lot of other users feel strongly about not allowing this kind of behavior, as it has huge WTF-potential if used incorrectly.

Like a lot of things in fact, but it has never been a solid argument ... without arguments. Unmapping a route and not being able to access it, is definitively a kind of WTF ;)

Btw I like the irony that `Service` is final and `Routes` since 2.2 has remove method ;)

**Comment by tauraamui** [comment]
Ooh finally!
