### ISSUE TITLE
Feature request: redirect without changing browser URL

### ISSUE THREAD

**Issue by xizhang** [perwendel/spark#870]
Is there a way in Spark to redirect without changing URL?

e.g.

I want http://example.com/message show the same content as http://example.com (static files.)

Or is there  way to load the static files and return it as response?

Thank you

**Comment by tauraamui** [comment]
Yes, I believe you can just redirect to the same URI, so it would effectively refresh the page.

**Comment by tauraamui** [comment]
Do you mean provide different content but using the same address? You can just return different content as part of the response.

**Comment by xizhang** [comment]
I want to return same content for different address. The difficulty is that the content I am returning is static files, e.g.:

staticFiles.location("/public")

And I want to return the same content for:

get("/message/*", (request, response) -> {
   // return static content located at "/"
});

**Comment by tauraamui** [comment]
Why can't you just return the same static content for different addresses?

**Comment by xizhang** [comment]
Could you give me a code example? I couldn't find one in doc: http://sparkjava.com/documentation#static-files

**Comment by xizhang** [comment]
Found a solution: 

https://stackoverflow.com/questions/44401973/sparkjava-redirect-while-keeping-the-browser-url
