### ISSUE TITLE
ClassLoader Problems

### ISSUE THREAD

**Issue by jsauvain** [perwendel/spark#875]
I'm actually using Spark-Java as a RestAPI. I have developed an application which is module based, and one of these modules is my RestAPI. Because I'm using the ClassLoader of my main application, spark is actually not working on some places. 
Could you give me any advices or fix it?

**Comment by jakaarl** [comment]
@jsauvain could you elaborate? How do you manage class loaders and class paths, and what kind of problems are you having?
