### ISSUE TITLE
secure setup with IBM JVM returns "fatal error: 40: no cipher suites in common"

### ISSUE THREAD

**Issue by offerbaruch** [perwendel/spark#877]
Hi,

i have been using a spark-core-2.3 with a secure setup with IBM java for a while now, and i wanted to migrate to 2.6.0 (specifically to be able to use the client authentication feature).

when i migrated (even before i tried using the client certificates feature) i started getting: 
fatal error: 40: no cipher suites in common 

I have created a simple program that works fine on oracle/openjdk JVM, but does not work on IBM JVM with the error mentioned above.

my sample program:
	import static spark.Spark.get;
	import static spark.Spark.secure;

	public class TestSecureSpark {
	
		public static void main(String[] args) {
			System.setProperty("javax.net.debug", "all");
			secure(args[0], args[1], null, null,true);
			get("/stats", (req, res) -> {
				return "hello secure world";
			});
		}
	}

The output is in the attached file.
specifically i tried 2 versions of IBM Java.
1. IBM java on x86 64 bit on Ubuntu
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr3fp12-20160919_01(SR3 FP12))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20160915_318796 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR3_20160915_0912_B318796
JIT  - tr.r14.java.green_20160818_122998
GC   - R28_Java8_SR3_20160915_0912_B318796_CMPRSS
J9CL - 20160915_318796)
JCL - 20160914_01 based on Oracle jdk8u101-b13
2. IBM Java on z/OS (system z)
JVMJZBL1012I Java Virtual Machine created. Version information follows:                  
java version "1.8.0"                                                                     
Java(TM) SE Runtime Environment (build pmz3180sr3fp10-20160720_02 (SR3 FP10))            
IBM J9 VM (build 2.8, JRE 1.8.0 z/OS s390-31 20160719_312156 (JIT enabled, AOT enabled)  
J9VM - R28_Java8_SR3_20160719_1144_B312156                                               
JIT  - tr.r14.java_20160629_120284.01                                                    
GC   - R28_Java8_SR3_20160719_1144_B312156                                               
J9CL - 20160719_312156)                                                                  

[spark.txt](https://github.com/perwendel/spark/files/1091451/spark.txt)

can anyone figure out why this happens?
a workaround will be really nice...

**Comment by yuvalk** [comment]
here's a nice workaround you can test:
try adding -Dcom.ibm.jsse2.overrideDefaultTLS=true

https://www.ibm.com/support/knowledgecenter/en/SSYKE2_7.1.0/com.ibm.java.security.component.71.doc/security-component/jsse2Docs/matchsslcontext_tls.html
