### ISSUE TITLE
WebSocket returns 500 on handshake

### ISSUE THREAD

**Issue by lvivtotoro** [perwendel/spark#879]
So far all of my clients have logged that the server returned 500 on handshake.
This is even before the server's `@OnWebSocketConnect` method is called.

**Comment by tipsy** [comment]
Did you try following the tutorial? http://sparkjava.com/tutorials/websocket-chat

**Comment by lvivtotoro** [comment]
Did I say I was making a real-time chat app?

**Comment by tipsy** [comment]
Try following the tutorial to get a simple implementation working, or post your code here so people can have a look.

**Comment by lvivtotoro** [comment]
Here's a stripped version (does not have unrelated things) of the class:
https://gist.github.com/lvivtotoro/cc4a5abcd31c71b0cce7bf2c6e0eb234

**Comment by lvivtotoro** [comment]
Noticed the problem.  
Apparently you can't have `byte[]` as a parameter.  
I instead used `InputStream` and it worked.
