### ISSUE TITLE
There is no modular division, and Is all the routes in a main function inside?

### ISSUE THREAD

**Issue by wangdanqing** [perwendel/spark#882]
so, what happend? A main function file becomes very large. 
Whether there are plans to introduce annotations? like spring boot will be 
public static void main(){
    SpringApplication.run(this.getClass());
}

that will scanner all routes , it necessary.

**Comment by wangdanqing** [comment]
and hot deployment is very important feature

**Comment by tipsy** [comment]
No, there will never be annotations. It's not hard to modularize Spark routes though, what are you having trouble with?

**Comment by wangdanqing** [comment]
ooh,Here's the obvious problem.
that main function will comes very large.

**Comment by wangdanqing** [comment]
main function will too long for routes defined. inlet module and annotations feature to resolve this problem. while application start run, will scanner all modules that annotation's route register. this way will keep project to easily position.

**Comment by tipsy** [comment]
If you're using Spark statically you can declare routes anywhere. If you're using the instance API you can just pass the instance around and register routes on it.
