### ISSUE TITLE
EmbeddedServer method activeThreadCount not reachable through Spark

### ISSUE THREAD

**Issue by ivansanchezg** [perwendel/spark#885]
The EmbeddedServer interface declares the method activeThreadCount and the EmbeddedJettyServer which implements this interface, defines its own logic for this method. I'm interested in having this information from the embedded server, but it is not reachable through the Spark class.

Please add a method in the Service and Spark classes to call the method from the EmbeddedJettyServer.

Methods could be as followed:
Service class:
```
public synchronized int activeThreadCount() {
    if (server != null) {
        return server.activeThreadCount();
    }
    return 0;
}
```

Spark class:
```
public static int activeThreadCount() {
    return getInstance().activeThreadCount();
}
```

**Comment by tipsy** [comment]
That's odd. Make a PR and I'll merge it.

**Comment by ivansanchezg** [comment]
@tipsy Just created the [PR](https://github.com/perwendel/spark/pull/886), please take a look when you have time, thanks :)

**Comment by tipsy** [comment]
Thanks, merged!
