### ISSUE TITLE
Get the method mapped to a route

### ISSUE THREAD

**Issue by AlexK-IL** [perwendel/spark#890]
Is it possible to get the method on a before filter which is mapped to the current route?  
My aim is to annotate the method and check it before entering the method, so I can halt the request if needed.

**Comment by tipsy** [comment]
Could you elaborate a little?

**Comment by AlexK-IL** [comment]
Closing since I don't need it anymore.  
I was thinking of having a `Filter` where I'd check which method should be invoked next (according to the route that was linked to it with `Spark.get`, `Spark.post`, etc.) and checking it's [Annotations](https://docs.oracle.com/javase/7/docs/technotes/guides/language/annotations.html) to determine if the current request should be halt or not.
