### ISSUE TITLE
Question: Possible to set static location for template files?

### ISSUE THREAD

**Issue by boyter** [perwendel/spark#892]
Probably a quick answer, but I was unable to see anything in the documentation.

I am trying to implement Spark such that users can override the templates themselves. While I get you can set the static files location which handles images I could not see a way to do so for the templates.

For example the below (from the documentation allows one to change the static location) but there is nothing to set the templates.

staticFiles.externalLocation(System.getProperty("java.io.tmpdir"));

A call which allows the setting the template location would be very useful when used in conjunction with the static files for quickly iterating through HTML changes and for allowing consumers of the applications to make HTML changes without having to recompile the application.

**Comment by tipsy** [comment]
This is a per-template-engine setting, not something you can set in Spark (or in all template engines). You can have a look at https://github.com/perwendel/spark-template-engines to see how the different engines are implemented.

**Comment by boyter** [comment]
Figured that might be the case. I will have a look through the code then. I really didn't want to modify spark proper to do it though. Thanks for the prompt response.

**Comment by joshuaavalon** [comment]
I have done this with FreeMarkerEngine. You can use `FileTemplateLoader` instead of `ClassTemplateLoader`

**Comment by boyter** [comment]
@joshuaavalon Thanks thats what I wanted to know. Did you have any code samples I could see?

**Comment by joshuaavalon** [comment]
@boyter I am writing in Kotlin but here is my translation to Java. It should work. (I did not test it)

```java
Path templatePath = Paths.get("./template") // I am using Path but you can use File instead
Configuration config = new Configuration(new Version(2, 3, 23)) // This is the version that spark is using
config.setTemplateLoader(new FileTemplateLoader(templatePath.toFile()))
FreeMarkerEngine engine = new FreeMarkerEngine(config)
```

**Comment by boyter** [comment]
Thanks. I will have a play around with this.

**Comment by tipsy** [comment]
Closing this, as I don't think we don't want a tighter coupling between Spark and template engines.
