### ISSUE TITLE
Internal Error when illegal argument in queryParams 

### ISSUE THREAD

**Issue by Matyeu** [perwendel/spark#895]
When you try to get param with GET param,
`String key= request.queryParams("key");`
if the param contains illegal argument (example: %), that cause an:

> ERROR spark.webserver.MatcherFilter - 
> java.lang.IllegalArgumentException: !hex 38
>

**Comment by tipsy** [comment]
Seems okay?

**Comment by Matyeu** [comment]
Yes but that cause an internel serveur error

**Comment by tipsy** [comment]
How do you think it should be handled?

**Comment by Matyeu** [comment]
That wasn't make an error 500

**Comment by tipsy** [comment]
But it's an illegal argument?

**Comment by Matyeu** [comment]
yes if the param contains % that return an internal server
