### ISSUE TITLE
How do I enable HTTPS or SSL communication?

### ISSUE THREAD

**Issue by kant111** [perwendel/spark#898]
How do I enable HTTPS or SSL communication? I only have a .pem file and I see that the Spark framework offers 

`secure(keystoreFilePath, keystorePassword, truststoreFilePath, truststorePassword);`

But I am not sure if should pass all the arguments ? can the arguments be null for parameters I don't have since I only have .pem file(which is a certificate) ?

**Comment by Gillingham** [comment]
http://sparkjava.com/documentation#how-do-i-enable-sslhttps make it pretty clear, you need a java key store, not a pem cert/key pair.

**Comment by tipsy** [comment]
Thanks @Gillingham
