### ISSUE TITLE
Invoking Request.body() disables Request.queryMap() and Request.queryParams()

### ISSUE THREAD

**Issue by patrickmayer0** [perwendel/spark#900]
Hi,
Bug is present in 2.6: invoking Request.body() does affect behavior of method Request.queryMap() and Request.queryParams() : both methods return  empty Map/Set if invoked after Request.body().

Simple code used to test this:
`		path("/api", () -> {

		    before("/*", (req, res) -> {

		    	// get full path info.
		    	LOG.log(Level.INFO, "Received api call: {0}", req.pathInfo());

		    	// get context path
		    	LOG.log(Level.INFO, "Context path: {0}", req.contextPath());

		    	// get headers
		    	StrBuilder sB = new StrBuilder().appendWithSeparators(req.headers(), ", ");
		    	LOG.log(Level.INFO, "Headers: {0}", sB.toString());

		    	// get host
		    	LOG.log(Level.INFO, "Host: {0} Client: {1}", new Object[] {req.host(), req.ip()});

		    	// get attributes list
		    	sB = new StrBuilder().appendWithSeparators(req.attributes(), ", ");
		    	LOG.log(Level.INFO, "Attributes: {0}", sB.toString());
		    	
                    // get body: if done here, following req.queryMap / req.queryParams() calls do not work.
		    	LOG.log(Level.INFO, "Body: {0}", req.body());
		    	
		    	// content length
		    	LOG.log(Level.INFO, "Content length: {0}, type: {1}", new Object[] {req.contentLength(), req.contentType()});
		    	
		    	// queryMap
		    	StringBuilder SB = new StringBuilder();
				for (Map.Entry<String, String[]> e : req.queryMap().toMap().entrySet()) {
					StrBuilder eB = new StrBuilder();
					eB.appendWithSeparators(e.getValue(), ",");
					SB.append(e.getKey()).append(" -> ").append(eB.toString()).append("\n");
				}
				LOG.log(Level.INFO, "QueryMap: {0}", SB.toString());
				
				// paramsMap
		    	SB = new StringBuilder();
				for (Map.Entry<String, String> e : req.params().entrySet()) {
					SB.append(e.getKey()).append(" -> ").append(e.getValue()).append("\n");
				}
				LOG.log(Level.INFO, "Params: {0}", SB.toString());
				
				// query params
				StrBuilder eB = new StrBuilder().appendWithSeparators(req.queryParams(), ",");
				LOG.log(Level.INFO, "Query params: {0}", eB.toString());
		    });
		});
`

This is the curl request I use to test this:

curl --data "param1=value1&param2=value2" http://localhost:4567/api/email/create/2

Thanks for having a look into this issue.

**Comment by jakaarl** [comment]
See #666 for a detailed discussion about this. I think this issue could be closed as a duplicate?

**Comment by tipsy** [comment]
Yes, thanks @jakaarl.

**Comment by patrickmayer0** [comment]
Hi,
Could be closed as duplicate... But should be documented: either get params
or vidy, but can't get both. Maybe mention this in Spark class javadoc?

Thanks for your quick answer!
Patrick
