### ISSUE TITLE
Exception handler forces you to cast to a specific Exception needlessly

### ISSUE THREAD

**Issue by Frietziek** [perwendel/spark#904]
Imagine you have an custom exception with custom data fields which extends Exception class. If you try to handle it in a top level of your application in the manner that spark provide, the **exception** received by the lambda handler is always an Exception, **so you have to explicit and needlessly cast it to CustomException** to access specific stuff from the last one. 

```java
Spark.exception(CustomException.class, (exception, request, response) -> {
    CustomException customException = (CustomException) exception; // exception argument is from class Exception
    // More code here...
})
```

**Comment by tipsy** [comment]
What version of Spark are you using? This was fixed some time ago.

**Comment by Frietziek** [comment]
Spark 2.6.0, it is not the last version?

**Comment by Frietziek** [comment]
Sorry, false alarm, we have a previous version of Spark when i wrote this issue, and then a partner changed it to the last version, and now we have no more this problem. Thanks anyways!
