### ISSUE TITLE
Embedded Jetty Server is not fully tunable – Complete customization would be good to overcome environment differences

### ISSUE THREAD

**Issue by tcervi** [perwendel/spark#914]
## ISSUE:  
Using the _secure()_ method has different behaviors when running on IBM JVM or Oracle JVM and the current _EmbeddedServer_ customization does not allow _SSLContext_ access to adapt application for different scenarios. This was found due to an incompatibility between Embedded Jetty and IBM Java 1.8 (probably related to _SSLContext_ use).

## ENVIRONMENT: 
 I’ve being working with Spark to provide a REST interface for a Web App. Everything went fine until I add the SSL using the method: _secure (keystore, keystorepassw, truststore, truststorepassw)_. My server provides this REST interface and I have two different environments where I deploy it: 

**1. Windows 7 + Java Oracle:** java version "1.8.0_131", Java(TM) SE Runtime Environment (build 1.8.0_131-b11), Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode).

**2. openSUSE Leap 42.3 + Java IBM:**  java version "1.8.0", Java(TM) SE Runtime Environment (build pxa6480sr4fp6-20170518_02(SR4 FP6)), IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20170516_348050 (JIT enabled, AOT enabled), J9VM - R28_20170516_1905_B348050, JIT  - tr.r14.java_20170516_348050, GC   - R28_20170516_1905_B348050_CMPRSS, J9CL - 20170516_348050, JCL - 20170516_01 based on Oracle jdk8u131-b11

## DESCRIPTION:  
When I use the _secure()_ method on Environment 1 it works fine without any effort. But when running it on Environment 2 I get a handshake_failure and my SSL connection fails every time. 
The _keystore_ used to secure these connections is the same one used by other server components and they work fine with the combination 2 (openSUSE + Java IBM). The handshake_failure was due to a fail while negotiating the Cipher with my client, something related to the default Cipher Suites I wondered. Follow a log piece where the handshake failed:

***
%% Initialized:  [Session-1, SSL_NULL_WITH_NULL_NULL]
qtp-839842820-20, fatal error: 40: no cipher suites in common
javax.net.ssl.SSLHandshakeException: no cipher suites in common
%% Invalidated:  [Session-1, SSL_NULL_WITH_NULL_NULL]
qtp-839842820-20, SEND TLSv1 ALERT:  fatal, description = handshake_failure
qtp-839842820-20, WRITE: TLSv1 Alert, length = 2
qtp-839842820-20, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLHandshakeException: no cipher suites in common

So, I started to dig into this problem because I really needed the server running over Environment 2 (even knowing that there is no official support for Spark/Jettty over Java IBM, or at least I didn’t find anything related to this).
IBM and Oracle have indeed[ different implementations](https://goo.gl/WimJjc) on their JVMs and, because of it, I wondered if the Jetty server was creating an _SSLContext_ using some JVM defaults that differ from IBM and Oracle. The other server components that could run SSL (with the same _keystore_) over the IBM JVM were probably implementing their _SSLContext_ in a way that works for both. I have logs for both scenarios: successful and unsuccessful,  where I can see the other modules selecting the “engine server matching alias” with the relative _keystore_, but the Spark module wasn’t doing it.

***
%% Initialized:  [Session-2, SSL_NULL_WITH_NULL_NULL]
ssl: ServerHandshaker.setupPrivateKeyAndChain RSA
ssl: ServerHandshaker.setupPrivateKeyAndChain, chooseEngineServerAlias app-tomcat
ssl: ServerHandshaker.setupPrivateKeyAndChain, return true
JsseJCE:  Using KeyPairGenerator EC from provider TBD via init
JsseJCE:  Using SecureRandom IBMSecureRandom from provider IBMJCE version 1.8
JsseJCE:  Using KeyPairGenerator EC from provider TBD via init
ECDHCrypt:  ECDH KeyPairGenerator  from provider from init IBMJCE version 1.8
%% Negotiating:  [Session-2, SSL_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
JsseJCE:  Using MessageDigest SHA-256 from provider IBMJCE version 1.8
*** ServerHello, TLSv1.2

My first try was to customize my Embedded Jetty Server instance and I found this Issue [#813](https://github.com/perwendel/spark/pull/813) fixed. I’ve implemented my customized Embedded Server to configure in my code the exact SSLContext parameters needed. But, for some reason, it was always “overwritten” by the Spark Default Embedded Jetty Server. Probably, something related to Issue [#883](https://github.com/perwendel/spark/issues/883) .
I was with Spark source code already open so I went inside the _SocketConnectorFactory_ and tried to set the allowed ciphers directly into my _SSLContextFactory_ (_sslContextFactory.setIncludeCipherSuites()_ ). This did not worked too, but I got some different errors where I could see my “chooseEngineServerAlias null” and the “Protocol TLS1x has no matching cipher suites”. What lead me to…

## SOLUTION: 
I explicitly set my included protocols during my SSLContexxt Factory initialization (_sslContextFactory.setIncludedProtocols(“TLSv1”,”TLSv1.1”,”TLSv1.2”)_).  Recompiled the spark-core.jar and changed it on my application.
I’m not really sure why, but now my application was able to complete the SSL Handshake. Probably the IBM “default” implementation for sslContexts and its Protocols differs from the Oracle one (My change works on both Environments IBM and Oracle).
`%% Initialized:  [Session-4, SSL_NULL_WITH_NULL_NULL]
ssl: ServerHandshaker.setupPrivateKeyAndChain EC
ssl: ServerHandshaker.setupPrivateKeyAndChain, chooseEngineServerAlias null
ssl: ServerHandshaker.setupPrivateKeyAndChain EC
ssl: ServerHandshaker.setupPrivateKeyAndChain, chooseEngineServerAlias null
ssl: ServerHandshaker.setupPrivateKeyAndChain RSA
matching alias: app-tomcat
ssl: ServerHandshaker.setupPrivateKeyAndChain, chooseEngineServerAlias app-tomcat
ssl: ServerHandshaker.setupPrivateKeyAndChain, return true
JsseJCE:  Using KeyPairGenerator EC from provider TBD via init 
JsseJCE:  Using SecureRandom IBMSecureRandom from provider IBMJCE version 1.8
JsseJCE:  Using KeyPairGenerator EC from provider TBD via init 
ECDHCrypt:  ECDH KeyPairGenerator  from provider from init IBMJCE version 1.8
%% Negotiating:  [Session-4, SSL_ECDHE_RSA_WITH_AES_256_GCM_SHA384]
JsseJCE:  Using MessageDigest SHA-384 from provider IBMJCE version `1.8``

I'm new on the open source world and I’m not an SSL expert, maybe this is not the best solution/approach but I thought it would be nice to share all this investigation :)

## CONCLUSIONS: 
I know that maybe there is no plan to support IBM Java, but I think it could be a nice pull-request for you to evaluate the solution and analyze this strange behavior in different environments. Most of all, it would be a reinforcement of Issue[ #883](https://github.com/perwendel/spark/issues/883) and the advantages of having a way to fully customize the Spark _EmbeddedServers_. With a complete customized server, Spark does not need to offer support to so many environment variations, but the users are able to code and adapt their application to work over untested scenarios.

### Obs: 
All the logs came from the JAR execution with the debug option enabled ( -Djavax.net.debug=all).
### Obs2:
 If needed, I can upload the logs and traces that I saved during my work.

**Comment by tipsy** [comment]
@tcervi I remember dealing with this before.
#883 is not correct. The custom-embedded-server works, but it has a bug: Any connector added to the custom-embedded-server will be overridden: https://github.com/perwendel/spark/blob/master/src/main/java/spark/embeddedserver/jetty/EmbeddedJettyServer.java#L96-L102

Could you try to change this part of the code to check if the server has any connectors (and don't override if it has), and see if that solves the problem?

**Comment by tcervi** [comment]
@tipsy thanks for your quick answer.
Yesterday I changed the code as you suggested and the build went well. I will test it with my custom-embedded-server and as soon as I get a result, will post back here.

Thank you again.

**Comment by tcervi** [comment]
@tipsy I changed the code you've pointed and everything went fine here. I used my old custom-server class and tested the SSL connections on both environments (Oracle and IBM JVMs).
So, how to proceed? Should I cancel (if it's possible) my previous pull-request and do a new one?

**Comment by tcervi** [comment]
@tipsy should I close this issue now that the PR was merged?

**Comment by tipsy** [comment]
Please do
