### ISSUE TITLE
how to set dirAllowed to false for embedded jetty?

### ISSUE THREAD

**Issue by zjiash** [perwendel/spark#918]
I use Spark Java and need to reach the following case. I find no way to set this parameter.
Thanks.

    <init-param>
        <param-name>dirAllowed</param-name>
        <param-value>false</param-value>
    </init-param>

**Comment by tipsy** [comment]
Are you saying Spark currently lists directories?

**Comment by zjiash** [comment]
Thanks.
Something like this: https://stackoverflow.com/questions/43284417/how-do-i-prevent-directory-listing-in-jetty
But in Spark, I use embedded jetty and have no web.xml.

**Comment by georgy7** [comment]
@zjiash @tipsy I could not reproduce this on `2.6.0`.

For instance, I set

    staticFiles.externalLocation("/home/georgy/PDF");

and I can see the file in this directory. But I could not get files from outside of this directory.

![screenshot_20170924_112315](https://user-images.githubusercontent.com/564471/30780727-cda73ef2-a11a-11e7-869a-d2f2f7292008.png)
![screenshot_20170924_112349](https://user-images.githubusercontent.com/564471/30780734-d944a452-a11a-11e7-9008-08a9e0ddc78c.png)

Also, the urls

    http://localhost:4567/../
    http://localhost:4567/../zZJxPw_tTv4.jpg

redirect to

    http://localhost:4567/
    http://localhost:4567/zZJxPw_tTv4.jpg

**Comment by tipsy** [comment]
@georgy7 Thanks, that's the expected behavior. What version are you using @zjiash ?

**Comment by zjiash** [comment]
I use `2.5`. I change to use `2.6.0` and this case disappear.
Thanks.
