### ISSUE TITLE
How to get parameters from websocket url and pass it on to handler?

### ISSUE THREAD

**Issue by kant111** [perwendel/spark#921]
Hi All,

I went through the tutorial below. However I have a slightly different case

https://sparktutorials.github.io/2015/11/08/spark-websocket-chat.html

I would like something like this 

`webSocket("/chat/:param", ChatWebSocketHandler.class);`

And in my ChatWebSocketHandler.java

I would want

 ```
   @OnWebSocketConnect
    public void onConnect(String param, Session user) throws Exception {
        System.out.println("Param: " + param + "," + "user" + user);
    }
```

**Comment by tipsy** [comment]
Spark doesn't add any sort of abstraction on top of Jetty's WebSocket API, so it looks like you'll have to do some manual parsing to achieve this. I had a quick look, and the information you want is available through `session.getUpgradeRequest().getRequestURI()`. There might be an easier way though, you should consult the Jetty WebSocket docs: http://www.eclipse.org/jetty/documentation/9.4.x/jetty-websocket-api-events.html

**Comment by kant111** [comment]
@tipsy Is this `webSocket("/chat/:param", ChatWebSocketHandler.class);` even valid? otherwords can I pass anything in that "param" such that when I do `session.getUpgradeRequest().getRequestURI()` its available?

**Comment by tipsy** [comment]
I don't think jetty supports that syntax, but hopefully it supports `/chat/*`. It would probably be simpler to use query-params though: `/chat?param=value`, then `session.getUpgradeRequest().getParameter("param")`
