### ISSUE TITLE
http benchmarks have high max latency with more connects

### ISSUE THREAD

**Issue by zjiash** [perwendel/spark#922]
I use wrk(https://github.com/wg/wrk) to test my application and find that with more connects, the QPS increases less while the max latency increase greatly.

In my case, I need support high number of connections (400~) with the relatively small peak QPS(3k~).
Can I user more threads for jetty?

With 50 threads and 200 connections, the result is as follows:

```
50 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    46.15ms   16.49ms 819.51ms   86.99%
    Req/Sec    86.83     14.99   363.00     74.77%
  Latency Distribution
     50%   52.14ms
     75%   52.99ms
     90%   54.03ms
     99%   62.09ms
  130769 requests in 30.10s, 43.06MB read
  Socket errors: connect 0, read 0, write 0, timeout 2
Requests/sec:   4344.45
Transfer/sec:      1.43MB
```

With 10 threads and 50 connections, the result is as follows:

```
10 threads and 50 connections  
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    15.48ms   14.34ms 361.13ms   89.98%
    Req/Sec   364.41     77.30   590.00     69.48%
  Latency Distribution
     50%   12.52ms
     75%   19.51ms
     90%   29.86ms
     99%   53.63ms
  217863 requests in 1.00m, 71.67MB read
Requests/sec:   3627.37
Transfer/sec:      1.19MB
```

**Comment by tipsy** [comment]
Yes, you can configure the jetty-server however you want. Threadcount even has a covenience-api: http://sparkjava.com/documentation#threadpool. Spark adds very little overhead to Jetty itself (less than 0.1% I believe someone concluded), so see if you can find a Jetty performance guide.
