### ISSUE TITLE
Missing test dependencies

### ISSUE THREAD

**Issue by mirkoperillo** [perwendel/spark#926]
Hi, 
I cloned a fresh copy of spark, but it seems that some test dependencies are missing.

`CookieIntegrationTest` doesn't compile because `org.apache.http.HttpResponse` is missing, and generally none of the test run because they indirectly need some class in org.apache.http.*

Do you confirm this problem ?
( If yes I can propose a PR about )

**Comment by AussieGuy0** [comment]
`HttpResponse` gets pulled in via this dependency in the pom:

```xml
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.1</version>
            <scope>test</scope>
        </dependency>
```

It must be a problem with that dependency not being downloaded on your end. Try running `mvn -U` to reimport all the dependencies.

**Comment by tipsy** [comment]
This should work fine.

**Comment by mirkoperillo** [comment]
Sorry for the false alarm.
In my local repository there was a broken parent pom for httpclient 4.5.1 so maven wasn't able to resolve the transitive dependencies for it.
