### ISSUE TITLE
Please publish binary releases

### ISSUE THREAD

**Issue by cliffbdf** [perwendel/spark#928]
Hi - it would be really helpful if this project published binary releases (e.g., as a jar). I don't use maven or gradle because my projects often include a mix of Java and other languages (e.g., Go) as well as tools for which there is no maven or gradle task (e.g., compiler generators), and so I use make - and for that I need a binary distribution that I can pull. Having to download the spark source project, set up maven (which I don't normally use), and build from source is burdensome. Thanks!

PS - of course one can obtain it from maven central, but it would be nice to obtain it directly from where it is published from.
Maven Central location:
http://search.maven.org/remotecontent?filepath=com/sparkjava/spark-core/2.6.0/spark-core-2.6.0.jar

PPS - Spark is a fantastic tool. Thanks for creating it!

**Comment by toyknight** [comment]
http://search.maven.org/remotecontent?filepath=com/sparkjava/spark-core/
Let's save this to bookmarks and consider it published ;)

**Comment by tipsy** [comment]
I don't really understand what you want us to do. Maven is where we publish, so that's about as direct as you'll get it.

**Comment by cliffbdf** [comment]
Maven is fine for people who use only Java. It is not so fine for projects that use a mixture of languages, and a mix is my norm (I often use both Go and Java in the same project). I therefore don’t use maven or gradle - I use make. When a github project says “use maven or gradle” that is always frustrating to me - I have to go hunting for the jar files.

Perhaps have a link to the Maven Central JAR file(s)?

Side question:
I know that you guys trust Maven Central, but how does someone know that the binary that is posted there came from you? Could it come from someone else and contain a malicious payload? Are you the ones who push to Maven Central? Can someone else? Does Maven Central list version history? How do I know that the JAR file there is the one that you built? If it were obtained from github as a release binary, there is history there, and I could see who published it. Maybe Maven Central has that, but as I explained, I don’t use maven so I am not sure. Bottom like, please be friendly to folks who don’t only use Java and who are not regular uses of maven ;-)

Thanks!

Once again, thanks for a fantastic piece of code!!!!! (SparkJava)

**Comment by tipsy** [comment]
> Perhaps have a link to the Maven Central JAR file(s)?

That we can do. Added the link @toyknight suggested to the download-page: http://sparkjava.com/download

To answer a very small part of your side-question: @perwendel is the only one who can push to Maven (afaik). You can't change/remove files once they have been published on Maven.

**Comment by cliffbdf** [comment]
> On Oct 9, 2017, at 1:24 PM, David <notifications@github.com> wrote:
> 
> Perhaps have a link to the Maven Central JAR file(s)?
> 
> That we can do. Added the link @toyknight <https://github.com/toyknight> suggested to the download-page: http://sparkjava.com/download <http://sparkjava.com/download>
> To answer a very small part of your side-question: @perwendel <https://github.com/perwendel> is the only one who can push to Maven (afaik). You can't change/remove files once they have been published on Maven.
> 

Good to know. Thanks for taking a question from a non-mavener!

Long Live Spark Java!!
