### ISSUE TITLE
Jetty specific import in spark.Request

### ISSUE THREAD

**Issue by sf-git** [perwendel/spark#941]
Hi,

SparkJava release 2.7.0 has a Jetty specific import org.eclipse.jetty.util.URIUtil; in spark.Request (line 34)

Now org.eclipse.jetty.util should be in your classpath even if you deploy Spark application on external servlet container (Tomcat, etc.)

Thanks.

**Comment by tipsy** [comment]
Looks like this PR introduced it: https://github.com/perwendel/spark/pull/872/files

**Comment by perwendel** [comment]
This is bad! We'll fix ASAP and release 2.7.1

**Comment by tipsy** [comment]
Fixed and released already.
