### ISSUE TITLE
Q: Different routes, identical targets - possible?

### ISSUE THREAD

**Issue by neilyoung** [perwendel/spark#947]
Hi, is it possible to have the same target handler being accessed using different routes?

E.g. get("/") should be handled like get("/index.html")

**Comment by tipsy** [comment]
```
Route myRoute = ...
get("/", myRoute);
get("/index.html", myRoute)

or

Class myClass {
    String myRoute(Request request, Response response) { ... }
}

get("/", myClass::myRoute);
get("/index.html",  myClass::myRoute)
```

**Comment by codemon2002** [comment]
I think a possible future feature would be an array or list of strings can
be put into the first parameter of "get(...)" Or "post(...)".  That would
group up multiple routes to the same function.

**Comment by neilyoung** [comment]
@codemon2002 : This is exactly the solution I would like and had actually in mind.

**Comment by perwendel** [comment]
I see no reason for this functionality. The provided example by @tipsy is a much clearer way of achieving this than pushing and array to the get,post,... functions
