### ISSUE TITLE
Set HttpOnly  for all Cookies

### ISSUE THREAD

**Issue by M-Razavi** [perwendel/spark#949]
I asked this question on Stack-overflow but unfortunately there is no answer for it. Would you please give me a solution to set HttpOnly for all cookies ?

There are some solution on StackOverflow to create a new embedded server and customize it, but only works for version 2.6 . Is there any solution for version 2.7?

https://stackoverflow.com/questions/47525841/set-httponly-for-all-cookies-in-spark-java

**Comment by perwendel** [comment]
If I don't remember incorrectly this has a fix. #1027

**Comment by tipsy** [comment]
Should be fixed, yeah.
