### ISSUE TITLE
Routes should match with and without trailing slash

### ISSUE THREAD

**Issue by jsnoriegam** [perwendel/spark#97]
It would be nice if "/route" match "/route" and also "/route/"
Not a big issue.  but some browsers put the trailing slash automatically, so sometimes it's annoying.

**Comment by otaviofff** [comment]
Any particular reason why this feature wasn't accepted?

**Comment by JohnStarich** [comment]
I would also like to know why this wasn't accepted. I would very much like this feature.

A trailing slash is often added to request URLs and, as far as I know, it is still the same meaning for RESTful operations.

**Comment by scaryclam** [comment]
Ditto for me. This would remove a lot of duplicated routes

**Comment by AzureusNation** [comment]
Technically they are all different routes /route and /route/ are different from each other. So Spark is preforming the correct action that needs to be done.

**Comment by JohnStarich** [comment]
Perhaps there could be a built-in configuration option for Spark that would allow for both routes to be created with the same handler (that defaults to off)?

**Comment by ryber** [comment]
The URI spec says they are different only if they are actually different, and if they are the same then one should redirect to the other. Remember that this mostly comes from Unix file systems where no-slash means file and a slash means folder. In terms of most websites and the expectations of most end users the expectation is that they are the same. I would suggest there be a option to force redirects to / automatically and that this option is on by default.

https://tools.ietf.org/html/rfc3986#section-6.2.4
