### ISSUE TITLE
What is the recommended way of deploying a Sparkjava app?

### ISSUE THREAD

**Issue by p-h** [perwendel/spark#979]
The docs don't talk much about what a deployment environment would look like, except for [this](http://sparkjava.com/documentation#other-web-server). How would I, for example, go about deploying a Sparkjava app on a classic on premise Ubuntu server? Do I need an Application Server? Do I copy an uber jar to the server and write systemd unit file?

**Comment by tipsy** [comment]
Just create a jar with dependencies and run it as any other jar (`java -jar file`). There is a tutorial on the web page for deploying to Heroku.

**Comment by p-h** [comment]
[This](https://sparktutorials.github.io/2015/08/24/spark-heroku.html)? I don't know how this applies to people not deploying on Heroku.

**Comment by tipsy** [comment]
It's the same procedure more or less anywhere. Just build a fat jar and run it.

**Comment by dbrezack** [comment]
Either you run it as java -jar myServer.jar or you can setup spark to run on something like a Tomcat server if you setup a tomcat server you can also setup gradle/maven to build the project as a war. Its even possible to configure both if you want to run a local and deployment based versions,

**Comment by p-h** [comment]
So do you ssh into your server, `java -jar myApp.jar`, and hope that the ssh connection doesn't crash? That the app doesn't crash and doesn't need to be restarted?

**Comment by jakaarl** [comment]
@p-h I think the question is more deployment environment than Spark specific. If you deploy as a runnable JAR, you should write a service wrapper (quick googling turned up for example this: https://dzone.com/articles/run-your-java-application-as-a-service-on-ubuntu). I guess `daemontools` and/or `supervise` would also be worth looking into.

**Comment by p-h** [comment]
@jakaarl Thank you, that's what I was looking for. 👍

**Comment by p-h** [comment]
gg
