### ISSUE TITLE
JettyServerFactory is not a functional interface multiple non-overriding abstract methods found in interface spark.embeddedserver.jetty.JettyServerFactory

### ISSUE THREAD

**Issue by coreyjackwilson** [perwendel/spark#990]
From: [http://sparkjava.com/tutorials/jetty-request-log](http://sparkjava.com/tutorials/jetty-request-log)

### Error occurs with class:

```
public static void main(String[] args) {
    port(8181);
    Logger logger = Logger.getLogger(MirApplication.class);
    

    EmbeddedServers.add(EmbeddedServers.Identifiers.JETTY, new EmbeddedJettyFactory((i, j, k) -> {
      Server server = new Server();
      server.setRequestLog(logger);
      return server;
    }));



    get("/hello", (req, res) -> "Hello World");
  }
```

### Error message

`java: incompatible types: spark.embeddedserver.jetty.JettyServerFactory is not a functional interface multiple non-overriding abstract methods found in interface spark.embeddedserver.jetty.JettyServerFactory`

Please advise

**Comment by victorwss** [comment]
Which Jetty and Spark versions are you using?

**Comment by coreyjackwilson** [comment]
This is the most recent Spark: 2.7.1
The Jetty that comes with Spark: 9.4.5.v20170502

**Comment by esamson33** [comment]
I tried using an anonymous class instead of the lambda expression and it works.
