### ISSUE TITLE
staticFiles.externalLocation from before filter

### ISSUE THREAD

**Issue by randohinn** [perwendel/spark#993]
Hello

Is there a way to use `staticFiles.externalLocation` from inside a `before` filter? Currently, this gives me a `This must be done before route mapping has begun` error. 

Use case: my before filter determines the subdomain that has been hit, and needs to set the static directory based on that.

**Comment by randohinn** [comment]
@perwendel ?

**Comment by tipsy** [comment]
No, it's a configuration option, it has to be done before server start. The server is automatically started upon route mapping.
